; a01: reg,reg for every two-operand op, r8-r15 in both positions
.CODE
f PROC
        mov     rax,rcx
        mov     rcx,rax
        mov     rax,r8
        mov     r8,rax
        mov     r9,r10
        mov     r15,r14
        mov     rsp,rbp
        mov     rbp,rsp
        mov     rsi,rdi
        mov     rdi,rsi
        mov     r12,r13
        mov     r13,r12
        mov     rbx,rdx
        mov     eax,ecx
        mov     ecx,eax
        mov     eax,r8d
        mov     r8d,eax
        mov     r9d,r10d
        mov     r15d,r14d
        mov     esp,ebp
        mov     esi,edi
        mov     r12d,r13d
        add     rax,rcx
        add     rcx,rax
        add     rax,r8
        add     r8,rax
        add     r9,r10
        add     r15,r14
        add     rsp,rbp
        add     rbp,rsp
        add     rsi,rdi
        add     rdi,rsi
        add     r12,r13
        add     r13,r12
        add     rbx,rdx
        add     eax,ecx
        add     ecx,eax
        add     eax,r8d
        add     r8d,eax
        add     r9d,r10d
        add     r15d,r14d
        add     esp,ebp
        add     esi,edi
        add     r12d,r13d
        or     rax,rcx
        or     rcx,rax
        or     rax,r8
        or     r8,rax
        or     r9,r10
        or     r15,r14
        or     rsp,rbp
        or     rbp,rsp
        or     rsi,rdi
        or     rdi,rsi
        or     r12,r13
        or     r13,r12
        or     rbx,rdx
        or     eax,ecx
        or     ecx,eax
        or     eax,r8d
        or     r8d,eax
        or     r9d,r10d
        or     r15d,r14d
        or     esp,ebp
        or     esi,edi
        or     r12d,r13d
        adc     rax,rcx
        adc     rcx,rax
        adc     rax,r8
        adc     r8,rax
        adc     r9,r10
        adc     r15,r14
        adc     rsp,rbp
        adc     rbp,rsp
        adc     rsi,rdi
        adc     rdi,rsi
        adc     r12,r13
        adc     r13,r12
        adc     rbx,rdx
        adc     eax,ecx
        adc     ecx,eax
        adc     eax,r8d
        adc     r8d,eax
        adc     r9d,r10d
        adc     r15d,r14d
        adc     esp,ebp
        adc     esi,edi
        adc     r12d,r13d
        sbb     rax,rcx
        sbb     rcx,rax
        sbb     rax,r8
        sbb     r8,rax
        sbb     r9,r10
        sbb     r15,r14
        sbb     rsp,rbp
        sbb     rbp,rsp
        sbb     rsi,rdi
        sbb     rdi,rsi
        sbb     r12,r13
        sbb     r13,r12
        sbb     rbx,rdx
        sbb     eax,ecx
        sbb     ecx,eax
        sbb     eax,r8d
        sbb     r8d,eax
        sbb     r9d,r10d
        sbb     r15d,r14d
        sbb     esp,ebp
        sbb     esi,edi
        sbb     r12d,r13d
        and     rax,rcx
        and     rcx,rax
        and     rax,r8
        and     r8,rax
        and     r9,r10
        and     r15,r14
        and     rsp,rbp
        and     rbp,rsp
        and     rsi,rdi
        and     rdi,rsi
        and     r12,r13
        and     r13,r12
        and     rbx,rdx
        and     eax,ecx
        and     ecx,eax
        and     eax,r8d
        and     r8d,eax
        and     r9d,r10d
        and     r15d,r14d
        and     esp,ebp
        and     esi,edi
        and     r12d,r13d
        sub     rax,rcx
        sub     rcx,rax
        sub     rax,r8
        sub     r8,rax
        sub     r9,r10
        sub     r15,r14
        sub     rsp,rbp
        sub     rbp,rsp
        sub     rsi,rdi
        sub     rdi,rsi
        sub     r12,r13
        sub     r13,r12
        sub     rbx,rdx
        sub     eax,ecx
        sub     ecx,eax
        sub     eax,r8d
        sub     r8d,eax
        sub     r9d,r10d
        sub     r15d,r14d
        sub     esp,ebp
        sub     esi,edi
        sub     r12d,r13d
        xor     rax,rcx
        xor     rcx,rax
        xor     rax,r8
        xor     r8,rax
        xor     r9,r10
        xor     r15,r14
        xor     rsp,rbp
        xor     rbp,rsp
        xor     rsi,rdi
        xor     rdi,rsi
        xor     r12,r13
        xor     r13,r12
        xor     rbx,rdx
        xor     eax,ecx
        xor     ecx,eax
        xor     eax,r8d
        xor     r8d,eax
        xor     r9d,r10d
        xor     r15d,r14d
        xor     esp,ebp
        xor     esi,edi
        xor     r12d,r13d
        cmp     rax,rcx
        cmp     rcx,rax
        cmp     rax,r8
        cmp     r8,rax
        cmp     r9,r10
        cmp     r15,r14
        cmp     rsp,rbp
        cmp     rbp,rsp
        cmp     rsi,rdi
        cmp     rdi,rsi
        cmp     r12,r13
        cmp     r13,r12
        cmp     rbx,rdx
        cmp     eax,ecx
        cmp     ecx,eax
        cmp     eax,r8d
        cmp     r8d,eax
        cmp     r9d,r10d
        cmp     r15d,r14d
        cmp     esp,ebp
        cmp     esi,edi
        cmp     r12d,r13d
        test     rax,rcx
        test     rcx,rax
        test     rax,r8
        test     r8,rax
        test     r9,r10
        test     r15,r14
        test     rsp,rbp
        test     rbp,rsp
        test     rsi,rdi
        test     rdi,rsi
        test     r12,r13
        test     r13,r12
        test     rbx,rdx
        test     eax,ecx
        test     ecx,eax
        test     eax,r8d
        test     r8d,eax
        test     r9d,r10d
        test     r15d,r14d
        test     esp,ebp
        test     esi,edi
        test     r12d,r13d
        ret
f ENDP
END
