; a14-movx - generated by gen.py, ml64 is the oracle
.DATA
v8 DB 0
v16 DW 0
v32 DD 0
v64 DQ 0
.CODE
f PROC
  movzx ax, al
  movzx ax, cl
  movzx ax, ah
  movzx ax, sil
  movzx ax, r9b
  movzx ax, byte ptr [rbx]
  movzx cx, al
  movzx cx, cl
  movzx cx, ah
  movzx cx, sil
  movzx cx, r9b
  movzx cx, byte ptr [rbx]
  movzx dx, al
  movzx dx, cl
  movzx dx, ah
  movzx dx, sil
  movzx dx, r9b
  movzx dx, byte ptr [rbx]
  movzx bx, al
  movzx bx, cl
  movzx bx, ah
  movzx bx, sil
  movzx bx, r9b
  movzx bx, byte ptr [rbx]
  movzx sp, al
  movzx sp, cl
  movzx sp, ah
  movzx sp, sil
  movzx sp, r9b
  movzx sp, byte ptr [rbx]
  movzx bp, al
  movzx bp, cl
  movzx bp, ah
  movzx bp, sil
  movzx bp, r9b
  movzx bp, byte ptr [rbx]
  movzx si, al
  movzx si, cl
  movzx si, ah
  movzx si, sil
  movzx si, r9b
  movzx si, byte ptr [rbx]
  movzx di, al
  movzx di, cl
  movzx di, ah
  movzx di, sil
  movzx di, r9b
  movzx di, byte ptr [rbx]
  movzx r8w, al
  movzx r8w, cl
  movzx r8w, sil
  movzx r8w, r9b
  movzx r8w, byte ptr [rbx]
  movzx r9w, al
  movzx r9w, cl
  movzx r9w, sil
  movzx r9w, r9b
  movzx r9w, byte ptr [rbx]
  movzx r10w, al
  movzx r10w, cl
  movzx r10w, sil
  movzx r10w, r9b
  movzx r10w, byte ptr [rbx]
  movzx r11w, al
  movzx r11w, cl
  movzx r11w, sil
  movzx r11w, r9b
  movzx r11w, byte ptr [rbx]
  movzx r12w, al
  movzx r12w, cl
  movzx r12w, sil
  movzx r12w, r9b
  movzx r12w, byte ptr [rbx]
  movzx r13w, al
  movzx r13w, cl
  movzx r13w, sil
  movzx r13w, r9b
  movzx r13w, byte ptr [rbx]
  movzx r14w, al
  movzx r14w, cl
  movzx r14w, sil
  movzx r14w, r9b
  movzx r14w, byte ptr [rbx]
  movzx r15w, al
  movzx r15w, cl
  movzx r15w, sil
  movzx r15w, r9b
  movzx r15w, byte ptr [rbx]
  movzx eax, al
  movzx eax, cl
  movzx eax, dl
  movzx eax, bl
  movzx eax, ah
  movzx eax, ch
  movzx eax, dh
  movzx eax, bh
  movzx eax, spl
  movzx eax, bpl
  movzx eax, sil
  movzx eax, dil
  movzx eax, r8b
  movzx eax, r9b
  movzx eax, r10b
  movzx eax, r11b
  movzx eax, r12b
  movzx eax, r13b
  movzx eax, r14b
  movzx eax, r15b
  movzx eax, ax
  movzx eax, cx
  movzx eax, dx
  movzx eax, bx
  movzx eax, sp
  movzx eax, bp
  movzx eax, si
  movzx eax, di
  movzx eax, r8w
  movzx eax, r9w
  movzx eax, r10w
  movzx eax, r11w
  movzx eax, r12w
  movzx eax, r13w
  movzx eax, r14w
  movzx eax, r15w
  movzx eax, byte ptr [rbx]
  movzx eax, byte ptr [r13+8]
  movzx eax, byte ptr [r12+rax*2+3]
  movzx eax, byte ptr [v8]
  movzx eax, word ptr [rbx]
  movzx eax, word ptr [r13+8]
  movzx eax, word ptr [v16]
  movzx ecx, al
  movzx ecx, cl
  movzx ecx, dl
  movzx ecx, bl
  movzx ecx, ah
  movzx ecx, ch
  movzx ecx, dh
  movzx ecx, bh
  movzx ecx, spl
  movzx ecx, bpl
  movzx ecx, sil
  movzx ecx, dil
  movzx ecx, r8b
  movzx ecx, r9b
  movzx ecx, r10b
  movzx ecx, r11b
  movzx ecx, r12b
  movzx ecx, r13b
  movzx ecx, r14b
  movzx ecx, r15b
  movzx ecx, ax
  movzx ecx, cx
  movzx ecx, dx
  movzx ecx, bx
  movzx ecx, sp
  movzx ecx, bp
  movzx ecx, si
  movzx ecx, di
  movzx ecx, r8w
  movzx ecx, r9w
  movzx ecx, r10w
  movzx ecx, r11w
  movzx ecx, r12w
  movzx ecx, r13w
  movzx ecx, r14w
  movzx ecx, r15w
  movzx ecx, byte ptr [rbx]
  movzx ecx, byte ptr [r13+8]
  movzx ecx, byte ptr [r12+rax*2+3]
  movzx ecx, byte ptr [v8]
  movzx ecx, word ptr [rbx]
  movzx ecx, word ptr [r13+8]
  movzx ecx, word ptr [v16]
  movzx edx, al
  movzx edx, cl
  movzx edx, dl
  movzx edx, bl
  movzx edx, ah
  movzx edx, ch
  movzx edx, dh
  movzx edx, bh
  movzx edx, spl
  movzx edx, bpl
  movzx edx, sil
  movzx edx, dil
  movzx edx, r8b
  movzx edx, r9b
  movzx edx, r10b
  movzx edx, r11b
  movzx edx, r12b
  movzx edx, r13b
  movzx edx, r14b
  movzx edx, r15b
  movzx edx, ax
  movzx edx, cx
  movzx edx, dx
  movzx edx, bx
  movzx edx, sp
  movzx edx, bp
  movzx edx, si
  movzx edx, di
  movzx edx, r8w
  movzx edx, r9w
  movzx edx, r10w
  movzx edx, r11w
  movzx edx, r12w
  movzx edx, r13w
  movzx edx, r14w
  movzx edx, r15w
  movzx edx, byte ptr [rbx]
  movzx edx, byte ptr [r13+8]
  movzx edx, byte ptr [r12+rax*2+3]
  movzx edx, byte ptr [v8]
  movzx edx, word ptr [rbx]
  movzx edx, word ptr [r13+8]
  movzx edx, word ptr [v16]
  movzx ebx, al
  movzx ebx, cl
  movzx ebx, dl
  movzx ebx, bl
  movzx ebx, ah
  movzx ebx, ch
  movzx ebx, dh
  movzx ebx, bh
  movzx ebx, spl
  movzx ebx, bpl
  movzx ebx, sil
  movzx ebx, dil
  movzx ebx, r8b
  movzx ebx, r9b
  movzx ebx, r10b
  movzx ebx, r11b
  movzx ebx, r12b
  movzx ebx, r13b
  movzx ebx, r14b
  movzx ebx, r15b
  movzx ebx, ax
  movzx ebx, cx
  movzx ebx, dx
  movzx ebx, bx
  movzx ebx, sp
  movzx ebx, bp
  movzx ebx, si
  movzx ebx, di
  movzx ebx, r8w
  movzx ebx, r9w
  movzx ebx, r10w
  movzx ebx, r11w
  movzx ebx, r12w
  movzx ebx, r13w
  movzx ebx, r14w
  movzx ebx, r15w
  movzx ebx, byte ptr [rbx]
  movzx ebx, byte ptr [r13+8]
  movzx ebx, byte ptr [r12+rax*2+3]
  movzx ebx, byte ptr [v8]
  movzx ebx, word ptr [rbx]
  movzx ebx, word ptr [r13+8]
  movzx ebx, word ptr [v16]
  movzx esp, al
  movzx esp, cl
  movzx esp, dl
  movzx esp, bl
  movzx esp, ah
  movzx esp, ch
  movzx esp, dh
  movzx esp, bh
  movzx esp, spl
  movzx esp, bpl
  movzx esp, sil
  movzx esp, dil
  movzx esp, r8b
  movzx esp, r9b
  movzx esp, r10b
  movzx esp, r11b
  movzx esp, r12b
  movzx esp, r13b
  movzx esp, r14b
  movzx esp, r15b
  movzx esp, ax
  movzx esp, cx
  movzx esp, dx
  movzx esp, bx
  movzx esp, sp
  movzx esp, bp
  movzx esp, si
  movzx esp, di
  movzx esp, r8w
  movzx esp, r9w
  movzx esp, r10w
  movzx esp, r11w
  movzx esp, r12w
  movzx esp, r13w
  movzx esp, r14w
  movzx esp, r15w
  movzx esp, byte ptr [rbx]
  movzx esp, byte ptr [r13+8]
  movzx esp, byte ptr [r12+rax*2+3]
  movzx esp, byte ptr [v8]
  movzx esp, word ptr [rbx]
  movzx esp, word ptr [r13+8]
  movzx esp, word ptr [v16]
  movzx ebp, al
  movzx ebp, cl
  movzx ebp, dl
  movzx ebp, bl
  movzx ebp, ah
  movzx ebp, ch
  movzx ebp, dh
  movzx ebp, bh
  movzx ebp, spl
  movzx ebp, bpl
  movzx ebp, sil
  movzx ebp, dil
  movzx ebp, r8b
  movzx ebp, r9b
  movzx ebp, r10b
  movzx ebp, r11b
  movzx ebp, r12b
  movzx ebp, r13b
  movzx ebp, r14b
  movzx ebp, r15b
  movzx ebp, ax
  movzx ebp, cx
  movzx ebp, dx
  movzx ebp, bx
  movzx ebp, sp
  movzx ebp, bp
  movzx ebp, si
  movzx ebp, di
  movzx ebp, r8w
  movzx ebp, r9w
  movzx ebp, r10w
  movzx ebp, r11w
  movzx ebp, r12w
  movzx ebp, r13w
  movzx ebp, r14w
  movzx ebp, r15w
  movzx ebp, byte ptr [rbx]
  movzx ebp, byte ptr [r13+8]
  movzx ebp, byte ptr [r12+rax*2+3]
  movzx ebp, byte ptr [v8]
  movzx ebp, word ptr [rbx]
  movzx ebp, word ptr [r13+8]
  movzx ebp, word ptr [v16]
  movzx esi, al
  movzx esi, cl
  movzx esi, dl
  movzx esi, bl
  movzx esi, ah
  movzx esi, ch
  movzx esi, dh
  movzx esi, bh
  movzx esi, spl
  movzx esi, bpl
  movzx esi, sil
  movzx esi, dil
  movzx esi, r8b
  movzx esi, r9b
  movzx esi, r10b
  movzx esi, r11b
  movzx esi, r12b
  movzx esi, r13b
  movzx esi, r14b
  movzx esi, r15b
  movzx esi, ax
  movzx esi, cx
  movzx esi, dx
  movzx esi, bx
  movzx esi, sp
  movzx esi, bp
  movzx esi, si
  movzx esi, di
  movzx esi, r8w
  movzx esi, r9w
  movzx esi, r10w
  movzx esi, r11w
  movzx esi, r12w
  movzx esi, r13w
  movzx esi, r14w
  movzx esi, r15w
  movzx esi, byte ptr [rbx]
  movzx esi, byte ptr [r13+8]
  movzx esi, byte ptr [r12+rax*2+3]
  movzx esi, byte ptr [v8]
  movzx esi, word ptr [rbx]
  movzx esi, word ptr [r13+8]
  movzx esi, word ptr [v16]
  movzx edi, al
  movzx edi, cl
  movzx edi, dl
  movzx edi, bl
  movzx edi, ah
  movzx edi, ch
  movzx edi, dh
  movzx edi, bh
  movzx edi, spl
  movzx edi, bpl
  movzx edi, sil
  movzx edi, dil
  movzx edi, r8b
  movzx edi, r9b
  movzx edi, r10b
  movzx edi, r11b
  movzx edi, r12b
  movzx edi, r13b
  movzx edi, r14b
  movzx edi, r15b
  movzx edi, ax
  movzx edi, cx
  movzx edi, dx
  movzx edi, bx
  movzx edi, sp
  movzx edi, bp
  movzx edi, si
  movzx edi, di
  movzx edi, r8w
  movzx edi, r9w
  movzx edi, r10w
  movzx edi, r11w
  movzx edi, r12w
  movzx edi, r13w
  movzx edi, r14w
  movzx edi, r15w
  movzx edi, byte ptr [rbx]
  movzx edi, byte ptr [r13+8]
  movzx edi, byte ptr [r12+rax*2+3]
  movzx edi, byte ptr [v8]
  movzx edi, word ptr [rbx]
  movzx edi, word ptr [r13+8]
  movzx edi, word ptr [v16]
  movzx r8d, al
  movzx r8d, cl
  movzx r8d, dl
  movzx r8d, bl
  movzx r8d, spl
  movzx r8d, bpl
  movzx r8d, sil
  movzx r8d, dil
  movzx r8d, r8b
  movzx r8d, r9b
  movzx r8d, r10b
  movzx r8d, r11b
  movzx r8d, r12b
  movzx r8d, r13b
  movzx r8d, r14b
  movzx r8d, r15b
  movzx r8d, ax
  movzx r8d, cx
  movzx r8d, dx
  movzx r8d, bx
  movzx r8d, sp
  movzx r8d, bp
  movzx r8d, si
  movzx r8d, di
  movzx r8d, r8w
  movzx r8d, r9w
  movzx r8d, r10w
  movzx r8d, r11w
  movzx r8d, r12w
  movzx r8d, r13w
  movzx r8d, r14w
  movzx r8d, r15w
  movzx r8d, byte ptr [rbx]
  movzx r8d, byte ptr [r13+8]
  movzx r8d, byte ptr [r12+rax*2+3]
  movzx r8d, byte ptr [v8]
  movzx r8d, word ptr [rbx]
  movzx r8d, word ptr [r13+8]
  movzx r8d, word ptr [v16]
  movzx r9d, al
  movzx r9d, cl
  movzx r9d, dl
  movzx r9d, bl
  movzx r9d, spl
  movzx r9d, bpl
  movzx r9d, sil
  movzx r9d, dil
  movzx r9d, r8b
  movzx r9d, r9b
  movzx r9d, r10b
  movzx r9d, r11b
  movzx r9d, r12b
  movzx r9d, r13b
  movzx r9d, r14b
  movzx r9d, r15b
  movzx r9d, ax
  movzx r9d, cx
  movzx r9d, dx
  movzx r9d, bx
  movzx r9d, sp
  movzx r9d, bp
  movzx r9d, si
  movzx r9d, di
  movzx r9d, r8w
  movzx r9d, r9w
  movzx r9d, r10w
  movzx r9d, r11w
  movzx r9d, r12w
  movzx r9d, r13w
  movzx r9d, r14w
  movzx r9d, r15w
  movzx r9d, byte ptr [rbx]
  movzx r9d, byte ptr [r13+8]
  movzx r9d, byte ptr [r12+rax*2+3]
  movzx r9d, byte ptr [v8]
  movzx r9d, word ptr [rbx]
  movzx r9d, word ptr [r13+8]
  movzx r9d, word ptr [v16]
  movzx r10d, al
  movzx r10d, cl
  movzx r10d, dl
  movzx r10d, bl
  movzx r10d, spl
  movzx r10d, bpl
  movzx r10d, sil
  movzx r10d, dil
  movzx r10d, r8b
  movzx r10d, r9b
  movzx r10d, r10b
  movzx r10d, r11b
  movzx r10d, r12b
  movzx r10d, r13b
  movzx r10d, r14b
  movzx r10d, r15b
  movzx r10d, ax
  movzx r10d, cx
  movzx r10d, dx
  movzx r10d, bx
  movzx r10d, sp
  movzx r10d, bp
  movzx r10d, si
  movzx r10d, di
  movzx r10d, r8w
  movzx r10d, r9w
  movzx r10d, r10w
  movzx r10d, r11w
  movzx r10d, r12w
  movzx r10d, r13w
  movzx r10d, r14w
  movzx r10d, r15w
  movzx r10d, byte ptr [rbx]
  movzx r10d, byte ptr [r13+8]
  movzx r10d, byte ptr [r12+rax*2+3]
  movzx r10d, byte ptr [v8]
  movzx r10d, word ptr [rbx]
  movzx r10d, word ptr [r13+8]
  movzx r10d, word ptr [v16]
  movzx r11d, al
  movzx r11d, cl
  movzx r11d, dl
  movzx r11d, bl
  movzx r11d, spl
  movzx r11d, bpl
  movzx r11d, sil
  movzx r11d, dil
  movzx r11d, r8b
  movzx r11d, r9b
  movzx r11d, r10b
  movzx r11d, r11b
  movzx r11d, r12b
  movzx r11d, r13b
  movzx r11d, r14b
  movzx r11d, r15b
  movzx r11d, ax
  movzx r11d, cx
  movzx r11d, dx
  movzx r11d, bx
  movzx r11d, sp
  movzx r11d, bp
  movzx r11d, si
  movzx r11d, di
  movzx r11d, r8w
  movzx r11d, r9w
  movzx r11d, r10w
  movzx r11d, r11w
  movzx r11d, r12w
  movzx r11d, r13w
  movzx r11d, r14w
  movzx r11d, r15w
  movzx r11d, byte ptr [rbx]
  movzx r11d, byte ptr [r13+8]
  movzx r11d, byte ptr [r12+rax*2+3]
  movzx r11d, byte ptr [v8]
  movzx r11d, word ptr [rbx]
  movzx r11d, word ptr [r13+8]
  movzx r11d, word ptr [v16]
  movzx r12d, al
  movzx r12d, cl
  movzx r12d, dl
  movzx r12d, bl
  movzx r12d, spl
  movzx r12d, bpl
  movzx r12d, sil
  movzx r12d, dil
  movzx r12d, r8b
  movzx r12d, r9b
  movzx r12d, r10b
  movzx r12d, r11b
  movzx r12d, r12b
  movzx r12d, r13b
  movzx r12d, r14b
  movzx r12d, r15b
  movzx r12d, ax
  movzx r12d, cx
  movzx r12d, dx
  movzx r12d, bx
  movzx r12d, sp
  movzx r12d, bp
  movzx r12d, si
  movzx r12d, di
  movzx r12d, r8w
  movzx r12d, r9w
  movzx r12d, r10w
  movzx r12d, r11w
  movzx r12d, r12w
  movzx r12d, r13w
  movzx r12d, r14w
  movzx r12d, r15w
  movzx r12d, byte ptr [rbx]
  movzx r12d, byte ptr [r13+8]
  movzx r12d, byte ptr [r12+rax*2+3]
  movzx r12d, byte ptr [v8]
  movzx r12d, word ptr [rbx]
  movzx r12d, word ptr [r13+8]
  movzx r12d, word ptr [v16]
  movzx r13d, al
  movzx r13d, cl
  movzx r13d, dl
  movzx r13d, bl
  movzx r13d, spl
  movzx r13d, bpl
  movzx r13d, sil
  movzx r13d, dil
  movzx r13d, r8b
  movzx r13d, r9b
  movzx r13d, r10b
  movzx r13d, r11b
  movzx r13d, r12b
  movzx r13d, r13b
  movzx r13d, r14b
  movzx r13d, r15b
  movzx r13d, ax
  movzx r13d, cx
  movzx r13d, dx
  movzx r13d, bx
  movzx r13d, sp
  movzx r13d, bp
  movzx r13d, si
  movzx r13d, di
  movzx r13d, r8w
  movzx r13d, r9w
  movzx r13d, r10w
  movzx r13d, r11w
  movzx r13d, r12w
  movzx r13d, r13w
  movzx r13d, r14w
  movzx r13d, r15w
  movzx r13d, byte ptr [rbx]
  movzx r13d, byte ptr [r13+8]
  movzx r13d, byte ptr [r12+rax*2+3]
  movzx r13d, byte ptr [v8]
  movzx r13d, word ptr [rbx]
  movzx r13d, word ptr [r13+8]
  movzx r13d, word ptr [v16]
  movzx r14d, al
  movzx r14d, cl
  movzx r14d, dl
  movzx r14d, bl
  movzx r14d, spl
  movzx r14d, bpl
  movzx r14d, sil
  movzx r14d, dil
  movzx r14d, r8b
  movzx r14d, r9b
  movzx r14d, r10b
  movzx r14d, r11b
  movzx r14d, r12b
  movzx r14d, r13b
  movzx r14d, r14b
  movzx r14d, r15b
  movzx r14d, ax
  movzx r14d, cx
  movzx r14d, dx
  movzx r14d, bx
  movzx r14d, sp
  movzx r14d, bp
  movzx r14d, si
  movzx r14d, di
  movzx r14d, r8w
  movzx r14d, r9w
  movzx r14d, r10w
  movzx r14d, r11w
  movzx r14d, r12w
  movzx r14d, r13w
  movzx r14d, r14w
  movzx r14d, r15w
  movzx r14d, byte ptr [rbx]
  movzx r14d, byte ptr [r13+8]
  movzx r14d, byte ptr [r12+rax*2+3]
  movzx r14d, byte ptr [v8]
  movzx r14d, word ptr [rbx]
  movzx r14d, word ptr [r13+8]
  movzx r14d, word ptr [v16]
  movzx r15d, al
  movzx r15d, cl
  movzx r15d, dl
  movzx r15d, bl
  movzx r15d, spl
  movzx r15d, bpl
  movzx r15d, sil
  movzx r15d, dil
  movzx r15d, r8b
  movzx r15d, r9b
  movzx r15d, r10b
  movzx r15d, r11b
  movzx r15d, r12b
  movzx r15d, r13b
  movzx r15d, r14b
  movzx r15d, r15b
  movzx r15d, ax
  movzx r15d, cx
  movzx r15d, dx
  movzx r15d, bx
  movzx r15d, sp
  movzx r15d, bp
  movzx r15d, si
  movzx r15d, di
  movzx r15d, r8w
  movzx r15d, r9w
  movzx r15d, r10w
  movzx r15d, r11w
  movzx r15d, r12w
  movzx r15d, r13w
  movzx r15d, r14w
  movzx r15d, r15w
  movzx r15d, byte ptr [rbx]
  movzx r15d, byte ptr [r13+8]
  movzx r15d, byte ptr [r12+rax*2+3]
  movzx r15d, byte ptr [v8]
  movzx r15d, word ptr [rbx]
  movzx r15d, word ptr [r13+8]
  movzx r15d, word ptr [v16]
  movzx rax, al
  movzx rax, cl
  movzx rax, dl
  movzx rax, bl
  movzx rax, spl
  movzx rax, bpl
  movzx rax, sil
  movzx rax, dil
  movzx rax, r8b
  movzx rax, r9b
  movzx rax, r10b
  movzx rax, r11b
  movzx rax, r12b
  movzx rax, r13b
  movzx rax, r14b
  movzx rax, r15b
  movzx rax, ax
  movzx rax, cx
  movzx rax, dx
  movzx rax, bx
  movzx rax, sp
  movzx rax, bp
  movzx rax, si
  movzx rax, di
  movzx rax, r8w
  movzx rax, r9w
  movzx rax, r10w
  movzx rax, r11w
  movzx rax, r12w
  movzx rax, r13w
  movzx rax, r14w
  movzx rax, r15w
  movzx rax, byte ptr [rbx]
  movzx rax, byte ptr [r13+8]
  movzx rax, byte ptr [r12+rax*2+3]
  movzx rax, byte ptr [v8]
  movzx rax, word ptr [rbx]
  movzx rax, word ptr [r13+8]
  movzx rax, word ptr [v16]
  movzx rcx, al
  movzx rcx, cl
  movzx rcx, dl
  movzx rcx, bl
  movzx rcx, spl
  movzx rcx, bpl
  movzx rcx, sil
  movzx rcx, dil
  movzx rcx, r8b
  movzx rcx, r9b
  movzx rcx, r10b
  movzx rcx, r11b
  movzx rcx, r12b
  movzx rcx, r13b
  movzx rcx, r14b
  movzx rcx, r15b
  movzx rcx, ax
  movzx rcx, cx
  movzx rcx, dx
  movzx rcx, bx
  movzx rcx, sp
  movzx rcx, bp
  movzx rcx, si
  movzx rcx, di
  movzx rcx, r8w
  movzx rcx, r9w
  movzx rcx, r10w
  movzx rcx, r11w
  movzx rcx, r12w
  movzx rcx, r13w
  movzx rcx, r14w
  movzx rcx, r15w
  movzx rcx, byte ptr [rbx]
  movzx rcx, byte ptr [r13+8]
  movzx rcx, byte ptr [r12+rax*2+3]
  movzx rcx, byte ptr [v8]
  movzx rcx, word ptr [rbx]
  movzx rcx, word ptr [r13+8]
  movzx rcx, word ptr [v16]
  movzx rdx, al
  movzx rdx, cl
  movzx rdx, dl
  movzx rdx, bl
  movzx rdx, spl
  movzx rdx, bpl
  movzx rdx, sil
  movzx rdx, dil
  movzx rdx, r8b
  movzx rdx, r9b
  movzx rdx, r10b
  movzx rdx, r11b
  movzx rdx, r12b
  movzx rdx, r13b
  movzx rdx, r14b
  movzx rdx, r15b
  movzx rdx, ax
  movzx rdx, cx
  movzx rdx, dx
  movzx rdx, bx
  movzx rdx, sp
  movzx rdx, bp
  movzx rdx, si
  movzx rdx, di
  movzx rdx, r8w
  movzx rdx, r9w
  movzx rdx, r10w
  movzx rdx, r11w
  movzx rdx, r12w
  movzx rdx, r13w
  movzx rdx, r14w
  movzx rdx, r15w
  movzx rdx, byte ptr [rbx]
  movzx rdx, byte ptr [r13+8]
  movzx rdx, byte ptr [r12+rax*2+3]
  movzx rdx, byte ptr [v8]
  movzx rdx, word ptr [rbx]
  movzx rdx, word ptr [r13+8]
  movzx rdx, word ptr [v16]
  movzx rbx, al
  movzx rbx, cl
  movzx rbx, dl
  movzx rbx, bl
  movzx rbx, spl
  movzx rbx, bpl
  movzx rbx, sil
  movzx rbx, dil
  movzx rbx, r8b
  movzx rbx, r9b
  movzx rbx, r10b
  movzx rbx, r11b
  movzx rbx, r12b
  movzx rbx, r13b
  movzx rbx, r14b
  movzx rbx, r15b
  movzx rbx, ax
  movzx rbx, cx
  movzx rbx, dx
  movzx rbx, bx
  movzx rbx, sp
  movzx rbx, bp
  movzx rbx, si
  movzx rbx, di
  movzx rbx, r8w
  movzx rbx, r9w
  movzx rbx, r10w
  movzx rbx, r11w
  movzx rbx, r12w
  movzx rbx, r13w
  movzx rbx, r14w
  movzx rbx, r15w
  movzx rbx, byte ptr [rbx]
  movzx rbx, byte ptr [r13+8]
  movzx rbx, byte ptr [r12+rax*2+3]
  movzx rbx, byte ptr [v8]
  movzx rbx, word ptr [rbx]
  movzx rbx, word ptr [r13+8]
  movzx rbx, word ptr [v16]
  movzx rsp, al
  movzx rsp, cl
  movzx rsp, dl
  movzx rsp, bl
  movzx rsp, spl
  movzx rsp, bpl
  movzx rsp, sil
  movzx rsp, dil
  movzx rsp, r8b
  movzx rsp, r9b
  movzx rsp, r10b
  movzx rsp, r11b
  movzx rsp, r12b
  movzx rsp, r13b
  movzx rsp, r14b
  movzx rsp, r15b
  movzx rsp, ax
  movzx rsp, cx
  movzx rsp, dx
  movzx rsp, bx
  movzx rsp, sp
  movzx rsp, bp
  movzx rsp, si
  movzx rsp, di
  movzx rsp, r8w
  movzx rsp, r9w
  movzx rsp, r10w
  movzx rsp, r11w
  movzx rsp, r12w
  movzx rsp, r13w
  movzx rsp, r14w
  movzx rsp, r15w
  movzx rsp, byte ptr [rbx]
  movzx rsp, byte ptr [r13+8]
  movzx rsp, byte ptr [r12+rax*2+3]
  movzx rsp, byte ptr [v8]
  movzx rsp, word ptr [rbx]
  movzx rsp, word ptr [r13+8]
  movzx rsp, word ptr [v16]
  movzx rbp, al
  movzx rbp, cl
  movzx rbp, dl
  movzx rbp, bl
  movzx rbp, spl
  movzx rbp, bpl
  movzx rbp, sil
  movzx rbp, dil
  movzx rbp, r8b
  movzx rbp, r9b
  movzx rbp, r10b
  movzx rbp, r11b
  movzx rbp, r12b
  movzx rbp, r13b
  movzx rbp, r14b
  movzx rbp, r15b
  movzx rbp, ax
  movzx rbp, cx
  movzx rbp, dx
  movzx rbp, bx
  movzx rbp, sp
  movzx rbp, bp
  movzx rbp, si
  movzx rbp, di
  movzx rbp, r8w
  movzx rbp, r9w
  movzx rbp, r10w
  movzx rbp, r11w
  movzx rbp, r12w
  movzx rbp, r13w
  movzx rbp, r14w
  movzx rbp, r15w
  movzx rbp, byte ptr [rbx]
  movzx rbp, byte ptr [r13+8]
  movzx rbp, byte ptr [r12+rax*2+3]
  movzx rbp, byte ptr [v8]
  movzx rbp, word ptr [rbx]
  movzx rbp, word ptr [r13+8]
  movzx rbp, word ptr [v16]
  movzx rsi, al
  movzx rsi, cl
  movzx rsi, dl
  movzx rsi, bl
  movzx rsi, spl
  movzx rsi, bpl
  movzx rsi, sil
  movzx rsi, dil
  movzx rsi, r8b
  movzx rsi, r9b
  movzx rsi, r10b
  movzx rsi, r11b
  movzx rsi, r12b
  movzx rsi, r13b
  movzx rsi, r14b
  movzx rsi, r15b
  movzx rsi, ax
  movzx rsi, cx
  movzx rsi, dx
  movzx rsi, bx
  movzx rsi, sp
  movzx rsi, bp
  movzx rsi, si
  movzx rsi, di
  movzx rsi, r8w
  movzx rsi, r9w
  movzx rsi, r10w
  movzx rsi, r11w
  movzx rsi, r12w
  movzx rsi, r13w
  movzx rsi, r14w
  movzx rsi, r15w
  movzx rsi, byte ptr [rbx]
  movzx rsi, byte ptr [r13+8]
  movzx rsi, byte ptr [r12+rax*2+3]
  movzx rsi, byte ptr [v8]
  movzx rsi, word ptr [rbx]
  movzx rsi, word ptr [r13+8]
  movzx rsi, word ptr [v16]
  movzx rdi, al
  movzx rdi, cl
  movzx rdi, dl
  movzx rdi, bl
  movzx rdi, spl
  movzx rdi, bpl
  movzx rdi, sil
  movzx rdi, dil
  movzx rdi, r8b
  movzx rdi, r9b
  movzx rdi, r10b
  movzx rdi, r11b
  movzx rdi, r12b
  movzx rdi, r13b
  movzx rdi, r14b
  movzx rdi, r15b
  movzx rdi, ax
  movzx rdi, cx
  movzx rdi, dx
  movzx rdi, bx
  movzx rdi, sp
  movzx rdi, bp
  movzx rdi, si
  movzx rdi, di
  movzx rdi, r8w
  movzx rdi, r9w
  movzx rdi, r10w
  movzx rdi, r11w
  movzx rdi, r12w
  movzx rdi, r13w
  movzx rdi, r14w
  movzx rdi, r15w
  movzx rdi, byte ptr [rbx]
  movzx rdi, byte ptr [r13+8]
  movzx rdi, byte ptr [r12+rax*2+3]
  movzx rdi, byte ptr [v8]
  movzx rdi, word ptr [rbx]
  movzx rdi, word ptr [r13+8]
  movzx rdi, word ptr [v16]
  movzx r8, al
  movzx r8, cl
  movzx r8, dl
  movzx r8, bl
  movzx r8, spl
  movzx r8, bpl
  movzx r8, sil
  movzx r8, dil
  movzx r8, r8b
  movzx r8, r9b
  movzx r8, r10b
  movzx r8, r11b
  movzx r8, r12b
  movzx r8, r13b
  movzx r8, r14b
  movzx r8, r15b
  movzx r8, ax
  movzx r8, cx
  movzx r8, dx
  movzx r8, bx
  movzx r8, sp
  movzx r8, bp
  movzx r8, si
  movzx r8, di
  movzx r8, r8w
  movzx r8, r9w
  movzx r8, r10w
  movzx r8, r11w
  movzx r8, r12w
  movzx r8, r13w
  movzx r8, r14w
  movzx r8, r15w
  movzx r8, byte ptr [rbx]
  movzx r8, byte ptr [r13+8]
  movzx r8, byte ptr [r12+rax*2+3]
  movzx r8, byte ptr [v8]
  movzx r8, word ptr [rbx]
  movzx r8, word ptr [r13+8]
  movzx r8, word ptr [v16]
  movzx r9, al
  movzx r9, cl
  movzx r9, dl
  movzx r9, bl
  movzx r9, spl
  movzx r9, bpl
  movzx r9, sil
  movzx r9, dil
  movzx r9, r8b
  movzx r9, r9b
  movzx r9, r10b
  movzx r9, r11b
  movzx r9, r12b
  movzx r9, r13b
  movzx r9, r14b
  movzx r9, r15b
  movzx r9, ax
  movzx r9, cx
  movzx r9, dx
  movzx r9, bx
  movzx r9, sp
  movzx r9, bp
  movzx r9, si
  movzx r9, di
  movzx r9, r8w
  movzx r9, r9w
  movzx r9, r10w
  movzx r9, r11w
  movzx r9, r12w
  movzx r9, r13w
  movzx r9, r14w
  movzx r9, r15w
  movzx r9, byte ptr [rbx]
  movzx r9, byte ptr [r13+8]
  movzx r9, byte ptr [r12+rax*2+3]
  movzx r9, byte ptr [v8]
  movzx r9, word ptr [rbx]
  movzx r9, word ptr [r13+8]
  movzx r9, word ptr [v16]
  movzx r10, al
  movzx r10, cl
  movzx r10, dl
  movzx r10, bl
  movzx r10, spl
  movzx r10, bpl
  movzx r10, sil
  movzx r10, dil
  movzx r10, r8b
  movzx r10, r9b
  movzx r10, r10b
  movzx r10, r11b
  movzx r10, r12b
  movzx r10, r13b
  movzx r10, r14b
  movzx r10, r15b
  movzx r10, ax
  movzx r10, cx
  movzx r10, dx
  movzx r10, bx
  movzx r10, sp
  movzx r10, bp
  movzx r10, si
  movzx r10, di
  movzx r10, r8w
  movzx r10, r9w
  movzx r10, r10w
  movzx r10, r11w
  movzx r10, r12w
  movzx r10, r13w
  movzx r10, r14w
  movzx r10, r15w
  movzx r10, byte ptr [rbx]
  movzx r10, byte ptr [r13+8]
  movzx r10, byte ptr [r12+rax*2+3]
  movzx r10, byte ptr [v8]
  movzx r10, word ptr [rbx]
  movzx r10, word ptr [r13+8]
  movzx r10, word ptr [v16]
  movzx r11, al
  movzx r11, cl
  movzx r11, dl
  movzx r11, bl
  movzx r11, spl
  movzx r11, bpl
  movzx r11, sil
  movzx r11, dil
  movzx r11, r8b
  movzx r11, r9b
  movzx r11, r10b
  movzx r11, r11b
  movzx r11, r12b
  movzx r11, r13b
  movzx r11, r14b
  movzx r11, r15b
  movzx r11, ax
  movzx r11, cx
  movzx r11, dx
  movzx r11, bx
  movzx r11, sp
  movzx r11, bp
  movzx r11, si
  movzx r11, di
  movzx r11, r8w
  movzx r11, r9w
  movzx r11, r10w
  movzx r11, r11w
  movzx r11, r12w
  movzx r11, r13w
  movzx r11, r14w
  movzx r11, r15w
  movzx r11, byte ptr [rbx]
  movzx r11, byte ptr [r13+8]
  movzx r11, byte ptr [r12+rax*2+3]
  movzx r11, byte ptr [v8]
  movzx r11, word ptr [rbx]
  movzx r11, word ptr [r13+8]
  movzx r11, word ptr [v16]
  movzx r12, al
  movzx r12, cl
  movzx r12, dl
  movzx r12, bl
  movzx r12, spl
  movzx r12, bpl
  movzx r12, sil
  movzx r12, dil
  movzx r12, r8b
  movzx r12, r9b
  movzx r12, r10b
  movzx r12, r11b
  movzx r12, r12b
  movzx r12, r13b
  movzx r12, r14b
  movzx r12, r15b
  movzx r12, ax
  movzx r12, cx
  movzx r12, dx
  movzx r12, bx
  movzx r12, sp
  movzx r12, bp
  movzx r12, si
  movzx r12, di
  movzx r12, r8w
  movzx r12, r9w
  movzx r12, r10w
  movzx r12, r11w
  movzx r12, r12w
  movzx r12, r13w
  movzx r12, r14w
  movzx r12, r15w
  movzx r12, byte ptr [rbx]
  movzx r12, byte ptr [r13+8]
  movzx r12, byte ptr [r12+rax*2+3]
  movzx r12, byte ptr [v8]
  movzx r12, word ptr [rbx]
  movzx r12, word ptr [r13+8]
  movzx r12, word ptr [v16]
  movzx r13, al
  movzx r13, cl
  movzx r13, dl
  movzx r13, bl
  movzx r13, spl
  movzx r13, bpl
  movzx r13, sil
  movzx r13, dil
  movzx r13, r8b
  movzx r13, r9b
  movzx r13, r10b
  movzx r13, r11b
  movzx r13, r12b
  movzx r13, r13b
  movzx r13, r14b
  movzx r13, r15b
  movzx r13, ax
  movzx r13, cx
  movzx r13, dx
  movzx r13, bx
  movzx r13, sp
  movzx r13, bp
  movzx r13, si
  movzx r13, di
  movzx r13, r8w
  movzx r13, r9w
  movzx r13, r10w
  movzx r13, r11w
  movzx r13, r12w
  movzx r13, r13w
  movzx r13, r14w
  movzx r13, r15w
  movzx r13, byte ptr [rbx]
  movzx r13, byte ptr [r13+8]
  movzx r13, byte ptr [r12+rax*2+3]
  movzx r13, byte ptr [v8]
  movzx r13, word ptr [rbx]
  movzx r13, word ptr [r13+8]
  movzx r13, word ptr [v16]
  movzx r14, al
  movzx r14, cl
  movzx r14, dl
  movzx r14, bl
  movzx r14, spl
  movzx r14, bpl
  movzx r14, sil
  movzx r14, dil
  movzx r14, r8b
  movzx r14, r9b
  movzx r14, r10b
  movzx r14, r11b
  movzx r14, r12b
  movzx r14, r13b
  movzx r14, r14b
  movzx r14, r15b
  movzx r14, ax
  movzx r14, cx
  movzx r14, dx
  movzx r14, bx
  movzx r14, sp
  movzx r14, bp
  movzx r14, si
  movzx r14, di
  movzx r14, r8w
  movzx r14, r9w
  movzx r14, r10w
  movzx r14, r11w
  movzx r14, r12w
  movzx r14, r13w
  movzx r14, r14w
  movzx r14, r15w
  movzx r14, byte ptr [rbx]
  movzx r14, byte ptr [r13+8]
  movzx r14, byte ptr [r12+rax*2+3]
  movzx r14, byte ptr [v8]
  movzx r14, word ptr [rbx]
  movzx r14, word ptr [r13+8]
  movzx r14, word ptr [v16]
  movzx r15, al
  movzx r15, cl
  movzx r15, dl
  movzx r15, bl
  movzx r15, spl
  movzx r15, bpl
  movzx r15, sil
  movzx r15, dil
  movzx r15, r8b
  movzx r15, r9b
  movzx r15, r10b
  movzx r15, r11b
  movzx r15, r12b
  movzx r15, r13b
  movzx r15, r14b
  movzx r15, r15b
  movzx r15, ax
  movzx r15, cx
  movzx r15, dx
  movzx r15, bx
  movzx r15, sp
  movzx r15, bp
  movzx r15, si
  movzx r15, di
  movzx r15, r8w
  movzx r15, r9w
  movzx r15, r10w
  movzx r15, r11w
  movzx r15, r12w
  movzx r15, r13w
  movzx r15, r14w
  movzx r15, r15w
  movzx r15, byte ptr [rbx]
  movzx r15, byte ptr [r13+8]
  movzx r15, byte ptr [r12+rax*2+3]
  movzx r15, byte ptr [v8]
  movzx r15, word ptr [rbx]
  movzx r15, word ptr [r13+8]
  movzx r15, word ptr [v16]
  movsx ax, al
  movsx ax, cl
  movsx ax, ah
  movsx ax, sil
  movsx ax, r9b
  movsx ax, byte ptr [rbx]
  movsx cx, al
  movsx cx, cl
  movsx cx, ah
  movsx cx, sil
  movsx cx, r9b
  movsx cx, byte ptr [rbx]
  movsx dx, al
  movsx dx, cl
  movsx dx, ah
  movsx dx, sil
  movsx dx, r9b
  movsx dx, byte ptr [rbx]
  movsx bx, al
  movsx bx, cl
  movsx bx, ah
  movsx bx, sil
  movsx bx, r9b
  movsx bx, byte ptr [rbx]
  movsx sp, al
  movsx sp, cl
  movsx sp, ah
  movsx sp, sil
  movsx sp, r9b
  movsx sp, byte ptr [rbx]
  movsx bp, al
  movsx bp, cl
  movsx bp, ah
  movsx bp, sil
  movsx bp, r9b
  movsx bp, byte ptr [rbx]
  movsx si, al
  movsx si, cl
  movsx si, ah
  movsx si, sil
  movsx si, r9b
  movsx si, byte ptr [rbx]
  movsx di, al
  movsx di, cl
  movsx di, ah
  movsx di, sil
  movsx di, r9b
  movsx di, byte ptr [rbx]
  movsx r8w, al
  movsx r8w, cl
  movsx r8w, sil
  movsx r8w, r9b
  movsx r8w, byte ptr [rbx]
  movsx r9w, al
  movsx r9w, cl
  movsx r9w, sil
  movsx r9w, r9b
  movsx r9w, byte ptr [rbx]
  movsx r10w, al
  movsx r10w, cl
  movsx r10w, sil
  movsx r10w, r9b
  movsx r10w, byte ptr [rbx]
  movsx r11w, al
  movsx r11w, cl
  movsx r11w, sil
  movsx r11w, r9b
  movsx r11w, byte ptr [rbx]
  movsx r12w, al
  movsx r12w, cl
  movsx r12w, sil
  movsx r12w, r9b
  movsx r12w, byte ptr [rbx]
  movsx r13w, al
  movsx r13w, cl
  movsx r13w, sil
  movsx r13w, r9b
  movsx r13w, byte ptr [rbx]
  movsx r14w, al
  movsx r14w, cl
  movsx r14w, sil
  movsx r14w, r9b
  movsx r14w, byte ptr [rbx]
  movsx r15w, al
  movsx r15w, cl
  movsx r15w, sil
  movsx r15w, r9b
  movsx r15w, byte ptr [rbx]
  movsx eax, al
  movsx eax, cl
  movsx eax, dl
  movsx eax, bl
  movsx eax, ah
  movsx eax, ch
  movsx eax, dh
  movsx eax, bh
  movsx eax, spl
  movsx eax, bpl
  movsx eax, sil
  movsx eax, dil
  movsx eax, r8b
  movsx eax, r9b
  movsx eax, r10b
  movsx eax, r11b
  movsx eax, r12b
  movsx eax, r13b
  movsx eax, r14b
  movsx eax, r15b
  movsx eax, ax
  movsx eax, cx
  movsx eax, dx
  movsx eax, bx
  movsx eax, sp
  movsx eax, bp
  movsx eax, si
  movsx eax, di
  movsx eax, r8w
  movsx eax, r9w
  movsx eax, r10w
  movsx eax, r11w
  movsx eax, r12w
  movsx eax, r13w
  movsx eax, r14w
  movsx eax, r15w
  movsx eax, byte ptr [rbx]
  movsx eax, byte ptr [r13+8]
  movsx eax, byte ptr [r12+rax*2+3]
  movsx eax, byte ptr [v8]
  movsx eax, word ptr [rbx]
  movsx eax, word ptr [r13+8]
  movsx eax, word ptr [v16]
  movsx ecx, al
  movsx ecx, cl
  movsx ecx, dl
  movsx ecx, bl
  movsx ecx, ah
  movsx ecx, ch
  movsx ecx, dh
  movsx ecx, bh
  movsx ecx, spl
  movsx ecx, bpl
  movsx ecx, sil
  movsx ecx, dil
  movsx ecx, r8b
  movsx ecx, r9b
  movsx ecx, r10b
  movsx ecx, r11b
  movsx ecx, r12b
  movsx ecx, r13b
  movsx ecx, r14b
  movsx ecx, r15b
  movsx ecx, ax
  movsx ecx, cx
  movsx ecx, dx
  movsx ecx, bx
  movsx ecx, sp
  movsx ecx, bp
  movsx ecx, si
  movsx ecx, di
  movsx ecx, r8w
  movsx ecx, r9w
  movsx ecx, r10w
  movsx ecx, r11w
  movsx ecx, r12w
  movsx ecx, r13w
  movsx ecx, r14w
  movsx ecx, r15w
  movsx ecx, byte ptr [rbx]
  movsx ecx, byte ptr [r13+8]
  movsx ecx, byte ptr [r12+rax*2+3]
  movsx ecx, byte ptr [v8]
  movsx ecx, word ptr [rbx]
  movsx ecx, word ptr [r13+8]
  movsx ecx, word ptr [v16]
  movsx edx, al
  movsx edx, cl
  movsx edx, dl
  movsx edx, bl
  movsx edx, ah
  movsx edx, ch
  movsx edx, dh
  movsx edx, bh
  movsx edx, spl
  movsx edx, bpl
  movsx edx, sil
  movsx edx, dil
  movsx edx, r8b
  movsx edx, r9b
  movsx edx, r10b
  movsx edx, r11b
  movsx edx, r12b
  movsx edx, r13b
  movsx edx, r14b
  movsx edx, r15b
  movsx edx, ax
  movsx edx, cx
  movsx edx, dx
  movsx edx, bx
  movsx edx, sp
  movsx edx, bp
  movsx edx, si
  movsx edx, di
  movsx edx, r8w
  movsx edx, r9w
  movsx edx, r10w
  movsx edx, r11w
  movsx edx, r12w
  movsx edx, r13w
  movsx edx, r14w
  movsx edx, r15w
  movsx edx, byte ptr [rbx]
  movsx edx, byte ptr [r13+8]
  movsx edx, byte ptr [r12+rax*2+3]
  movsx edx, byte ptr [v8]
  movsx edx, word ptr [rbx]
  movsx edx, word ptr [r13+8]
  movsx edx, word ptr [v16]
  movsx ebx, al
  movsx ebx, cl
  movsx ebx, dl
  movsx ebx, bl
  movsx ebx, ah
  movsx ebx, ch
  movsx ebx, dh
  movsx ebx, bh
  movsx ebx, spl
  movsx ebx, bpl
  movsx ebx, sil
  movsx ebx, dil
  movsx ebx, r8b
  movsx ebx, r9b
  movsx ebx, r10b
  movsx ebx, r11b
  movsx ebx, r12b
  movsx ebx, r13b
  movsx ebx, r14b
  movsx ebx, r15b
  movsx ebx, ax
  movsx ebx, cx
  movsx ebx, dx
  movsx ebx, bx
  movsx ebx, sp
  movsx ebx, bp
  movsx ebx, si
  movsx ebx, di
  movsx ebx, r8w
  movsx ebx, r9w
  movsx ebx, r10w
  movsx ebx, r11w
  movsx ebx, r12w
  movsx ebx, r13w
  movsx ebx, r14w
  movsx ebx, r15w
  movsx ebx, byte ptr [rbx]
  movsx ebx, byte ptr [r13+8]
  movsx ebx, byte ptr [r12+rax*2+3]
  movsx ebx, byte ptr [v8]
  movsx ebx, word ptr [rbx]
  movsx ebx, word ptr [r13+8]
  movsx ebx, word ptr [v16]
  movsx esp, al
  movsx esp, cl
  movsx esp, dl
  movsx esp, bl
  movsx esp, ah
  movsx esp, ch
  movsx esp, dh
  movsx esp, bh
  movsx esp, spl
  movsx esp, bpl
  movsx esp, sil
  movsx esp, dil
  movsx esp, r8b
  movsx esp, r9b
  movsx esp, r10b
  movsx esp, r11b
  movsx esp, r12b
  movsx esp, r13b
  movsx esp, r14b
  movsx esp, r15b
  movsx esp, ax
  movsx esp, cx
  movsx esp, dx
  movsx esp, bx
  movsx esp, sp
  movsx esp, bp
  movsx esp, si
  movsx esp, di
  movsx esp, r8w
  movsx esp, r9w
  movsx esp, r10w
  movsx esp, r11w
  movsx esp, r12w
  movsx esp, r13w
  movsx esp, r14w
  movsx esp, r15w
  movsx esp, byte ptr [rbx]
  movsx esp, byte ptr [r13+8]
  movsx esp, byte ptr [r12+rax*2+3]
  movsx esp, byte ptr [v8]
  movsx esp, word ptr [rbx]
  movsx esp, word ptr [r13+8]
  movsx esp, word ptr [v16]
  movsx ebp, al
  movsx ebp, cl
  movsx ebp, dl
  movsx ebp, bl
  movsx ebp, ah
  movsx ebp, ch
  movsx ebp, dh
  movsx ebp, bh
  movsx ebp, spl
  movsx ebp, bpl
  movsx ebp, sil
  movsx ebp, dil
  movsx ebp, r8b
  movsx ebp, r9b
  movsx ebp, r10b
  movsx ebp, r11b
  movsx ebp, r12b
  movsx ebp, r13b
  movsx ebp, r14b
  movsx ebp, r15b
  movsx ebp, ax
  movsx ebp, cx
  movsx ebp, dx
  movsx ebp, bx
  movsx ebp, sp
  movsx ebp, bp
  movsx ebp, si
  movsx ebp, di
  movsx ebp, r8w
  movsx ebp, r9w
  movsx ebp, r10w
  movsx ebp, r11w
  movsx ebp, r12w
  movsx ebp, r13w
  movsx ebp, r14w
  movsx ebp, r15w
  movsx ebp, byte ptr [rbx]
  movsx ebp, byte ptr [r13+8]
  movsx ebp, byte ptr [r12+rax*2+3]
  movsx ebp, byte ptr [v8]
  movsx ebp, word ptr [rbx]
  movsx ebp, word ptr [r13+8]
  movsx ebp, word ptr [v16]
  movsx esi, al
  movsx esi, cl
  movsx esi, dl
  movsx esi, bl
  movsx esi, ah
  movsx esi, ch
  movsx esi, dh
  movsx esi, bh
  movsx esi, spl
  movsx esi, bpl
  movsx esi, sil
  movsx esi, dil
  movsx esi, r8b
  movsx esi, r9b
  movsx esi, r10b
  movsx esi, r11b
  movsx esi, r12b
  movsx esi, r13b
  movsx esi, r14b
  movsx esi, r15b
  movsx esi, ax
  movsx esi, cx
  movsx esi, dx
  movsx esi, bx
  movsx esi, sp
  movsx esi, bp
  movsx esi, si
  movsx esi, di
  movsx esi, r8w
  movsx esi, r9w
  movsx esi, r10w
  movsx esi, r11w
  movsx esi, r12w
  movsx esi, r13w
  movsx esi, r14w
  movsx esi, r15w
  movsx esi, byte ptr [rbx]
  movsx esi, byte ptr [r13+8]
  movsx esi, byte ptr [r12+rax*2+3]
  movsx esi, byte ptr [v8]
  movsx esi, word ptr [rbx]
  movsx esi, word ptr [r13+8]
  movsx esi, word ptr [v16]
  movsx edi, al
  movsx edi, cl
  movsx edi, dl
  movsx edi, bl
  movsx edi, ah
  movsx edi, ch
  movsx edi, dh
  movsx edi, bh
  movsx edi, spl
  movsx edi, bpl
  movsx edi, sil
  movsx edi, dil
  movsx edi, r8b
  movsx edi, r9b
  movsx edi, r10b
  movsx edi, r11b
  movsx edi, r12b
  movsx edi, r13b
  movsx edi, r14b
  movsx edi, r15b
  movsx edi, ax
  movsx edi, cx
  movsx edi, dx
  movsx edi, bx
  movsx edi, sp
  movsx edi, bp
  movsx edi, si
  movsx edi, di
  movsx edi, r8w
  movsx edi, r9w
  movsx edi, r10w
  movsx edi, r11w
  movsx edi, r12w
  movsx edi, r13w
  movsx edi, r14w
  movsx edi, r15w
  movsx edi, byte ptr [rbx]
  movsx edi, byte ptr [r13+8]
  movsx edi, byte ptr [r12+rax*2+3]
  movsx edi, byte ptr [v8]
  movsx edi, word ptr [rbx]
  movsx edi, word ptr [r13+8]
  movsx edi, word ptr [v16]
  movsx r8d, al
  movsx r8d, cl
  movsx r8d, dl
  movsx r8d, bl
  movsx r8d, spl
  movsx r8d, bpl
  movsx r8d, sil
  movsx r8d, dil
  movsx r8d, r8b
  movsx r8d, r9b
  movsx r8d, r10b
  movsx r8d, r11b
  movsx r8d, r12b
  movsx r8d, r13b
  movsx r8d, r14b
  movsx r8d, r15b
  movsx r8d, ax
  movsx r8d, cx
  movsx r8d, dx
  movsx r8d, bx
  movsx r8d, sp
  movsx r8d, bp
  movsx r8d, si
  movsx r8d, di
  movsx r8d, r8w
  movsx r8d, r9w
  movsx r8d, r10w
  movsx r8d, r11w
  movsx r8d, r12w
  movsx r8d, r13w
  movsx r8d, r14w
  movsx r8d, r15w
  movsx r8d, byte ptr [rbx]
  movsx r8d, byte ptr [r13+8]
  movsx r8d, byte ptr [r12+rax*2+3]
  movsx r8d, byte ptr [v8]
  movsx r8d, word ptr [rbx]
  movsx r8d, word ptr [r13+8]
  movsx r8d, word ptr [v16]
  movsx r9d, al
  movsx r9d, cl
  movsx r9d, dl
  movsx r9d, bl
  movsx r9d, spl
  movsx r9d, bpl
  movsx r9d, sil
  movsx r9d, dil
  movsx r9d, r8b
  movsx r9d, r9b
  movsx r9d, r10b
  movsx r9d, r11b
  movsx r9d, r12b
  movsx r9d, r13b
  movsx r9d, r14b
  movsx r9d, r15b
  movsx r9d, ax
  movsx r9d, cx
  movsx r9d, dx
  movsx r9d, bx
  movsx r9d, sp
  movsx r9d, bp
  movsx r9d, si
  movsx r9d, di
  movsx r9d, r8w
  movsx r9d, r9w
  movsx r9d, r10w
  movsx r9d, r11w
  movsx r9d, r12w
  movsx r9d, r13w
  movsx r9d, r14w
  movsx r9d, r15w
  movsx r9d, byte ptr [rbx]
  movsx r9d, byte ptr [r13+8]
  movsx r9d, byte ptr [r12+rax*2+3]
  movsx r9d, byte ptr [v8]
  movsx r9d, word ptr [rbx]
  movsx r9d, word ptr [r13+8]
  movsx r9d, word ptr [v16]
  movsx r10d, al
  movsx r10d, cl
  movsx r10d, dl
  movsx r10d, bl
  movsx r10d, spl
  movsx r10d, bpl
  movsx r10d, sil
  movsx r10d, dil
  movsx r10d, r8b
  movsx r10d, r9b
  movsx r10d, r10b
  movsx r10d, r11b
  movsx r10d, r12b
  movsx r10d, r13b
  movsx r10d, r14b
  movsx r10d, r15b
  movsx r10d, ax
  movsx r10d, cx
  movsx r10d, dx
  movsx r10d, bx
  movsx r10d, sp
  movsx r10d, bp
  movsx r10d, si
  movsx r10d, di
  movsx r10d, r8w
  movsx r10d, r9w
  movsx r10d, r10w
  movsx r10d, r11w
  movsx r10d, r12w
  movsx r10d, r13w
  movsx r10d, r14w
  movsx r10d, r15w
  movsx r10d, byte ptr [rbx]
  movsx r10d, byte ptr [r13+8]
  movsx r10d, byte ptr [r12+rax*2+3]
  movsx r10d, byte ptr [v8]
  movsx r10d, word ptr [rbx]
  movsx r10d, word ptr [r13+8]
  movsx r10d, word ptr [v16]
  movsx r11d, al
  movsx r11d, cl
  movsx r11d, dl
  movsx r11d, bl
  movsx r11d, spl
  movsx r11d, bpl
  movsx r11d, sil
  movsx r11d, dil
  movsx r11d, r8b
  movsx r11d, r9b
  movsx r11d, r10b
  movsx r11d, r11b
  movsx r11d, r12b
  movsx r11d, r13b
  movsx r11d, r14b
  movsx r11d, r15b
  movsx r11d, ax
  movsx r11d, cx
  movsx r11d, dx
  movsx r11d, bx
  movsx r11d, sp
  movsx r11d, bp
  movsx r11d, si
  movsx r11d, di
  movsx r11d, r8w
  movsx r11d, r9w
  movsx r11d, r10w
  movsx r11d, r11w
  movsx r11d, r12w
  movsx r11d, r13w
  movsx r11d, r14w
  movsx r11d, r15w
  movsx r11d, byte ptr [rbx]
  movsx r11d, byte ptr [r13+8]
  movsx r11d, byte ptr [r12+rax*2+3]
  movsx r11d, byte ptr [v8]
  movsx r11d, word ptr [rbx]
  movsx r11d, word ptr [r13+8]
  movsx r11d, word ptr [v16]
  movsx r12d, al
  movsx r12d, cl
  movsx r12d, dl
  movsx r12d, bl
  movsx r12d, spl
  movsx r12d, bpl
  movsx r12d, sil
  movsx r12d, dil
  movsx r12d, r8b
  movsx r12d, r9b
  movsx r12d, r10b
  movsx r12d, r11b
  movsx r12d, r12b
  movsx r12d, r13b
  movsx r12d, r14b
  movsx r12d, r15b
  movsx r12d, ax
  movsx r12d, cx
  movsx r12d, dx
  movsx r12d, bx
  movsx r12d, sp
  movsx r12d, bp
  movsx r12d, si
  movsx r12d, di
  movsx r12d, r8w
  movsx r12d, r9w
  movsx r12d, r10w
  movsx r12d, r11w
  movsx r12d, r12w
  movsx r12d, r13w
  movsx r12d, r14w
  movsx r12d, r15w
  movsx r12d, byte ptr [rbx]
  movsx r12d, byte ptr [r13+8]
  movsx r12d, byte ptr [r12+rax*2+3]
  movsx r12d, byte ptr [v8]
  movsx r12d, word ptr [rbx]
  movsx r12d, word ptr [r13+8]
  movsx r12d, word ptr [v16]
  movsx r13d, al
  movsx r13d, cl
  movsx r13d, dl
  movsx r13d, bl
  movsx r13d, spl
  movsx r13d, bpl
  movsx r13d, sil
  movsx r13d, dil
  movsx r13d, r8b
  movsx r13d, r9b
  movsx r13d, r10b
  movsx r13d, r11b
  movsx r13d, r12b
  movsx r13d, r13b
  movsx r13d, r14b
  movsx r13d, r15b
  movsx r13d, ax
  movsx r13d, cx
  movsx r13d, dx
  movsx r13d, bx
  movsx r13d, sp
  movsx r13d, bp
  movsx r13d, si
  movsx r13d, di
  movsx r13d, r8w
  movsx r13d, r9w
  movsx r13d, r10w
  movsx r13d, r11w
  movsx r13d, r12w
  movsx r13d, r13w
  movsx r13d, r14w
  movsx r13d, r15w
  movsx r13d, byte ptr [rbx]
  movsx r13d, byte ptr [r13+8]
  movsx r13d, byte ptr [r12+rax*2+3]
  movsx r13d, byte ptr [v8]
  movsx r13d, word ptr [rbx]
  movsx r13d, word ptr [r13+8]
  movsx r13d, word ptr [v16]
  movsx r14d, al
  movsx r14d, cl
  movsx r14d, dl
  movsx r14d, bl
  movsx r14d, spl
  movsx r14d, bpl
  movsx r14d, sil
  movsx r14d, dil
  movsx r14d, r8b
  movsx r14d, r9b
  movsx r14d, r10b
  movsx r14d, r11b
  movsx r14d, r12b
  movsx r14d, r13b
  movsx r14d, r14b
  movsx r14d, r15b
  movsx r14d, ax
  movsx r14d, cx
  movsx r14d, dx
  movsx r14d, bx
  movsx r14d, sp
  movsx r14d, bp
  movsx r14d, si
  movsx r14d, di
  movsx r14d, r8w
  movsx r14d, r9w
  movsx r14d, r10w
  movsx r14d, r11w
  movsx r14d, r12w
  movsx r14d, r13w
  movsx r14d, r14w
  movsx r14d, r15w
  movsx r14d, byte ptr [rbx]
  movsx r14d, byte ptr [r13+8]
  movsx r14d, byte ptr [r12+rax*2+3]
  movsx r14d, byte ptr [v8]
  movsx r14d, word ptr [rbx]
  movsx r14d, word ptr [r13+8]
  movsx r14d, word ptr [v16]
  movsx r15d, al
  movsx r15d, cl
  movsx r15d, dl
  movsx r15d, bl
  movsx r15d, spl
  movsx r15d, bpl
  movsx r15d, sil
  movsx r15d, dil
  movsx r15d, r8b
  movsx r15d, r9b
  movsx r15d, r10b
  movsx r15d, r11b
  movsx r15d, r12b
  movsx r15d, r13b
  movsx r15d, r14b
  movsx r15d, r15b
  movsx r15d, ax
  movsx r15d, cx
  movsx r15d, dx
  movsx r15d, bx
  movsx r15d, sp
  movsx r15d, bp
  movsx r15d, si
  movsx r15d, di
  movsx r15d, r8w
  movsx r15d, r9w
  movsx r15d, r10w
  movsx r15d, r11w
  movsx r15d, r12w
  movsx r15d, r13w
  movsx r15d, r14w
  movsx r15d, r15w
  movsx r15d, byte ptr [rbx]
  movsx r15d, byte ptr [r13+8]
  movsx r15d, byte ptr [r12+rax*2+3]
  movsx r15d, byte ptr [v8]
  movsx r15d, word ptr [rbx]
  movsx r15d, word ptr [r13+8]
  movsx r15d, word ptr [v16]
  movsx rax, al
  movsx rax, cl
  movsx rax, dl
  movsx rax, bl
  movsx rax, spl
  movsx rax, bpl
  movsx rax, sil
  movsx rax, dil
  movsx rax, r8b
  movsx rax, r9b
  movsx rax, r10b
  movsx rax, r11b
  movsx rax, r12b
  movsx rax, r13b
  movsx rax, r14b
  movsx rax, r15b
  movsx rax, ax
  movsx rax, cx
  movsx rax, dx
  movsx rax, bx
  movsx rax, sp
  movsx rax, bp
  movsx rax, si
  movsx rax, di
  movsx rax, r8w
  movsx rax, r9w
  movsx rax, r10w
  movsx rax, r11w
  movsx rax, r12w
  movsx rax, r13w
  movsx rax, r14w
  movsx rax, r15w
  movsx rax, byte ptr [rbx]
  movsx rax, byte ptr [r13+8]
  movsx rax, byte ptr [r12+rax*2+3]
  movsx rax, byte ptr [v8]
  movsx rax, word ptr [rbx]
  movsx rax, word ptr [r13+8]
  movsx rax, word ptr [v16]
  movsx rcx, al
  movsx rcx, cl
  movsx rcx, dl
  movsx rcx, bl
  movsx rcx, spl
  movsx rcx, bpl
  movsx rcx, sil
  movsx rcx, dil
  movsx rcx, r8b
  movsx rcx, r9b
  movsx rcx, r10b
  movsx rcx, r11b
  movsx rcx, r12b
  movsx rcx, r13b
  movsx rcx, r14b
  movsx rcx, r15b
  movsx rcx, ax
  movsx rcx, cx
  movsx rcx, dx
  movsx rcx, bx
  movsx rcx, sp
  movsx rcx, bp
  movsx rcx, si
  movsx rcx, di
  movsx rcx, r8w
  movsx rcx, r9w
  movsx rcx, r10w
  movsx rcx, r11w
  movsx rcx, r12w
  movsx rcx, r13w
  movsx rcx, r14w
  movsx rcx, r15w
  movsx rcx, byte ptr [rbx]
  movsx rcx, byte ptr [r13+8]
  movsx rcx, byte ptr [r12+rax*2+3]
  movsx rcx, byte ptr [v8]
  movsx rcx, word ptr [rbx]
  movsx rcx, word ptr [r13+8]
  movsx rcx, word ptr [v16]
  movsx rdx, al
  movsx rdx, cl
  movsx rdx, dl
  movsx rdx, bl
  movsx rdx, spl
  movsx rdx, bpl
  movsx rdx, sil
  movsx rdx, dil
  movsx rdx, r8b
  movsx rdx, r9b
  movsx rdx, r10b
  movsx rdx, r11b
  movsx rdx, r12b
  movsx rdx, r13b
  movsx rdx, r14b
  movsx rdx, r15b
  movsx rdx, ax
  movsx rdx, cx
  movsx rdx, dx
  movsx rdx, bx
  movsx rdx, sp
  movsx rdx, bp
  movsx rdx, si
  movsx rdx, di
  movsx rdx, r8w
  movsx rdx, r9w
  movsx rdx, r10w
  movsx rdx, r11w
  movsx rdx, r12w
  movsx rdx, r13w
  movsx rdx, r14w
  movsx rdx, r15w
  movsx rdx, byte ptr [rbx]
  movsx rdx, byte ptr [r13+8]
  movsx rdx, byte ptr [r12+rax*2+3]
  movsx rdx, byte ptr [v8]
  movsx rdx, word ptr [rbx]
  movsx rdx, word ptr [r13+8]
  movsx rdx, word ptr [v16]
  movsx rbx, al
  movsx rbx, cl
  movsx rbx, dl
  movsx rbx, bl
  movsx rbx, spl
  movsx rbx, bpl
  movsx rbx, sil
  movsx rbx, dil
  movsx rbx, r8b
  movsx rbx, r9b
  movsx rbx, r10b
  movsx rbx, r11b
  movsx rbx, r12b
  movsx rbx, r13b
  movsx rbx, r14b
  movsx rbx, r15b
  movsx rbx, ax
  movsx rbx, cx
  movsx rbx, dx
  movsx rbx, bx
  movsx rbx, sp
  movsx rbx, bp
  movsx rbx, si
  movsx rbx, di
  movsx rbx, r8w
  movsx rbx, r9w
  movsx rbx, r10w
  movsx rbx, r11w
  movsx rbx, r12w
  movsx rbx, r13w
  movsx rbx, r14w
  movsx rbx, r15w
  movsx rbx, byte ptr [rbx]
  movsx rbx, byte ptr [r13+8]
  movsx rbx, byte ptr [r12+rax*2+3]
  movsx rbx, byte ptr [v8]
  movsx rbx, word ptr [rbx]
  movsx rbx, word ptr [r13+8]
  movsx rbx, word ptr [v16]
  movsx rsp, al
  movsx rsp, cl
  movsx rsp, dl
  movsx rsp, bl
  movsx rsp, spl
  movsx rsp, bpl
  movsx rsp, sil
  movsx rsp, dil
  movsx rsp, r8b
  movsx rsp, r9b
  movsx rsp, r10b
  movsx rsp, r11b
  movsx rsp, r12b
  movsx rsp, r13b
  movsx rsp, r14b
  movsx rsp, r15b
  movsx rsp, ax
  movsx rsp, cx
  movsx rsp, dx
  movsx rsp, bx
  movsx rsp, sp
  movsx rsp, bp
  movsx rsp, si
  movsx rsp, di
  movsx rsp, r8w
  movsx rsp, r9w
  movsx rsp, r10w
  movsx rsp, r11w
  movsx rsp, r12w
  movsx rsp, r13w
  movsx rsp, r14w
  movsx rsp, r15w
  movsx rsp, byte ptr [rbx]
  movsx rsp, byte ptr [r13+8]
  movsx rsp, byte ptr [r12+rax*2+3]
  movsx rsp, byte ptr [v8]
  movsx rsp, word ptr [rbx]
  movsx rsp, word ptr [r13+8]
  movsx rsp, word ptr [v16]
  movsx rbp, al
  movsx rbp, cl
  movsx rbp, dl
  movsx rbp, bl
  movsx rbp, spl
  movsx rbp, bpl
  movsx rbp, sil
  movsx rbp, dil
  movsx rbp, r8b
  movsx rbp, r9b
  movsx rbp, r10b
  movsx rbp, r11b
  movsx rbp, r12b
  movsx rbp, r13b
  movsx rbp, r14b
  movsx rbp, r15b
  movsx rbp, ax
  movsx rbp, cx
  movsx rbp, dx
  movsx rbp, bx
  movsx rbp, sp
  movsx rbp, bp
  movsx rbp, si
  movsx rbp, di
  movsx rbp, r8w
  movsx rbp, r9w
  movsx rbp, r10w
  movsx rbp, r11w
  movsx rbp, r12w
  movsx rbp, r13w
  movsx rbp, r14w
  movsx rbp, r15w
  movsx rbp, byte ptr [rbx]
  movsx rbp, byte ptr [r13+8]
  movsx rbp, byte ptr [r12+rax*2+3]
  movsx rbp, byte ptr [v8]
  movsx rbp, word ptr [rbx]
  movsx rbp, word ptr [r13+8]
  movsx rbp, word ptr [v16]
  movsx rsi, al
  movsx rsi, cl
  movsx rsi, dl
  movsx rsi, bl
  movsx rsi, spl
  movsx rsi, bpl
  movsx rsi, sil
  movsx rsi, dil
  movsx rsi, r8b
  movsx rsi, r9b
  movsx rsi, r10b
  movsx rsi, r11b
  movsx rsi, r12b
  movsx rsi, r13b
  movsx rsi, r14b
  movsx rsi, r15b
  movsx rsi, ax
  movsx rsi, cx
  movsx rsi, dx
  movsx rsi, bx
  movsx rsi, sp
  movsx rsi, bp
  movsx rsi, si
  movsx rsi, di
  movsx rsi, r8w
  movsx rsi, r9w
  movsx rsi, r10w
  movsx rsi, r11w
  movsx rsi, r12w
  movsx rsi, r13w
  movsx rsi, r14w
  movsx rsi, r15w
  movsx rsi, byte ptr [rbx]
  movsx rsi, byte ptr [r13+8]
  movsx rsi, byte ptr [r12+rax*2+3]
  movsx rsi, byte ptr [v8]
  movsx rsi, word ptr [rbx]
  movsx rsi, word ptr [r13+8]
  movsx rsi, word ptr [v16]
  movsx rdi, al
  movsx rdi, cl
  movsx rdi, dl
  movsx rdi, bl
  movsx rdi, spl
  movsx rdi, bpl
  movsx rdi, sil
  movsx rdi, dil
  movsx rdi, r8b
  movsx rdi, r9b
  movsx rdi, r10b
  movsx rdi, r11b
  movsx rdi, r12b
  movsx rdi, r13b
  movsx rdi, r14b
  movsx rdi, r15b
  movsx rdi, ax
  movsx rdi, cx
  movsx rdi, dx
  movsx rdi, bx
  movsx rdi, sp
  movsx rdi, bp
  movsx rdi, si
  movsx rdi, di
  movsx rdi, r8w
  movsx rdi, r9w
  movsx rdi, r10w
  movsx rdi, r11w
  movsx rdi, r12w
  movsx rdi, r13w
  movsx rdi, r14w
  movsx rdi, r15w
  movsx rdi, byte ptr [rbx]
  movsx rdi, byte ptr [r13+8]
  movsx rdi, byte ptr [r12+rax*2+3]
  movsx rdi, byte ptr [v8]
  movsx rdi, word ptr [rbx]
  movsx rdi, word ptr [r13+8]
  movsx rdi, word ptr [v16]
  movsx r8, al
  movsx r8, cl
  movsx r8, dl
  movsx r8, bl
  movsx r8, spl
  movsx r8, bpl
  movsx r8, sil
  movsx r8, dil
  movsx r8, r8b
  movsx r8, r9b
  movsx r8, r10b
  movsx r8, r11b
  movsx r8, r12b
  movsx r8, r13b
  movsx r8, r14b
  movsx r8, r15b
  movsx r8, ax
  movsx r8, cx
  movsx r8, dx
  movsx r8, bx
  movsx r8, sp
  movsx r8, bp
  movsx r8, si
  movsx r8, di
  movsx r8, r8w
  movsx r8, r9w
  movsx r8, r10w
  movsx r8, r11w
  movsx r8, r12w
  movsx r8, r13w
  movsx r8, r14w
  movsx r8, r15w
  movsx r8, byte ptr [rbx]
  movsx r8, byte ptr [r13+8]
  movsx r8, byte ptr [r12+rax*2+3]
  movsx r8, byte ptr [v8]
  movsx r8, word ptr [rbx]
  movsx r8, word ptr [r13+8]
  movsx r8, word ptr [v16]
  movsx r9, al
  movsx r9, cl
  movsx r9, dl
  movsx r9, bl
  movsx r9, spl
  movsx r9, bpl
  movsx r9, sil
  movsx r9, dil
  movsx r9, r8b
  movsx r9, r9b
  movsx r9, r10b
  movsx r9, r11b
  movsx r9, r12b
  movsx r9, r13b
  movsx r9, r14b
  movsx r9, r15b
  movsx r9, ax
  movsx r9, cx
  movsx r9, dx
  movsx r9, bx
  movsx r9, sp
  movsx r9, bp
  movsx r9, si
  movsx r9, di
  movsx r9, r8w
  movsx r9, r9w
  movsx r9, r10w
  movsx r9, r11w
  movsx r9, r12w
  movsx r9, r13w
  movsx r9, r14w
  movsx r9, r15w
  movsx r9, byte ptr [rbx]
  movsx r9, byte ptr [r13+8]
  movsx r9, byte ptr [r12+rax*2+3]
  movsx r9, byte ptr [v8]
  movsx r9, word ptr [rbx]
  movsx r9, word ptr [r13+8]
  movsx r9, word ptr [v16]
  movsx r10, al
  movsx r10, cl
  movsx r10, dl
  movsx r10, bl
  movsx r10, spl
  movsx r10, bpl
  movsx r10, sil
  movsx r10, dil
  movsx r10, r8b
  movsx r10, r9b
  movsx r10, r10b
  movsx r10, r11b
  movsx r10, r12b
  movsx r10, r13b
  movsx r10, r14b
  movsx r10, r15b
  movsx r10, ax
  movsx r10, cx
  movsx r10, dx
  movsx r10, bx
  movsx r10, sp
  movsx r10, bp
  movsx r10, si
  movsx r10, di
  movsx r10, r8w
  movsx r10, r9w
  movsx r10, r10w
  movsx r10, r11w
  movsx r10, r12w
  movsx r10, r13w
  movsx r10, r14w
  movsx r10, r15w
  movsx r10, byte ptr [rbx]
  movsx r10, byte ptr [r13+8]
  movsx r10, byte ptr [r12+rax*2+3]
  movsx r10, byte ptr [v8]
  movsx r10, word ptr [rbx]
  movsx r10, word ptr [r13+8]
  movsx r10, word ptr [v16]
  movsx r11, al
  movsx r11, cl
  movsx r11, dl
  movsx r11, bl
  movsx r11, spl
  movsx r11, bpl
  movsx r11, sil
  movsx r11, dil
  movsx r11, r8b
  movsx r11, r9b
  movsx r11, r10b
  movsx r11, r11b
  movsx r11, r12b
  movsx r11, r13b
  movsx r11, r14b
  movsx r11, r15b
  movsx r11, ax
  movsx r11, cx
  movsx r11, dx
  movsx r11, bx
  movsx r11, sp
  movsx r11, bp
  movsx r11, si
  movsx r11, di
  movsx r11, r8w
  movsx r11, r9w
  movsx r11, r10w
  movsx r11, r11w
  movsx r11, r12w
  movsx r11, r13w
  movsx r11, r14w
  movsx r11, r15w
  movsx r11, byte ptr [rbx]
  movsx r11, byte ptr [r13+8]
  movsx r11, byte ptr [r12+rax*2+3]
  movsx r11, byte ptr [v8]
  movsx r11, word ptr [rbx]
  movsx r11, word ptr [r13+8]
  movsx r11, word ptr [v16]
  movsx r12, al
  movsx r12, cl
  movsx r12, dl
  movsx r12, bl
  movsx r12, spl
  movsx r12, bpl
  movsx r12, sil
  movsx r12, dil
  movsx r12, r8b
  movsx r12, r9b
  movsx r12, r10b
  movsx r12, r11b
  movsx r12, r12b
  movsx r12, r13b
  movsx r12, r14b
  movsx r12, r15b
  movsx r12, ax
  movsx r12, cx
  movsx r12, dx
  movsx r12, bx
  movsx r12, sp
  movsx r12, bp
  movsx r12, si
  movsx r12, di
  movsx r12, r8w
  movsx r12, r9w
  movsx r12, r10w
  movsx r12, r11w
  movsx r12, r12w
  movsx r12, r13w
  movsx r12, r14w
  movsx r12, r15w
  movsx r12, byte ptr [rbx]
  movsx r12, byte ptr [r13+8]
  movsx r12, byte ptr [r12+rax*2+3]
  movsx r12, byte ptr [v8]
  movsx r12, word ptr [rbx]
  movsx r12, word ptr [r13+8]
  movsx r12, word ptr [v16]
  movsx r13, al
  movsx r13, cl
  movsx r13, dl
  movsx r13, bl
  movsx r13, spl
  movsx r13, bpl
  movsx r13, sil
  movsx r13, dil
  movsx r13, r8b
  movsx r13, r9b
  movsx r13, r10b
  movsx r13, r11b
  movsx r13, r12b
  movsx r13, r13b
  movsx r13, r14b
  movsx r13, r15b
  movsx r13, ax
  movsx r13, cx
  movsx r13, dx
  movsx r13, bx
  movsx r13, sp
  movsx r13, bp
  movsx r13, si
  movsx r13, di
  movsx r13, r8w
  movsx r13, r9w
  movsx r13, r10w
  movsx r13, r11w
  movsx r13, r12w
  movsx r13, r13w
  movsx r13, r14w
  movsx r13, r15w
  movsx r13, byte ptr [rbx]
  movsx r13, byte ptr [r13+8]
  movsx r13, byte ptr [r12+rax*2+3]
  movsx r13, byte ptr [v8]
  movsx r13, word ptr [rbx]
  movsx r13, word ptr [r13+8]
  movsx r13, word ptr [v16]
  movsx r14, al
  movsx r14, cl
  movsx r14, dl
  movsx r14, bl
  movsx r14, spl
  movsx r14, bpl
  movsx r14, sil
  movsx r14, dil
  movsx r14, r8b
  movsx r14, r9b
  movsx r14, r10b
  movsx r14, r11b
  movsx r14, r12b
  movsx r14, r13b
  movsx r14, r14b
  movsx r14, r15b
  movsx r14, ax
  movsx r14, cx
  movsx r14, dx
  movsx r14, bx
  movsx r14, sp
  movsx r14, bp
  movsx r14, si
  movsx r14, di
  movsx r14, r8w
  movsx r14, r9w
  movsx r14, r10w
  movsx r14, r11w
  movsx r14, r12w
  movsx r14, r13w
  movsx r14, r14w
  movsx r14, r15w
  movsx r14, byte ptr [rbx]
  movsx r14, byte ptr [r13+8]
  movsx r14, byte ptr [r12+rax*2+3]
  movsx r14, byte ptr [v8]
  movsx r14, word ptr [rbx]
  movsx r14, word ptr [r13+8]
  movsx r14, word ptr [v16]
  movsx r15, al
  movsx r15, cl
  movsx r15, dl
  movsx r15, bl
  movsx r15, spl
  movsx r15, bpl
  movsx r15, sil
  movsx r15, dil
  movsx r15, r8b
  movsx r15, r9b
  movsx r15, r10b
  movsx r15, r11b
  movsx r15, r12b
  movsx r15, r13b
  movsx r15, r14b
  movsx r15, r15b
  movsx r15, ax
  movsx r15, cx
  movsx r15, dx
  movsx r15, bx
  movsx r15, sp
  movsx r15, bp
  movsx r15, si
  movsx r15, di
  movsx r15, r8w
  movsx r15, r9w
  movsx r15, r10w
  movsx r15, r11w
  movsx r15, r12w
  movsx r15, r13w
  movsx r15, r14w
  movsx r15, r15w
  movsx r15, byte ptr [rbx]
  movsx r15, byte ptr [r13+8]
  movsx r15, byte ptr [r12+rax*2+3]
  movsx r15, byte ptr [v8]
  movsx r15, word ptr [rbx]
  movsx r15, word ptr [r13+8]
  movsx r15, word ptr [v16]
  movsxd rax, eax
  movsxd rax, ecx
  movsxd rax, edx
  movsxd rax, ebx
  movsxd rax, esp
  movsxd rax, ebp
  movsxd rax, esi
  movsxd rax, edi
  movsxd rax, r8d
  movsxd rax, r9d
  movsxd rax, r10d
  movsxd rax, r11d
  movsxd rax, r12d
  movsxd rax, r13d
  movsxd rax, r14d
  movsxd rax, r15d
  movsxd rax, dword ptr [rbx]
  movsxd rax, dword ptr [r13+8]
  movsxd rax, dword ptr [v32]
  movsxd rcx, eax
  movsxd rcx, ecx
  movsxd rcx, edx
  movsxd rcx, ebx
  movsxd rcx, esp
  movsxd rcx, ebp
  movsxd rcx, esi
  movsxd rcx, edi
  movsxd rcx, r8d
  movsxd rcx, r9d
  movsxd rcx, r10d
  movsxd rcx, r11d
  movsxd rcx, r12d
  movsxd rcx, r13d
  movsxd rcx, r14d
  movsxd rcx, r15d
  movsxd rcx, dword ptr [rbx]
  movsxd rcx, dword ptr [r13+8]
  movsxd rcx, dword ptr [v32]
  movsxd rdx, eax
  movsxd rdx, ecx
  movsxd rdx, edx
  movsxd rdx, ebx
  movsxd rdx, esp
  movsxd rdx, ebp
  movsxd rdx, esi
  movsxd rdx, edi
  movsxd rdx, r8d
  movsxd rdx, r9d
  movsxd rdx, r10d
  movsxd rdx, r11d
  movsxd rdx, r12d
  movsxd rdx, r13d
  movsxd rdx, r14d
  movsxd rdx, r15d
  movsxd rdx, dword ptr [rbx]
  movsxd rdx, dword ptr [r13+8]
  movsxd rdx, dword ptr [v32]
  movsxd rbx, eax
  movsxd rbx, ecx
  movsxd rbx, edx
  movsxd rbx, ebx
  movsxd rbx, esp
  movsxd rbx, ebp
  movsxd rbx, esi
  movsxd rbx, edi
  movsxd rbx, r8d
  movsxd rbx, r9d
  movsxd rbx, r10d
  movsxd rbx, r11d
  movsxd rbx, r12d
  movsxd rbx, r13d
  movsxd rbx, r14d
  movsxd rbx, r15d
  movsxd rbx, dword ptr [rbx]
  movsxd rbx, dword ptr [r13+8]
  movsxd rbx, dword ptr [v32]
  movsxd rsp, eax
  movsxd rsp, ecx
  movsxd rsp, edx
  movsxd rsp, ebx
  movsxd rsp, esp
  movsxd rsp, ebp
  movsxd rsp, esi
  movsxd rsp, edi
  movsxd rsp, r8d
  movsxd rsp, r9d
  movsxd rsp, r10d
  movsxd rsp, r11d
  movsxd rsp, r12d
  movsxd rsp, r13d
  movsxd rsp, r14d
  movsxd rsp, r15d
  movsxd rsp, dword ptr [rbx]
  movsxd rsp, dword ptr [r13+8]
  movsxd rsp, dword ptr [v32]
  movsxd rbp, eax
  movsxd rbp, ecx
  movsxd rbp, edx
  movsxd rbp, ebx
  movsxd rbp, esp
  movsxd rbp, ebp
  movsxd rbp, esi
  movsxd rbp, edi
  movsxd rbp, r8d
  movsxd rbp, r9d
  movsxd rbp, r10d
  movsxd rbp, r11d
  movsxd rbp, r12d
  movsxd rbp, r13d
  movsxd rbp, r14d
  movsxd rbp, r15d
  movsxd rbp, dword ptr [rbx]
  movsxd rbp, dword ptr [r13+8]
  movsxd rbp, dword ptr [v32]
  movsxd rsi, eax
  movsxd rsi, ecx
  movsxd rsi, edx
  movsxd rsi, ebx
  movsxd rsi, esp
  movsxd rsi, ebp
  movsxd rsi, esi
  movsxd rsi, edi
  movsxd rsi, r8d
  movsxd rsi, r9d
  movsxd rsi, r10d
  movsxd rsi, r11d
  movsxd rsi, r12d
  movsxd rsi, r13d
  movsxd rsi, r14d
  movsxd rsi, r15d
  movsxd rsi, dword ptr [rbx]
  movsxd rsi, dword ptr [r13+8]
  movsxd rsi, dword ptr [v32]
  movsxd rdi, eax
  movsxd rdi, ecx
  movsxd rdi, edx
  movsxd rdi, ebx
  movsxd rdi, esp
  movsxd rdi, ebp
  movsxd rdi, esi
  movsxd rdi, edi
  movsxd rdi, r8d
  movsxd rdi, r9d
  movsxd rdi, r10d
  movsxd rdi, r11d
  movsxd rdi, r12d
  movsxd rdi, r13d
  movsxd rdi, r14d
  movsxd rdi, r15d
  movsxd rdi, dword ptr [rbx]
  movsxd rdi, dword ptr [r13+8]
  movsxd rdi, dword ptr [v32]
  movsxd r8, eax
  movsxd r8, ecx
  movsxd r8, edx
  movsxd r8, ebx
  movsxd r8, esp
  movsxd r8, ebp
  movsxd r8, esi
  movsxd r8, edi
  movsxd r8, r8d
  movsxd r8, r9d
  movsxd r8, r10d
  movsxd r8, r11d
  movsxd r8, r12d
  movsxd r8, r13d
  movsxd r8, r14d
  movsxd r8, r15d
  movsxd r8, dword ptr [rbx]
  movsxd r8, dword ptr [r13+8]
  movsxd r8, dword ptr [v32]
  movsxd r9, eax
  movsxd r9, ecx
  movsxd r9, edx
  movsxd r9, ebx
  movsxd r9, esp
  movsxd r9, ebp
  movsxd r9, esi
  movsxd r9, edi
  movsxd r9, r8d
  movsxd r9, r9d
  movsxd r9, r10d
  movsxd r9, r11d
  movsxd r9, r12d
  movsxd r9, r13d
  movsxd r9, r14d
  movsxd r9, r15d
  movsxd r9, dword ptr [rbx]
  movsxd r9, dword ptr [r13+8]
  movsxd r9, dword ptr [v32]
  movsxd r10, eax
  movsxd r10, ecx
  movsxd r10, edx
  movsxd r10, ebx
  movsxd r10, esp
  movsxd r10, ebp
  movsxd r10, esi
  movsxd r10, edi
  movsxd r10, r8d
  movsxd r10, r9d
  movsxd r10, r10d
  movsxd r10, r11d
  movsxd r10, r12d
  movsxd r10, r13d
  movsxd r10, r14d
  movsxd r10, r15d
  movsxd r10, dword ptr [rbx]
  movsxd r10, dword ptr [r13+8]
  movsxd r10, dword ptr [v32]
  movsxd r11, eax
  movsxd r11, ecx
  movsxd r11, edx
  movsxd r11, ebx
  movsxd r11, esp
  movsxd r11, ebp
  movsxd r11, esi
  movsxd r11, edi
  movsxd r11, r8d
  movsxd r11, r9d
  movsxd r11, r10d
  movsxd r11, r11d
  movsxd r11, r12d
  movsxd r11, r13d
  movsxd r11, r14d
  movsxd r11, r15d
  movsxd r11, dword ptr [rbx]
  movsxd r11, dword ptr [r13+8]
  movsxd r11, dword ptr [v32]
  movsxd r12, eax
  movsxd r12, ecx
  movsxd r12, edx
  movsxd r12, ebx
  movsxd r12, esp
  movsxd r12, ebp
  movsxd r12, esi
  movsxd r12, edi
  movsxd r12, r8d
  movsxd r12, r9d
  movsxd r12, r10d
  movsxd r12, r11d
  movsxd r12, r12d
  movsxd r12, r13d
  movsxd r12, r14d
  movsxd r12, r15d
  movsxd r12, dword ptr [rbx]
  movsxd r12, dword ptr [r13+8]
  movsxd r12, dword ptr [v32]
  movsxd r13, eax
  movsxd r13, ecx
  movsxd r13, edx
  movsxd r13, ebx
  movsxd r13, esp
  movsxd r13, ebp
  movsxd r13, esi
  movsxd r13, edi
  movsxd r13, r8d
  movsxd r13, r9d
  movsxd r13, r10d
  movsxd r13, r11d
  movsxd r13, r12d
  movsxd r13, r13d
  movsxd r13, r14d
  movsxd r13, r15d
  movsxd r13, dword ptr [rbx]
  movsxd r13, dword ptr [r13+8]
  movsxd r13, dword ptr [v32]
  movsxd r14, eax
  movsxd r14, ecx
  movsxd r14, edx
  movsxd r14, ebx
  movsxd r14, esp
  movsxd r14, ebp
  movsxd r14, esi
  movsxd r14, edi
  movsxd r14, r8d
  movsxd r14, r9d
  movsxd r14, r10d
  movsxd r14, r11d
  movsxd r14, r12d
  movsxd r14, r13d
  movsxd r14, r14d
  movsxd r14, r15d
  movsxd r14, dword ptr [rbx]
  movsxd r14, dword ptr [r13+8]
  movsxd r14, dword ptr [v32]
  movsxd r15, eax
  movsxd r15, ecx
  movsxd r15, edx
  movsxd r15, ebx
  movsxd r15, esp
  movsxd r15, ebp
  movsxd r15, esi
  movsxd r15, edi
  movsxd r15, r8d
  movsxd r15, r9d
  movsxd r15, r10d
  movsxd r15, r11d
  movsxd r15, r12d
  movsxd r15, r13d
  movsxd r15, r14d
  movsxd r15, r15d
  movsxd r15, dword ptr [rbx]
  movsxd r15, dword ptr [r13+8]
  movsxd r15, dword ptr [v32]
f ENDP
END
