; a15-setcc-cmov - generated by gen.py, ml64 is the oracle
.DATA
v8 DB 0
v16 DW 0
v32 DD 0
v64 DQ 0
.CODE
f PROC
  seto al
  seto cl
  seto dl
  seto bl
  seto ah
  seto ch
  seto dh
  seto bh
  seto spl
  seto bpl
  seto sil
  seto dil
  seto r8b
  seto r9b
  seto r10b
  seto r11b
  seto r12b
  seto r13b
  seto r14b
  seto r15b
  seto byte ptr [rbx]
  seto byte ptr [r12+rax*2+3]
  seto byte ptr [v8]
  cmovo eax, ecx
  cmovo r9d, eax
  cmovo eax, r9d
  cmovo rax, rcx
  cmovo r8, r9
  cmovo rcx, r15
  cmovo ax, cx
  cmovo r10w, ax
  cmovo eax, dword ptr [rbx]
  cmovo rax, qword ptr [r13+8]
  cmovo r9, qword ptr [v64]
  cmovo ax, word ptr [rbx]
  setno al
  setno cl
  setno dl
  setno bl
  setno ah
  setno ch
  setno dh
  setno bh
  setno spl
  setno bpl
  setno sil
  setno dil
  setno r8b
  setno r9b
  setno r10b
  setno r11b
  setno r12b
  setno r13b
  setno r14b
  setno r15b
  setno byte ptr [rbx]
  setno byte ptr [r12+rax*2+3]
  setno byte ptr [v8]
  cmovno eax, ecx
  cmovno r9d, eax
  cmovno eax, r9d
  cmovno rax, rcx
  cmovno r8, r9
  cmovno rcx, r15
  cmovno ax, cx
  cmovno r10w, ax
  cmovno eax, dword ptr [rbx]
  cmovno rax, qword ptr [r13+8]
  cmovno r9, qword ptr [v64]
  cmovno ax, word ptr [rbx]
  setb al
  setb cl
  setb dl
  setb bl
  setb ah
  setb ch
  setb dh
  setb bh
  setb spl
  setb bpl
  setb sil
  setb dil
  setb r8b
  setb r9b
  setb r10b
  setb r11b
  setb r12b
  setb r13b
  setb r14b
  setb r15b
  setb byte ptr [rbx]
  setb byte ptr [r12+rax*2+3]
  setb byte ptr [v8]
  cmovb eax, ecx
  cmovb r9d, eax
  cmovb eax, r9d
  cmovb rax, rcx
  cmovb r8, r9
  cmovb rcx, r15
  cmovb ax, cx
  cmovb r10w, ax
  cmovb eax, dword ptr [rbx]
  cmovb rax, qword ptr [r13+8]
  cmovb r9, qword ptr [v64]
  cmovb ax, word ptr [rbx]
  setc al
  setc cl
  setc dl
  setc bl
  setc ah
  setc ch
  setc dh
  setc bh
  setc spl
  setc bpl
  setc sil
  setc dil
  setc r8b
  setc r9b
  setc r10b
  setc r11b
  setc r12b
  setc r13b
  setc r14b
  setc r15b
  setc byte ptr [rbx]
  setc byte ptr [r12+rax*2+3]
  setc byte ptr [v8]
  cmovc eax, ecx
  cmovc r9d, eax
  cmovc eax, r9d
  cmovc rax, rcx
  cmovc r8, r9
  cmovc rcx, r15
  cmovc ax, cx
  cmovc r10w, ax
  cmovc eax, dword ptr [rbx]
  cmovc rax, qword ptr [r13+8]
  cmovc r9, qword ptr [v64]
  cmovc ax, word ptr [rbx]
  setnae al
  setnae cl
  setnae dl
  setnae bl
  setnae ah
  setnae ch
  setnae dh
  setnae bh
  setnae spl
  setnae bpl
  setnae sil
  setnae dil
  setnae r8b
  setnae r9b
  setnae r10b
  setnae r11b
  setnae r12b
  setnae r13b
  setnae r14b
  setnae r15b
  setnae byte ptr [rbx]
  setnae byte ptr [r12+rax*2+3]
  setnae byte ptr [v8]
  cmovnae eax, ecx
  cmovnae r9d, eax
  cmovnae eax, r9d
  cmovnae rax, rcx
  cmovnae r8, r9
  cmovnae rcx, r15
  cmovnae ax, cx
  cmovnae r10w, ax
  cmovnae eax, dword ptr [rbx]
  cmovnae rax, qword ptr [r13+8]
  cmovnae r9, qword ptr [v64]
  cmovnae ax, word ptr [rbx]
  setae al
  setae cl
  setae dl
  setae bl
  setae ah
  setae ch
  setae dh
  setae bh
  setae spl
  setae bpl
  setae sil
  setae dil
  setae r8b
  setae r9b
  setae r10b
  setae r11b
  setae r12b
  setae r13b
  setae r14b
  setae r15b
  setae byte ptr [rbx]
  setae byte ptr [r12+rax*2+3]
  setae byte ptr [v8]
  cmovae eax, ecx
  cmovae r9d, eax
  cmovae eax, r9d
  cmovae rax, rcx
  cmovae r8, r9
  cmovae rcx, r15
  cmovae ax, cx
  cmovae r10w, ax
  cmovae eax, dword ptr [rbx]
  cmovae rax, qword ptr [r13+8]
  cmovae r9, qword ptr [v64]
  cmovae ax, word ptr [rbx]
  setnb al
  setnb cl
  setnb dl
  setnb bl
  setnb ah
  setnb ch
  setnb dh
  setnb bh
  setnb spl
  setnb bpl
  setnb sil
  setnb dil
  setnb r8b
  setnb r9b
  setnb r10b
  setnb r11b
  setnb r12b
  setnb r13b
  setnb r14b
  setnb r15b
  setnb byte ptr [rbx]
  setnb byte ptr [r12+rax*2+3]
  setnb byte ptr [v8]
  cmovnb eax, ecx
  cmovnb r9d, eax
  cmovnb eax, r9d
  cmovnb rax, rcx
  cmovnb r8, r9
  cmovnb rcx, r15
  cmovnb ax, cx
  cmovnb r10w, ax
  cmovnb eax, dword ptr [rbx]
  cmovnb rax, qword ptr [r13+8]
  cmovnb r9, qword ptr [v64]
  cmovnb ax, word ptr [rbx]
  setnc al
  setnc cl
  setnc dl
  setnc bl
  setnc ah
  setnc ch
  setnc dh
  setnc bh
  setnc spl
  setnc bpl
  setnc sil
  setnc dil
  setnc r8b
  setnc r9b
  setnc r10b
  setnc r11b
  setnc r12b
  setnc r13b
  setnc r14b
  setnc r15b
  setnc byte ptr [rbx]
  setnc byte ptr [r12+rax*2+3]
  setnc byte ptr [v8]
  cmovnc eax, ecx
  cmovnc r9d, eax
  cmovnc eax, r9d
  cmovnc rax, rcx
  cmovnc r8, r9
  cmovnc rcx, r15
  cmovnc ax, cx
  cmovnc r10w, ax
  cmovnc eax, dword ptr [rbx]
  cmovnc rax, qword ptr [r13+8]
  cmovnc r9, qword ptr [v64]
  cmovnc ax, word ptr [rbx]
  sete al
  sete cl
  sete dl
  sete bl
  sete ah
  sete ch
  sete dh
  sete bh
  sete spl
  sete bpl
  sete sil
  sete dil
  sete r8b
  sete r9b
  sete r10b
  sete r11b
  sete r12b
  sete r13b
  sete r14b
  sete r15b
  sete byte ptr [rbx]
  sete byte ptr [r12+rax*2+3]
  sete byte ptr [v8]
  cmove eax, ecx
  cmove r9d, eax
  cmove eax, r9d
  cmove rax, rcx
  cmove r8, r9
  cmove rcx, r15
  cmove ax, cx
  cmove r10w, ax
  cmove eax, dword ptr [rbx]
  cmove rax, qword ptr [r13+8]
  cmove r9, qword ptr [v64]
  cmove ax, word ptr [rbx]
  setz al
  setz cl
  setz dl
  setz bl
  setz ah
  setz ch
  setz dh
  setz bh
  setz spl
  setz bpl
  setz sil
  setz dil
  setz r8b
  setz r9b
  setz r10b
  setz r11b
  setz r12b
  setz r13b
  setz r14b
  setz r15b
  setz byte ptr [rbx]
  setz byte ptr [r12+rax*2+3]
  setz byte ptr [v8]
  cmovz eax, ecx
  cmovz r9d, eax
  cmovz eax, r9d
  cmovz rax, rcx
  cmovz r8, r9
  cmovz rcx, r15
  cmovz ax, cx
  cmovz r10w, ax
  cmovz eax, dword ptr [rbx]
  cmovz rax, qword ptr [r13+8]
  cmovz r9, qword ptr [v64]
  cmovz ax, word ptr [rbx]
  setne al
  setne cl
  setne dl
  setne bl
  setne ah
  setne ch
  setne dh
  setne bh
  setne spl
  setne bpl
  setne sil
  setne dil
  setne r8b
  setne r9b
  setne r10b
  setne r11b
  setne r12b
  setne r13b
  setne r14b
  setne r15b
  setne byte ptr [rbx]
  setne byte ptr [r12+rax*2+3]
  setne byte ptr [v8]
  cmovne eax, ecx
  cmovne r9d, eax
  cmovne eax, r9d
  cmovne rax, rcx
  cmovne r8, r9
  cmovne rcx, r15
  cmovne ax, cx
  cmovne r10w, ax
  cmovne eax, dword ptr [rbx]
  cmovne rax, qword ptr [r13+8]
  cmovne r9, qword ptr [v64]
  cmovne ax, word ptr [rbx]
  setnz al
  setnz cl
  setnz dl
  setnz bl
  setnz ah
  setnz ch
  setnz dh
  setnz bh
  setnz spl
  setnz bpl
  setnz sil
  setnz dil
  setnz r8b
  setnz r9b
  setnz r10b
  setnz r11b
  setnz r12b
  setnz r13b
  setnz r14b
  setnz r15b
  setnz byte ptr [rbx]
  setnz byte ptr [r12+rax*2+3]
  setnz byte ptr [v8]
  cmovnz eax, ecx
  cmovnz r9d, eax
  cmovnz eax, r9d
  cmovnz rax, rcx
  cmovnz r8, r9
  cmovnz rcx, r15
  cmovnz ax, cx
  cmovnz r10w, ax
  cmovnz eax, dword ptr [rbx]
  cmovnz rax, qword ptr [r13+8]
  cmovnz r9, qword ptr [v64]
  cmovnz ax, word ptr [rbx]
  setbe al
  setbe cl
  setbe dl
  setbe bl
  setbe ah
  setbe ch
  setbe dh
  setbe bh
  setbe spl
  setbe bpl
  setbe sil
  setbe dil
  setbe r8b
  setbe r9b
  setbe r10b
  setbe r11b
  setbe r12b
  setbe r13b
  setbe r14b
  setbe r15b
  setbe byte ptr [rbx]
  setbe byte ptr [r12+rax*2+3]
  setbe byte ptr [v8]
  cmovbe eax, ecx
  cmovbe r9d, eax
  cmovbe eax, r9d
  cmovbe rax, rcx
  cmovbe r8, r9
  cmovbe rcx, r15
  cmovbe ax, cx
  cmovbe r10w, ax
  cmovbe eax, dword ptr [rbx]
  cmovbe rax, qword ptr [r13+8]
  cmovbe r9, qword ptr [v64]
  cmovbe ax, word ptr [rbx]
  setna al
  setna cl
  setna dl
  setna bl
  setna ah
  setna ch
  setna dh
  setna bh
  setna spl
  setna bpl
  setna sil
  setna dil
  setna r8b
  setna r9b
  setna r10b
  setna r11b
  setna r12b
  setna r13b
  setna r14b
  setna r15b
  setna byte ptr [rbx]
  setna byte ptr [r12+rax*2+3]
  setna byte ptr [v8]
  cmovna eax, ecx
  cmovna r9d, eax
  cmovna eax, r9d
  cmovna rax, rcx
  cmovna r8, r9
  cmovna rcx, r15
  cmovna ax, cx
  cmovna r10w, ax
  cmovna eax, dword ptr [rbx]
  cmovna rax, qword ptr [r13+8]
  cmovna r9, qword ptr [v64]
  cmovna ax, word ptr [rbx]
  seta al
  seta cl
  seta dl
  seta bl
  seta ah
  seta ch
  seta dh
  seta bh
  seta spl
  seta bpl
  seta sil
  seta dil
  seta r8b
  seta r9b
  seta r10b
  seta r11b
  seta r12b
  seta r13b
  seta r14b
  seta r15b
  seta byte ptr [rbx]
  seta byte ptr [r12+rax*2+3]
  seta byte ptr [v8]
  cmova eax, ecx
  cmova r9d, eax
  cmova eax, r9d
  cmova rax, rcx
  cmova r8, r9
  cmova rcx, r15
  cmova ax, cx
  cmova r10w, ax
  cmova eax, dword ptr [rbx]
  cmova rax, qword ptr [r13+8]
  cmova r9, qword ptr [v64]
  cmova ax, word ptr [rbx]
  setnbe al
  setnbe cl
  setnbe dl
  setnbe bl
  setnbe ah
  setnbe ch
  setnbe dh
  setnbe bh
  setnbe spl
  setnbe bpl
  setnbe sil
  setnbe dil
  setnbe r8b
  setnbe r9b
  setnbe r10b
  setnbe r11b
  setnbe r12b
  setnbe r13b
  setnbe r14b
  setnbe r15b
  setnbe byte ptr [rbx]
  setnbe byte ptr [r12+rax*2+3]
  setnbe byte ptr [v8]
  cmovnbe eax, ecx
  cmovnbe r9d, eax
  cmovnbe eax, r9d
  cmovnbe rax, rcx
  cmovnbe r8, r9
  cmovnbe rcx, r15
  cmovnbe ax, cx
  cmovnbe r10w, ax
  cmovnbe eax, dword ptr [rbx]
  cmovnbe rax, qword ptr [r13+8]
  cmovnbe r9, qword ptr [v64]
  cmovnbe ax, word ptr [rbx]
  sets al
  sets cl
  sets dl
  sets bl
  sets ah
  sets ch
  sets dh
  sets bh
  sets spl
  sets bpl
  sets sil
  sets dil
  sets r8b
  sets r9b
  sets r10b
  sets r11b
  sets r12b
  sets r13b
  sets r14b
  sets r15b
  sets byte ptr [rbx]
  sets byte ptr [r12+rax*2+3]
  sets byte ptr [v8]
  cmovs eax, ecx
  cmovs r9d, eax
  cmovs eax, r9d
  cmovs rax, rcx
  cmovs r8, r9
  cmovs rcx, r15
  cmovs ax, cx
  cmovs r10w, ax
  cmovs eax, dword ptr [rbx]
  cmovs rax, qword ptr [r13+8]
  cmovs r9, qword ptr [v64]
  cmovs ax, word ptr [rbx]
  setns al
  setns cl
  setns dl
  setns bl
  setns ah
  setns ch
  setns dh
  setns bh
  setns spl
  setns bpl
  setns sil
  setns dil
  setns r8b
  setns r9b
  setns r10b
  setns r11b
  setns r12b
  setns r13b
  setns r14b
  setns r15b
  setns byte ptr [rbx]
  setns byte ptr [r12+rax*2+3]
  setns byte ptr [v8]
  cmovns eax, ecx
  cmovns r9d, eax
  cmovns eax, r9d
  cmovns rax, rcx
  cmovns r8, r9
  cmovns rcx, r15
  cmovns ax, cx
  cmovns r10w, ax
  cmovns eax, dword ptr [rbx]
  cmovns rax, qword ptr [r13+8]
  cmovns r9, qword ptr [v64]
  cmovns ax, word ptr [rbx]
  setp al
  setp cl
  setp dl
  setp bl
  setp ah
  setp ch
  setp dh
  setp bh
  setp spl
  setp bpl
  setp sil
  setp dil
  setp r8b
  setp r9b
  setp r10b
  setp r11b
  setp r12b
  setp r13b
  setp r14b
  setp r15b
  setp byte ptr [rbx]
  setp byte ptr [r12+rax*2+3]
  setp byte ptr [v8]
  cmovp eax, ecx
  cmovp r9d, eax
  cmovp eax, r9d
  cmovp rax, rcx
  cmovp r8, r9
  cmovp rcx, r15
  cmovp ax, cx
  cmovp r10w, ax
  cmovp eax, dword ptr [rbx]
  cmovp rax, qword ptr [r13+8]
  cmovp r9, qword ptr [v64]
  cmovp ax, word ptr [rbx]
  setpe al
  setpe cl
  setpe dl
  setpe bl
  setpe ah
  setpe ch
  setpe dh
  setpe bh
  setpe spl
  setpe bpl
  setpe sil
  setpe dil
  setpe r8b
  setpe r9b
  setpe r10b
  setpe r11b
  setpe r12b
  setpe r13b
  setpe r14b
  setpe r15b
  setpe byte ptr [rbx]
  setpe byte ptr [r12+rax*2+3]
  setpe byte ptr [v8]
  cmovpe eax, ecx
  cmovpe r9d, eax
  cmovpe eax, r9d
  cmovpe rax, rcx
  cmovpe r8, r9
  cmovpe rcx, r15
  cmovpe ax, cx
  cmovpe r10w, ax
  cmovpe eax, dword ptr [rbx]
  cmovpe rax, qword ptr [r13+8]
  cmovpe r9, qword ptr [v64]
  cmovpe ax, word ptr [rbx]
  setnp al
  setnp cl
  setnp dl
  setnp bl
  setnp ah
  setnp ch
  setnp dh
  setnp bh
  setnp spl
  setnp bpl
  setnp sil
  setnp dil
  setnp r8b
  setnp r9b
  setnp r10b
  setnp r11b
  setnp r12b
  setnp r13b
  setnp r14b
  setnp r15b
  setnp byte ptr [rbx]
  setnp byte ptr [r12+rax*2+3]
  setnp byte ptr [v8]
  cmovnp eax, ecx
  cmovnp r9d, eax
  cmovnp eax, r9d
  cmovnp rax, rcx
  cmovnp r8, r9
  cmovnp rcx, r15
  cmovnp ax, cx
  cmovnp r10w, ax
  cmovnp eax, dword ptr [rbx]
  cmovnp rax, qword ptr [r13+8]
  cmovnp r9, qword ptr [v64]
  cmovnp ax, word ptr [rbx]
  setpo al
  setpo cl
  setpo dl
  setpo bl
  setpo ah
  setpo ch
  setpo dh
  setpo bh
  setpo spl
  setpo bpl
  setpo sil
  setpo dil
  setpo r8b
  setpo r9b
  setpo r10b
  setpo r11b
  setpo r12b
  setpo r13b
  setpo r14b
  setpo r15b
  setpo byte ptr [rbx]
  setpo byte ptr [r12+rax*2+3]
  setpo byte ptr [v8]
  cmovpo eax, ecx
  cmovpo r9d, eax
  cmovpo eax, r9d
  cmovpo rax, rcx
  cmovpo r8, r9
  cmovpo rcx, r15
  cmovpo ax, cx
  cmovpo r10w, ax
  cmovpo eax, dword ptr [rbx]
  cmovpo rax, qword ptr [r13+8]
  cmovpo r9, qword ptr [v64]
  cmovpo ax, word ptr [rbx]
  setl al
  setl cl
  setl dl
  setl bl
  setl ah
  setl ch
  setl dh
  setl bh
  setl spl
  setl bpl
  setl sil
  setl dil
  setl r8b
  setl r9b
  setl r10b
  setl r11b
  setl r12b
  setl r13b
  setl r14b
  setl r15b
  setl byte ptr [rbx]
  setl byte ptr [r12+rax*2+3]
  setl byte ptr [v8]
  cmovl eax, ecx
  cmovl r9d, eax
  cmovl eax, r9d
  cmovl rax, rcx
  cmovl r8, r9
  cmovl rcx, r15
  cmovl ax, cx
  cmovl r10w, ax
  cmovl eax, dword ptr [rbx]
  cmovl rax, qword ptr [r13+8]
  cmovl r9, qword ptr [v64]
  cmovl ax, word ptr [rbx]
  setnge al
  setnge cl
  setnge dl
  setnge bl
  setnge ah
  setnge ch
  setnge dh
  setnge bh
  setnge spl
  setnge bpl
  setnge sil
  setnge dil
  setnge r8b
  setnge r9b
  setnge r10b
  setnge r11b
  setnge r12b
  setnge r13b
  setnge r14b
  setnge r15b
  setnge byte ptr [rbx]
  setnge byte ptr [r12+rax*2+3]
  setnge byte ptr [v8]
  cmovnge eax, ecx
  cmovnge r9d, eax
  cmovnge eax, r9d
  cmovnge rax, rcx
  cmovnge r8, r9
  cmovnge rcx, r15
  cmovnge ax, cx
  cmovnge r10w, ax
  cmovnge eax, dword ptr [rbx]
  cmovnge rax, qword ptr [r13+8]
  cmovnge r9, qword ptr [v64]
  cmovnge ax, word ptr [rbx]
  setge al
  setge cl
  setge dl
  setge bl
  setge ah
  setge ch
  setge dh
  setge bh
  setge spl
  setge bpl
  setge sil
  setge dil
  setge r8b
  setge r9b
  setge r10b
  setge r11b
  setge r12b
  setge r13b
  setge r14b
  setge r15b
  setge byte ptr [rbx]
  setge byte ptr [r12+rax*2+3]
  setge byte ptr [v8]
  cmovge eax, ecx
  cmovge r9d, eax
  cmovge eax, r9d
  cmovge rax, rcx
  cmovge r8, r9
  cmovge rcx, r15
  cmovge ax, cx
  cmovge r10w, ax
  cmovge eax, dword ptr [rbx]
  cmovge rax, qword ptr [r13+8]
  cmovge r9, qword ptr [v64]
  cmovge ax, word ptr [rbx]
  setnl al
  setnl cl
  setnl dl
  setnl bl
  setnl ah
  setnl ch
  setnl dh
  setnl bh
  setnl spl
  setnl bpl
  setnl sil
  setnl dil
  setnl r8b
  setnl r9b
  setnl r10b
  setnl r11b
  setnl r12b
  setnl r13b
  setnl r14b
  setnl r15b
  setnl byte ptr [rbx]
  setnl byte ptr [r12+rax*2+3]
  setnl byte ptr [v8]
  cmovnl eax, ecx
  cmovnl r9d, eax
  cmovnl eax, r9d
  cmovnl rax, rcx
  cmovnl r8, r9
  cmovnl rcx, r15
  cmovnl ax, cx
  cmovnl r10w, ax
  cmovnl eax, dword ptr [rbx]
  cmovnl rax, qword ptr [r13+8]
  cmovnl r9, qword ptr [v64]
  cmovnl ax, word ptr [rbx]
  setle al
  setle cl
  setle dl
  setle bl
  setle ah
  setle ch
  setle dh
  setle bh
  setle spl
  setle bpl
  setle sil
  setle dil
  setle r8b
  setle r9b
  setle r10b
  setle r11b
  setle r12b
  setle r13b
  setle r14b
  setle r15b
  setle byte ptr [rbx]
  setle byte ptr [r12+rax*2+3]
  setle byte ptr [v8]
  cmovle eax, ecx
  cmovle r9d, eax
  cmovle eax, r9d
  cmovle rax, rcx
  cmovle r8, r9
  cmovle rcx, r15
  cmovle ax, cx
  cmovle r10w, ax
  cmovle eax, dword ptr [rbx]
  cmovle rax, qword ptr [r13+8]
  cmovle r9, qword ptr [v64]
  cmovle ax, word ptr [rbx]
  setng al
  setng cl
  setng dl
  setng bl
  setng ah
  setng ch
  setng dh
  setng bh
  setng spl
  setng bpl
  setng sil
  setng dil
  setng r8b
  setng r9b
  setng r10b
  setng r11b
  setng r12b
  setng r13b
  setng r14b
  setng r15b
  setng byte ptr [rbx]
  setng byte ptr [r12+rax*2+3]
  setng byte ptr [v8]
  cmovng eax, ecx
  cmovng r9d, eax
  cmovng eax, r9d
  cmovng rax, rcx
  cmovng r8, r9
  cmovng rcx, r15
  cmovng ax, cx
  cmovng r10w, ax
  cmovng eax, dword ptr [rbx]
  cmovng rax, qword ptr [r13+8]
  cmovng r9, qword ptr [v64]
  cmovng ax, word ptr [rbx]
  setg al
  setg cl
  setg dl
  setg bl
  setg ah
  setg ch
  setg dh
  setg bh
  setg spl
  setg bpl
  setg sil
  setg dil
  setg r8b
  setg r9b
  setg r10b
  setg r11b
  setg r12b
  setg r13b
  setg r14b
  setg r15b
  setg byte ptr [rbx]
  setg byte ptr [r12+rax*2+3]
  setg byte ptr [v8]
  cmovg eax, ecx
  cmovg r9d, eax
  cmovg eax, r9d
  cmovg rax, rcx
  cmovg r8, r9
  cmovg rcx, r15
  cmovg ax, cx
  cmovg r10w, ax
  cmovg eax, dword ptr [rbx]
  cmovg rax, qword ptr [r13+8]
  cmovg r9, qword ptr [v64]
  cmovg ax, word ptr [rbx]
  setnle al
  setnle cl
  setnle dl
  setnle bl
  setnle ah
  setnle ch
  setnle dh
  setnle bh
  setnle spl
  setnle bpl
  setnle sil
  setnle dil
  setnle r8b
  setnle r9b
  setnle r10b
  setnle r11b
  setnle r12b
  setnle r13b
  setnle r14b
  setnle r15b
  setnle byte ptr [rbx]
  setnle byte ptr [r12+rax*2+3]
  setnle byte ptr [v8]
  cmovnle eax, ecx
  cmovnle r9d, eax
  cmovnle eax, r9d
  cmovnle rax, rcx
  cmovnle r8, r9
  cmovnle rcx, r15
  cmovnle ax, cx
  cmovnle r10w, ax
  cmovnle eax, dword ptr [rbx]
  cmovnle rax, qword ptr [r13+8]
  cmovnle r9, qword ptr [v64]
  cmovnle ax, word ptr [rbx]
f ENDP
END
