; a16-sse - generated by gen.py, ml64 is the oracle
.DATA
v8 DB 0
v16 DW 0
v32 DD 0
v64 DQ 0
.CODE
f PROC
  movsd xmm0, xmm1
  movsd xmm1, xmm0
  movsd xmm8, xmm1
  movsd xmm1, xmm8
  movsd xmm15, xmm15
  movsd xmm7, xmm7
  movsd xmm3, xmm12
  movsd xmm1, qword ptr [rbx]
  movsd xmm1, qword ptr [r13+8]
  movsd xmm1, qword ptr [r12+rax*8+16]
  movsd xmm1, qword ptr [v64]
  movsd xmm9, qword ptr [rbx]
  movsd xmm9, qword ptr [r13+8]
  movsd xmm9, qword ptr [r12+rax*8+16]
  movsd xmm9, qword ptr [v64]
  addsd xmm0, xmm1
  addsd xmm1, xmm0
  addsd xmm8, xmm1
  addsd xmm1, xmm8
  addsd xmm15, xmm15
  addsd xmm7, xmm7
  addsd xmm3, xmm12
  addsd xmm1, qword ptr [rbx]
  addsd xmm1, qword ptr [r13+8]
  addsd xmm1, qword ptr [r12+rax*8+16]
  addsd xmm1, qword ptr [v64]
  addsd xmm9, qword ptr [rbx]
  addsd xmm9, qword ptr [r13+8]
  addsd xmm9, qword ptr [r12+rax*8+16]
  addsd xmm9, qword ptr [v64]
  subsd xmm0, xmm1
  subsd xmm1, xmm0
  subsd xmm8, xmm1
  subsd xmm1, xmm8
  subsd xmm15, xmm15
  subsd xmm7, xmm7
  subsd xmm3, xmm12
  subsd xmm1, qword ptr [rbx]
  subsd xmm1, qword ptr [r13+8]
  subsd xmm1, qword ptr [r12+rax*8+16]
  subsd xmm1, qword ptr [v64]
  subsd xmm9, qword ptr [rbx]
  subsd xmm9, qword ptr [r13+8]
  subsd xmm9, qword ptr [r12+rax*8+16]
  subsd xmm9, qword ptr [v64]
  mulsd xmm0, xmm1
  mulsd xmm1, xmm0
  mulsd xmm8, xmm1
  mulsd xmm1, xmm8
  mulsd xmm15, xmm15
  mulsd xmm7, xmm7
  mulsd xmm3, xmm12
  mulsd xmm1, qword ptr [rbx]
  mulsd xmm1, qword ptr [r13+8]
  mulsd xmm1, qword ptr [r12+rax*8+16]
  mulsd xmm1, qword ptr [v64]
  mulsd xmm9, qword ptr [rbx]
  mulsd xmm9, qword ptr [r13+8]
  mulsd xmm9, qword ptr [r12+rax*8+16]
  mulsd xmm9, qword ptr [v64]
  divsd xmm0, xmm1
  divsd xmm1, xmm0
  divsd xmm8, xmm1
  divsd xmm1, xmm8
  divsd xmm15, xmm15
  divsd xmm7, xmm7
  divsd xmm3, xmm12
  divsd xmm1, qword ptr [rbx]
  divsd xmm1, qword ptr [r13+8]
  divsd xmm1, qword ptr [r12+rax*8+16]
  divsd xmm1, qword ptr [v64]
  divsd xmm9, qword ptr [rbx]
  divsd xmm9, qword ptr [r13+8]
  divsd xmm9, qword ptr [r12+rax*8+16]
  divsd xmm9, qword ptr [v64]
  sqrtsd xmm0, xmm1
  sqrtsd xmm1, xmm0
  sqrtsd xmm8, xmm1
  sqrtsd xmm1, xmm8
  sqrtsd xmm15, xmm15
  sqrtsd xmm7, xmm7
  sqrtsd xmm3, xmm12
  sqrtsd xmm1, qword ptr [rbx]
  sqrtsd xmm1, qword ptr [r13+8]
  sqrtsd xmm1, qword ptr [r12+rax*8+16]
  sqrtsd xmm1, qword ptr [v64]
  sqrtsd xmm9, qword ptr [rbx]
  sqrtsd xmm9, qword ptr [r13+8]
  sqrtsd xmm9, qword ptr [r12+rax*8+16]
  sqrtsd xmm9, qword ptr [v64]
  minsd xmm0, xmm1
  minsd xmm1, xmm0
  minsd xmm8, xmm1
  minsd xmm1, xmm8
  minsd xmm15, xmm15
  minsd xmm7, xmm7
  minsd xmm3, xmm12
  minsd xmm1, qword ptr [rbx]
  minsd xmm1, qword ptr [r13+8]
  minsd xmm1, qword ptr [r12+rax*8+16]
  minsd xmm1, qword ptr [v64]
  minsd xmm9, qword ptr [rbx]
  minsd xmm9, qword ptr [r13+8]
  minsd xmm9, qword ptr [r12+rax*8+16]
  minsd xmm9, qword ptr [v64]
  maxsd xmm0, xmm1
  maxsd xmm1, xmm0
  maxsd xmm8, xmm1
  maxsd xmm1, xmm8
  maxsd xmm15, xmm15
  maxsd xmm7, xmm7
  maxsd xmm3, xmm12
  maxsd xmm1, qword ptr [rbx]
  maxsd xmm1, qword ptr [r13+8]
  maxsd xmm1, qword ptr [r12+rax*8+16]
  maxsd xmm1, qword ptr [v64]
  maxsd xmm9, qword ptr [rbx]
  maxsd xmm9, qword ptr [r13+8]
  maxsd xmm9, qword ptr [r12+rax*8+16]
  maxsd xmm9, qword ptr [v64]
  ucomisd xmm0, xmm1
  ucomisd xmm1, xmm0
  ucomisd xmm8, xmm1
  ucomisd xmm1, xmm8
  ucomisd xmm15, xmm15
  ucomisd xmm7, xmm7
  ucomisd xmm3, xmm12
  ucomisd xmm1, qword ptr [rbx]
  ucomisd xmm1, qword ptr [r13+8]
  ucomisd xmm1, qword ptr [r12+rax*8+16]
  ucomisd xmm1, qword ptr [v64]
  ucomisd xmm9, qword ptr [rbx]
  ucomisd xmm9, qword ptr [r13+8]
  ucomisd xmm9, qword ptr [r12+rax*8+16]
  ucomisd xmm9, qword ptr [v64]
  comisd xmm0, xmm1
  comisd xmm1, xmm0
  comisd xmm8, xmm1
  comisd xmm1, xmm8
  comisd xmm15, xmm15
  comisd xmm7, xmm7
  comisd xmm3, xmm12
  comisd xmm1, qword ptr [rbx]
  comisd xmm1, qword ptr [r13+8]
  comisd xmm1, qword ptr [r12+rax*8+16]
  comisd xmm1, qword ptr [v64]
  comisd xmm9, qword ptr [rbx]
  comisd xmm9, qword ptr [r13+8]
  comisd xmm9, qword ptr [r12+rax*8+16]
  comisd xmm9, qword ptr [v64]
  cvtss2sd xmm0, xmm1
  cvtss2sd xmm1, xmm0
  cvtss2sd xmm8, xmm1
  cvtss2sd xmm1, xmm8
  cvtss2sd xmm15, xmm15
  cvtss2sd xmm7, xmm7
  cvtss2sd xmm3, xmm12
  cvtss2sd xmm2, dword ptr [rbx]
  cvtss2sd xmm2, dword ptr [r13+8]
  cvtss2sd xmm2, dword ptr [r12+rax*8+16]
  cvtss2sd xmm2, dword ptr [v64]
  cvtss2sd xmm9, dword ptr [rbx]
  cvtss2sd xmm9, dword ptr [r13+8]
  cvtss2sd xmm9, dword ptr [r12+rax*8+16]
  cvtss2sd xmm9, dword ptr [v64]
  movsd qword ptr [rbx], xmm1
  movsd qword ptr [rbx], xmm9
  movsd qword ptr [r13+8], xmm1
  movsd qword ptr [r13+8], xmm9
  movsd qword ptr [r12+rax*8+16], xmm1
  movsd qword ptr [r12+rax*8+16], xmm9
  movsd qword ptr [v64], xmm1
  movsd qword ptr [v64], xmm9
  movss xmm0, xmm1
  movss xmm1, xmm0
  movss xmm8, xmm1
  movss xmm1, xmm8
  movss xmm15, xmm15
  movss xmm7, xmm7
  movss xmm3, xmm12
  movss xmm1, dword ptr [rbx]
  movss xmm1, dword ptr [r13+8]
  movss xmm1, dword ptr [r12+rax*8+16]
  movss xmm1, dword ptr [v64]
  movss xmm9, dword ptr [rbx]
  movss xmm9, dword ptr [r13+8]
  movss xmm9, dword ptr [r12+rax*8+16]
  movss xmm9, dword ptr [v64]
  addss xmm0, xmm1
  addss xmm1, xmm0
  addss xmm8, xmm1
  addss xmm1, xmm8
  addss xmm15, xmm15
  addss xmm7, xmm7
  addss xmm3, xmm12
  addss xmm1, dword ptr [rbx]
  addss xmm1, dword ptr [r13+8]
  addss xmm1, dword ptr [r12+rax*8+16]
  addss xmm1, dword ptr [v64]
  addss xmm9, dword ptr [rbx]
  addss xmm9, dword ptr [r13+8]
  addss xmm9, dword ptr [r12+rax*8+16]
  addss xmm9, dword ptr [v64]
  subss xmm0, xmm1
  subss xmm1, xmm0
  subss xmm8, xmm1
  subss xmm1, xmm8
  subss xmm15, xmm15
  subss xmm7, xmm7
  subss xmm3, xmm12
  subss xmm1, dword ptr [rbx]
  subss xmm1, dword ptr [r13+8]
  subss xmm1, dword ptr [r12+rax*8+16]
  subss xmm1, dword ptr [v64]
  subss xmm9, dword ptr [rbx]
  subss xmm9, dword ptr [r13+8]
  subss xmm9, dword ptr [r12+rax*8+16]
  subss xmm9, dword ptr [v64]
  mulss xmm0, xmm1
  mulss xmm1, xmm0
  mulss xmm8, xmm1
  mulss xmm1, xmm8
  mulss xmm15, xmm15
  mulss xmm7, xmm7
  mulss xmm3, xmm12
  mulss xmm1, dword ptr [rbx]
  mulss xmm1, dword ptr [r13+8]
  mulss xmm1, dword ptr [r12+rax*8+16]
  mulss xmm1, dword ptr [v64]
  mulss xmm9, dword ptr [rbx]
  mulss xmm9, dword ptr [r13+8]
  mulss xmm9, dword ptr [r12+rax*8+16]
  mulss xmm9, dword ptr [v64]
  divss xmm0, xmm1
  divss xmm1, xmm0
  divss xmm8, xmm1
  divss xmm1, xmm8
  divss xmm15, xmm15
  divss xmm7, xmm7
  divss xmm3, xmm12
  divss xmm1, dword ptr [rbx]
  divss xmm1, dword ptr [r13+8]
  divss xmm1, dword ptr [r12+rax*8+16]
  divss xmm1, dword ptr [v64]
  divss xmm9, dword ptr [rbx]
  divss xmm9, dword ptr [r13+8]
  divss xmm9, dword ptr [r12+rax*8+16]
  divss xmm9, dword ptr [v64]
  sqrtss xmm0, xmm1
  sqrtss xmm1, xmm0
  sqrtss xmm8, xmm1
  sqrtss xmm1, xmm8
  sqrtss xmm15, xmm15
  sqrtss xmm7, xmm7
  sqrtss xmm3, xmm12
  sqrtss xmm1, dword ptr [rbx]
  sqrtss xmm1, dword ptr [r13+8]
  sqrtss xmm1, dword ptr [r12+rax*8+16]
  sqrtss xmm1, dword ptr [v64]
  sqrtss xmm9, dword ptr [rbx]
  sqrtss xmm9, dword ptr [r13+8]
  sqrtss xmm9, dword ptr [r12+rax*8+16]
  sqrtss xmm9, dword ptr [v64]
  minss xmm0, xmm1
  minss xmm1, xmm0
  minss xmm8, xmm1
  minss xmm1, xmm8
  minss xmm15, xmm15
  minss xmm7, xmm7
  minss xmm3, xmm12
  minss xmm1, dword ptr [rbx]
  minss xmm1, dword ptr [r13+8]
  minss xmm1, dword ptr [r12+rax*8+16]
  minss xmm1, dword ptr [v64]
  minss xmm9, dword ptr [rbx]
  minss xmm9, dword ptr [r13+8]
  minss xmm9, dword ptr [r12+rax*8+16]
  minss xmm9, dword ptr [v64]
  maxss xmm0, xmm1
  maxss xmm1, xmm0
  maxss xmm8, xmm1
  maxss xmm1, xmm8
  maxss xmm15, xmm15
  maxss xmm7, xmm7
  maxss xmm3, xmm12
  maxss xmm1, dword ptr [rbx]
  maxss xmm1, dword ptr [r13+8]
  maxss xmm1, dword ptr [r12+rax*8+16]
  maxss xmm1, dword ptr [v64]
  maxss xmm9, dword ptr [rbx]
  maxss xmm9, dword ptr [r13+8]
  maxss xmm9, dword ptr [r12+rax*8+16]
  maxss xmm9, dword ptr [v64]
  ucomiss xmm0, xmm1
  ucomiss xmm1, xmm0
  ucomiss xmm8, xmm1
  ucomiss xmm1, xmm8
  ucomiss xmm15, xmm15
  ucomiss xmm7, xmm7
  ucomiss xmm3, xmm12
  ucomiss xmm1, dword ptr [rbx]
  ucomiss xmm1, dword ptr [r13+8]
  ucomiss xmm1, dword ptr [r12+rax*8+16]
  ucomiss xmm1, dword ptr [v64]
  ucomiss xmm9, dword ptr [rbx]
  ucomiss xmm9, dword ptr [r13+8]
  ucomiss xmm9, dword ptr [r12+rax*8+16]
  ucomiss xmm9, dword ptr [v64]
  comiss xmm0, xmm1
  comiss xmm1, xmm0
  comiss xmm8, xmm1
  comiss xmm1, xmm8
  comiss xmm15, xmm15
  comiss xmm7, xmm7
  comiss xmm3, xmm12
  comiss xmm1, dword ptr [rbx]
  comiss xmm1, dword ptr [r13+8]
  comiss xmm1, dword ptr [r12+rax*8+16]
  comiss xmm1, dword ptr [v64]
  comiss xmm9, dword ptr [rbx]
  comiss xmm9, dword ptr [r13+8]
  comiss xmm9, dword ptr [r12+rax*8+16]
  comiss xmm9, dword ptr [v64]
  cvtsd2ss xmm0, xmm1
  cvtsd2ss xmm1, xmm0
  cvtsd2ss xmm8, xmm1
  cvtsd2ss xmm1, xmm8
  cvtsd2ss xmm15, xmm15
  cvtsd2ss xmm7, xmm7
  cvtsd2ss xmm3, xmm12
  cvtsd2ss xmm1, qword ptr [rbx]
  cvtsd2ss xmm1, qword ptr [r13+8]
  cvtsd2ss xmm1, qword ptr [r12+rax*8+16]
  cvtsd2ss xmm1, qword ptr [v64]
  cvtsd2ss xmm9, qword ptr [rbx]
  cvtsd2ss xmm9, qword ptr [r13+8]
  cvtsd2ss xmm9, qword ptr [r12+rax*8+16]
  cvtsd2ss xmm9, qword ptr [v64]
  movss dword ptr [rbx], xmm1
  movss dword ptr [rbx], xmm9
  movss dword ptr [r13+8], xmm1
  movss dword ptr [r13+8], xmm9
  movss dword ptr [r12+rax*8+16], xmm1
  movss dword ptr [r12+rax*8+16], xmm9
  movss dword ptr [v64], xmm1
  movss dword ptr [v64], xmm9
  cvtsi2sd xmm0, eax
  cvtsi2sd xmm0, ecx
  cvtsi2sd xmm0, edx
  cvtsi2sd xmm0, ebx
  cvtsi2sd xmm0, esp
  cvtsi2sd xmm0, ebp
  cvtsi2sd xmm0, esi
  cvtsi2sd xmm0, edi
  cvtsi2sd xmm0, r8d
  cvtsi2sd xmm0, r9d
  cvtsi2sd xmm0, r10d
  cvtsi2sd xmm0, r11d
  cvtsi2sd xmm0, r12d
  cvtsi2sd xmm0, r13d
  cvtsi2sd xmm0, r14d
  cvtsi2sd xmm0, r15d
  cvtsi2sd xmm0, rax
  cvtsi2sd xmm0, rcx
  cvtsi2sd xmm0, rdx
  cvtsi2sd xmm0, rbx
  cvtsi2sd xmm0, rsp
  cvtsi2sd xmm0, rbp
  cvtsi2sd xmm0, rsi
  cvtsi2sd xmm0, rdi
  cvtsi2sd xmm0, r8
  cvtsi2sd xmm0, r9
  cvtsi2sd xmm0, r10
  cvtsi2sd xmm0, r11
  cvtsi2sd xmm0, r12
  cvtsi2sd xmm0, r13
  cvtsi2sd xmm0, r14
  cvtsi2sd xmm0, r15
  cvtsi2sd xmm1, eax
  cvtsi2sd xmm1, ecx
  cvtsi2sd xmm1, edx
  cvtsi2sd xmm1, ebx
  cvtsi2sd xmm1, esp
  cvtsi2sd xmm1, ebp
  cvtsi2sd xmm1, esi
  cvtsi2sd xmm1, edi
  cvtsi2sd xmm1, r8d
  cvtsi2sd xmm1, r9d
  cvtsi2sd xmm1, r10d
  cvtsi2sd xmm1, r11d
  cvtsi2sd xmm1, r12d
  cvtsi2sd xmm1, r13d
  cvtsi2sd xmm1, r14d
  cvtsi2sd xmm1, r15d
  cvtsi2sd xmm1, rax
  cvtsi2sd xmm1, rcx
  cvtsi2sd xmm1, rdx
  cvtsi2sd xmm1, rbx
  cvtsi2sd xmm1, rsp
  cvtsi2sd xmm1, rbp
  cvtsi2sd xmm1, rsi
  cvtsi2sd xmm1, rdi
  cvtsi2sd xmm1, r8
  cvtsi2sd xmm1, r9
  cvtsi2sd xmm1, r10
  cvtsi2sd xmm1, r11
  cvtsi2sd xmm1, r12
  cvtsi2sd xmm1, r13
  cvtsi2sd xmm1, r14
  cvtsi2sd xmm1, r15
  cvtsi2sd xmm8, eax
  cvtsi2sd xmm8, ecx
  cvtsi2sd xmm8, edx
  cvtsi2sd xmm8, ebx
  cvtsi2sd xmm8, esp
  cvtsi2sd xmm8, ebp
  cvtsi2sd xmm8, esi
  cvtsi2sd xmm8, edi
  cvtsi2sd xmm8, r8d
  cvtsi2sd xmm8, r9d
  cvtsi2sd xmm8, r10d
  cvtsi2sd xmm8, r11d
  cvtsi2sd xmm8, r12d
  cvtsi2sd xmm8, r13d
  cvtsi2sd xmm8, r14d
  cvtsi2sd xmm8, r15d
  cvtsi2sd xmm8, rax
  cvtsi2sd xmm8, rcx
  cvtsi2sd xmm8, rdx
  cvtsi2sd xmm8, rbx
  cvtsi2sd xmm8, rsp
  cvtsi2sd xmm8, rbp
  cvtsi2sd xmm8, rsi
  cvtsi2sd xmm8, rdi
  cvtsi2sd xmm8, r8
  cvtsi2sd xmm8, r9
  cvtsi2sd xmm8, r10
  cvtsi2sd xmm8, r11
  cvtsi2sd xmm8, r12
  cvtsi2sd xmm8, r13
  cvtsi2sd xmm8, r14
  cvtsi2sd xmm8, r15
  cvtsi2sd xmm15, eax
  cvtsi2sd xmm15, ecx
  cvtsi2sd xmm15, edx
  cvtsi2sd xmm15, ebx
  cvtsi2sd xmm15, esp
  cvtsi2sd xmm15, ebp
  cvtsi2sd xmm15, esi
  cvtsi2sd xmm15, edi
  cvtsi2sd xmm15, r8d
  cvtsi2sd xmm15, r9d
  cvtsi2sd xmm15, r10d
  cvtsi2sd xmm15, r11d
  cvtsi2sd xmm15, r12d
  cvtsi2sd xmm15, r13d
  cvtsi2sd xmm15, r14d
  cvtsi2sd xmm15, r15d
  cvtsi2sd xmm15, rax
  cvtsi2sd xmm15, rcx
  cvtsi2sd xmm15, rdx
  cvtsi2sd xmm15, rbx
  cvtsi2sd xmm15, rsp
  cvtsi2sd xmm15, rbp
  cvtsi2sd xmm15, rsi
  cvtsi2sd xmm15, rdi
  cvtsi2sd xmm15, r8
  cvtsi2sd xmm15, r9
  cvtsi2sd xmm15, r10
  cvtsi2sd xmm15, r11
  cvtsi2sd xmm15, r12
  cvtsi2sd xmm15, r13
  cvtsi2sd xmm15, r14
  cvtsi2sd xmm15, r15
  cvtsi2sd xmm1, dword ptr [rbx]
  cvtsi2sd xmm9, qword ptr [rbx]
  cvtsi2sd xmm1, dword ptr [r13+8]
  cvtsi2sd xmm9, qword ptr [r13+8]
  cvtsi2sd xmm1, dword ptr [r12+rax*8+16]
  cvtsi2sd xmm9, qword ptr [r12+rax*8+16]
  cvtsi2sd xmm1, dword ptr [v64]
  cvtsi2sd xmm9, qword ptr [v64]
  cvtsi2ss xmm0, eax
  cvtsi2ss xmm0, ecx
  cvtsi2ss xmm0, edx
  cvtsi2ss xmm0, ebx
  cvtsi2ss xmm0, esp
  cvtsi2ss xmm0, ebp
  cvtsi2ss xmm0, esi
  cvtsi2ss xmm0, edi
  cvtsi2ss xmm0, r8d
  cvtsi2ss xmm0, r9d
  cvtsi2ss xmm0, r10d
  cvtsi2ss xmm0, r11d
  cvtsi2ss xmm0, r12d
  cvtsi2ss xmm0, r13d
  cvtsi2ss xmm0, r14d
  cvtsi2ss xmm0, r15d
  cvtsi2ss xmm0, rax
  cvtsi2ss xmm0, rcx
  cvtsi2ss xmm0, rdx
  cvtsi2ss xmm0, rbx
  cvtsi2ss xmm0, rsp
  cvtsi2ss xmm0, rbp
  cvtsi2ss xmm0, rsi
  cvtsi2ss xmm0, rdi
  cvtsi2ss xmm0, r8
  cvtsi2ss xmm0, r9
  cvtsi2ss xmm0, r10
  cvtsi2ss xmm0, r11
  cvtsi2ss xmm0, r12
  cvtsi2ss xmm0, r13
  cvtsi2ss xmm0, r14
  cvtsi2ss xmm0, r15
  cvtsi2ss xmm1, eax
  cvtsi2ss xmm1, ecx
  cvtsi2ss xmm1, edx
  cvtsi2ss xmm1, ebx
  cvtsi2ss xmm1, esp
  cvtsi2ss xmm1, ebp
  cvtsi2ss xmm1, esi
  cvtsi2ss xmm1, edi
  cvtsi2ss xmm1, r8d
  cvtsi2ss xmm1, r9d
  cvtsi2ss xmm1, r10d
  cvtsi2ss xmm1, r11d
  cvtsi2ss xmm1, r12d
  cvtsi2ss xmm1, r13d
  cvtsi2ss xmm1, r14d
  cvtsi2ss xmm1, r15d
  cvtsi2ss xmm1, rax
  cvtsi2ss xmm1, rcx
  cvtsi2ss xmm1, rdx
  cvtsi2ss xmm1, rbx
  cvtsi2ss xmm1, rsp
  cvtsi2ss xmm1, rbp
  cvtsi2ss xmm1, rsi
  cvtsi2ss xmm1, rdi
  cvtsi2ss xmm1, r8
  cvtsi2ss xmm1, r9
  cvtsi2ss xmm1, r10
  cvtsi2ss xmm1, r11
  cvtsi2ss xmm1, r12
  cvtsi2ss xmm1, r13
  cvtsi2ss xmm1, r14
  cvtsi2ss xmm1, r15
  cvtsi2ss xmm8, eax
  cvtsi2ss xmm8, ecx
  cvtsi2ss xmm8, edx
  cvtsi2ss xmm8, ebx
  cvtsi2ss xmm8, esp
  cvtsi2ss xmm8, ebp
  cvtsi2ss xmm8, esi
  cvtsi2ss xmm8, edi
  cvtsi2ss xmm8, r8d
  cvtsi2ss xmm8, r9d
  cvtsi2ss xmm8, r10d
  cvtsi2ss xmm8, r11d
  cvtsi2ss xmm8, r12d
  cvtsi2ss xmm8, r13d
  cvtsi2ss xmm8, r14d
  cvtsi2ss xmm8, r15d
  cvtsi2ss xmm8, rax
  cvtsi2ss xmm8, rcx
  cvtsi2ss xmm8, rdx
  cvtsi2ss xmm8, rbx
  cvtsi2ss xmm8, rsp
  cvtsi2ss xmm8, rbp
  cvtsi2ss xmm8, rsi
  cvtsi2ss xmm8, rdi
  cvtsi2ss xmm8, r8
  cvtsi2ss xmm8, r9
  cvtsi2ss xmm8, r10
  cvtsi2ss xmm8, r11
  cvtsi2ss xmm8, r12
  cvtsi2ss xmm8, r13
  cvtsi2ss xmm8, r14
  cvtsi2ss xmm8, r15
  cvtsi2ss xmm15, eax
  cvtsi2ss xmm15, ecx
  cvtsi2ss xmm15, edx
  cvtsi2ss xmm15, ebx
  cvtsi2ss xmm15, esp
  cvtsi2ss xmm15, ebp
  cvtsi2ss xmm15, esi
  cvtsi2ss xmm15, edi
  cvtsi2ss xmm15, r8d
  cvtsi2ss xmm15, r9d
  cvtsi2ss xmm15, r10d
  cvtsi2ss xmm15, r11d
  cvtsi2ss xmm15, r12d
  cvtsi2ss xmm15, r13d
  cvtsi2ss xmm15, r14d
  cvtsi2ss xmm15, r15d
  cvtsi2ss xmm15, rax
  cvtsi2ss xmm15, rcx
  cvtsi2ss xmm15, rdx
  cvtsi2ss xmm15, rbx
  cvtsi2ss xmm15, rsp
  cvtsi2ss xmm15, rbp
  cvtsi2ss xmm15, rsi
  cvtsi2ss xmm15, rdi
  cvtsi2ss xmm15, r8
  cvtsi2ss xmm15, r9
  cvtsi2ss xmm15, r10
  cvtsi2ss xmm15, r11
  cvtsi2ss xmm15, r12
  cvtsi2ss xmm15, r13
  cvtsi2ss xmm15, r14
  cvtsi2ss xmm15, r15
  cvtsi2ss xmm1, dword ptr [rbx]
  cvtsi2ss xmm9, qword ptr [rbx]
  cvtsi2ss xmm1, dword ptr [r13+8]
  cvtsi2ss xmm9, qword ptr [r13+8]
  cvtsi2ss xmm1, dword ptr [r12+rax*8+16]
  cvtsi2ss xmm9, qword ptr [r12+rax*8+16]
  cvtsi2ss xmm1, dword ptr [v64]
  cvtsi2ss xmm9, qword ptr [v64]
  cvttsd2si eax, xmm0
  cvttsd2si ecx, xmm0
  cvttsd2si edx, xmm0
  cvttsd2si ebx, xmm0
  cvttsd2si esp, xmm0
  cvttsd2si ebp, xmm0
  cvttsd2si esi, xmm0
  cvttsd2si edi, xmm0
  cvttsd2si r8d, xmm0
  cvttsd2si r9d, xmm0
  cvttsd2si r10d, xmm0
  cvttsd2si r11d, xmm0
  cvttsd2si r12d, xmm0
  cvttsd2si r13d, xmm0
  cvttsd2si r14d, xmm0
  cvttsd2si r15d, xmm0
  cvttsd2si rax, xmm0
  cvttsd2si rcx, xmm0
  cvttsd2si rdx, xmm0
  cvttsd2si rbx, xmm0
  cvttsd2si rsp, xmm0
  cvttsd2si rbp, xmm0
  cvttsd2si rsi, xmm0
  cvttsd2si rdi, xmm0
  cvttsd2si r8, xmm0
  cvttsd2si r9, xmm0
  cvttsd2si r10, xmm0
  cvttsd2si r11, xmm0
  cvttsd2si r12, xmm0
  cvttsd2si r13, xmm0
  cvttsd2si r14, xmm0
  cvttsd2si r15, xmm0
  cvttsd2si eax, xmm1
  cvttsd2si ecx, xmm1
  cvttsd2si edx, xmm1
  cvttsd2si ebx, xmm1
  cvttsd2si esp, xmm1
  cvttsd2si ebp, xmm1
  cvttsd2si esi, xmm1
  cvttsd2si edi, xmm1
  cvttsd2si r8d, xmm1
  cvttsd2si r9d, xmm1
  cvttsd2si r10d, xmm1
  cvttsd2si r11d, xmm1
  cvttsd2si r12d, xmm1
  cvttsd2si r13d, xmm1
  cvttsd2si r14d, xmm1
  cvttsd2si r15d, xmm1
  cvttsd2si rax, xmm1
  cvttsd2si rcx, xmm1
  cvttsd2si rdx, xmm1
  cvttsd2si rbx, xmm1
  cvttsd2si rsp, xmm1
  cvttsd2si rbp, xmm1
  cvttsd2si rsi, xmm1
  cvttsd2si rdi, xmm1
  cvttsd2si r8, xmm1
  cvttsd2si r9, xmm1
  cvttsd2si r10, xmm1
  cvttsd2si r11, xmm1
  cvttsd2si r12, xmm1
  cvttsd2si r13, xmm1
  cvttsd2si r14, xmm1
  cvttsd2si r15, xmm1
  cvttsd2si eax, xmm8
  cvttsd2si ecx, xmm8
  cvttsd2si edx, xmm8
  cvttsd2si ebx, xmm8
  cvttsd2si esp, xmm8
  cvttsd2si ebp, xmm8
  cvttsd2si esi, xmm8
  cvttsd2si edi, xmm8
  cvttsd2si r8d, xmm8
  cvttsd2si r9d, xmm8
  cvttsd2si r10d, xmm8
  cvttsd2si r11d, xmm8
  cvttsd2si r12d, xmm8
  cvttsd2si r13d, xmm8
  cvttsd2si r14d, xmm8
  cvttsd2si r15d, xmm8
  cvttsd2si rax, xmm8
  cvttsd2si rcx, xmm8
  cvttsd2si rdx, xmm8
  cvttsd2si rbx, xmm8
  cvttsd2si rsp, xmm8
  cvttsd2si rbp, xmm8
  cvttsd2si rsi, xmm8
  cvttsd2si rdi, xmm8
  cvttsd2si r8, xmm8
  cvttsd2si r9, xmm8
  cvttsd2si r10, xmm8
  cvttsd2si r11, xmm8
  cvttsd2si r12, xmm8
  cvttsd2si r13, xmm8
  cvttsd2si r14, xmm8
  cvttsd2si r15, xmm8
  cvttsd2si eax, xmm15
  cvttsd2si ecx, xmm15
  cvttsd2si edx, xmm15
  cvttsd2si ebx, xmm15
  cvttsd2si esp, xmm15
  cvttsd2si ebp, xmm15
  cvttsd2si esi, xmm15
  cvttsd2si edi, xmm15
  cvttsd2si r8d, xmm15
  cvttsd2si r9d, xmm15
  cvttsd2si r10d, xmm15
  cvttsd2si r11d, xmm15
  cvttsd2si r12d, xmm15
  cvttsd2si r13d, xmm15
  cvttsd2si r14d, xmm15
  cvttsd2si r15d, xmm15
  cvttsd2si rax, xmm15
  cvttsd2si rcx, xmm15
  cvttsd2si rdx, xmm15
  cvttsd2si rbx, xmm15
  cvttsd2si rsp, xmm15
  cvttsd2si rbp, xmm15
  cvttsd2si rsi, xmm15
  cvttsd2si rdi, xmm15
  cvttsd2si r8, xmm15
  cvttsd2si r9, xmm15
  cvttsd2si r10, xmm15
  cvttsd2si r11, xmm15
  cvttsd2si r12, xmm15
  cvttsd2si r13, xmm15
  cvttsd2si r14, xmm15
  cvttsd2si r15, xmm15
  cvttsd2si eax, qword ptr [rbx]
  cvttsd2si r9, qword ptr [rbx]
  cvttsd2si eax, qword ptr [r13+8]
  cvttsd2si r9, qword ptr [r13+8]
  cvttsd2si eax, qword ptr [r12+rax*8+16]
  cvttsd2si r9, qword ptr [r12+rax*8+16]
  cvttsd2si eax, qword ptr [v64]
  cvttsd2si r9, qword ptr [v64]
  cvtsd2si eax, xmm0
  cvtsd2si ecx, xmm0
  cvtsd2si edx, xmm0
  cvtsd2si ebx, xmm0
  cvtsd2si esp, xmm0
  cvtsd2si ebp, xmm0
  cvtsd2si esi, xmm0
  cvtsd2si edi, xmm0
  cvtsd2si r8d, xmm0
  cvtsd2si r9d, xmm0
  cvtsd2si r10d, xmm0
  cvtsd2si r11d, xmm0
  cvtsd2si r12d, xmm0
  cvtsd2si r13d, xmm0
  cvtsd2si r14d, xmm0
  cvtsd2si r15d, xmm0
  cvtsd2si rax, xmm0
  cvtsd2si rcx, xmm0
  cvtsd2si rdx, xmm0
  cvtsd2si rbx, xmm0
  cvtsd2si rsp, xmm0
  cvtsd2si rbp, xmm0
  cvtsd2si rsi, xmm0
  cvtsd2si rdi, xmm0
  cvtsd2si r8, xmm0
  cvtsd2si r9, xmm0
  cvtsd2si r10, xmm0
  cvtsd2si r11, xmm0
  cvtsd2si r12, xmm0
  cvtsd2si r13, xmm0
  cvtsd2si r14, xmm0
  cvtsd2si r15, xmm0
  cvtsd2si eax, xmm1
  cvtsd2si ecx, xmm1
  cvtsd2si edx, xmm1
  cvtsd2si ebx, xmm1
  cvtsd2si esp, xmm1
  cvtsd2si ebp, xmm1
  cvtsd2si esi, xmm1
  cvtsd2si edi, xmm1
  cvtsd2si r8d, xmm1
  cvtsd2si r9d, xmm1
  cvtsd2si r10d, xmm1
  cvtsd2si r11d, xmm1
  cvtsd2si r12d, xmm1
  cvtsd2si r13d, xmm1
  cvtsd2si r14d, xmm1
  cvtsd2si r15d, xmm1
  cvtsd2si rax, xmm1
  cvtsd2si rcx, xmm1
  cvtsd2si rdx, xmm1
  cvtsd2si rbx, xmm1
  cvtsd2si rsp, xmm1
  cvtsd2si rbp, xmm1
  cvtsd2si rsi, xmm1
  cvtsd2si rdi, xmm1
  cvtsd2si r8, xmm1
  cvtsd2si r9, xmm1
  cvtsd2si r10, xmm1
  cvtsd2si r11, xmm1
  cvtsd2si r12, xmm1
  cvtsd2si r13, xmm1
  cvtsd2si r14, xmm1
  cvtsd2si r15, xmm1
  cvtsd2si eax, xmm8
  cvtsd2si ecx, xmm8
  cvtsd2si edx, xmm8
  cvtsd2si ebx, xmm8
  cvtsd2si esp, xmm8
  cvtsd2si ebp, xmm8
  cvtsd2si esi, xmm8
  cvtsd2si edi, xmm8
  cvtsd2si r8d, xmm8
  cvtsd2si r9d, xmm8
  cvtsd2si r10d, xmm8
  cvtsd2si r11d, xmm8
  cvtsd2si r12d, xmm8
  cvtsd2si r13d, xmm8
  cvtsd2si r14d, xmm8
  cvtsd2si r15d, xmm8
  cvtsd2si rax, xmm8
  cvtsd2si rcx, xmm8
  cvtsd2si rdx, xmm8
  cvtsd2si rbx, xmm8
  cvtsd2si rsp, xmm8
  cvtsd2si rbp, xmm8
  cvtsd2si rsi, xmm8
  cvtsd2si rdi, xmm8
  cvtsd2si r8, xmm8
  cvtsd2si r9, xmm8
  cvtsd2si r10, xmm8
  cvtsd2si r11, xmm8
  cvtsd2si r12, xmm8
  cvtsd2si r13, xmm8
  cvtsd2si r14, xmm8
  cvtsd2si r15, xmm8
  cvtsd2si eax, xmm15
  cvtsd2si ecx, xmm15
  cvtsd2si edx, xmm15
  cvtsd2si ebx, xmm15
  cvtsd2si esp, xmm15
  cvtsd2si ebp, xmm15
  cvtsd2si esi, xmm15
  cvtsd2si edi, xmm15
  cvtsd2si r8d, xmm15
  cvtsd2si r9d, xmm15
  cvtsd2si r10d, xmm15
  cvtsd2si r11d, xmm15
  cvtsd2si r12d, xmm15
  cvtsd2si r13d, xmm15
  cvtsd2si r14d, xmm15
  cvtsd2si r15d, xmm15
  cvtsd2si rax, xmm15
  cvtsd2si rcx, xmm15
  cvtsd2si rdx, xmm15
  cvtsd2si rbx, xmm15
  cvtsd2si rsp, xmm15
  cvtsd2si rbp, xmm15
  cvtsd2si rsi, xmm15
  cvtsd2si rdi, xmm15
  cvtsd2si r8, xmm15
  cvtsd2si r9, xmm15
  cvtsd2si r10, xmm15
  cvtsd2si r11, xmm15
  cvtsd2si r12, xmm15
  cvtsd2si r13, xmm15
  cvtsd2si r14, xmm15
  cvtsd2si r15, xmm15
  cvtsd2si eax, qword ptr [rbx]
  cvtsd2si r9, qword ptr [rbx]
  cvtsd2si eax, qword ptr [r13+8]
  cvtsd2si r9, qword ptr [r13+8]
  cvtsd2si eax, qword ptr [r12+rax*8+16]
  cvtsd2si r9, qword ptr [r12+rax*8+16]
  cvtsd2si eax, qword ptr [v64]
  cvtsd2si r9, qword ptr [v64]
  cvttss2si eax, xmm0
  cvttss2si ecx, xmm0
  cvttss2si edx, xmm0
  cvttss2si ebx, xmm0
  cvttss2si esp, xmm0
  cvttss2si ebp, xmm0
  cvttss2si esi, xmm0
  cvttss2si edi, xmm0
  cvttss2si r8d, xmm0
  cvttss2si r9d, xmm0
  cvttss2si r10d, xmm0
  cvttss2si r11d, xmm0
  cvttss2si r12d, xmm0
  cvttss2si r13d, xmm0
  cvttss2si r14d, xmm0
  cvttss2si r15d, xmm0
  cvttss2si rax, xmm0
  cvttss2si rcx, xmm0
  cvttss2si rdx, xmm0
  cvttss2si rbx, xmm0
  cvttss2si rsp, xmm0
  cvttss2si rbp, xmm0
  cvttss2si rsi, xmm0
  cvttss2si rdi, xmm0
  cvttss2si r8, xmm0
  cvttss2si r9, xmm0
  cvttss2si r10, xmm0
  cvttss2si r11, xmm0
  cvttss2si r12, xmm0
  cvttss2si r13, xmm0
  cvttss2si r14, xmm0
  cvttss2si r15, xmm0
  cvttss2si eax, xmm1
  cvttss2si ecx, xmm1
  cvttss2si edx, xmm1
  cvttss2si ebx, xmm1
  cvttss2si esp, xmm1
  cvttss2si ebp, xmm1
  cvttss2si esi, xmm1
  cvttss2si edi, xmm1
  cvttss2si r8d, xmm1
  cvttss2si r9d, xmm1
  cvttss2si r10d, xmm1
  cvttss2si r11d, xmm1
  cvttss2si r12d, xmm1
  cvttss2si r13d, xmm1
  cvttss2si r14d, xmm1
  cvttss2si r15d, xmm1
  cvttss2si rax, xmm1
  cvttss2si rcx, xmm1
  cvttss2si rdx, xmm1
  cvttss2si rbx, xmm1
  cvttss2si rsp, xmm1
  cvttss2si rbp, xmm1
  cvttss2si rsi, xmm1
  cvttss2si rdi, xmm1
  cvttss2si r8, xmm1
  cvttss2si r9, xmm1
  cvttss2si r10, xmm1
  cvttss2si r11, xmm1
  cvttss2si r12, xmm1
  cvttss2si r13, xmm1
  cvttss2si r14, xmm1
  cvttss2si r15, xmm1
  cvttss2si eax, xmm8
  cvttss2si ecx, xmm8
  cvttss2si edx, xmm8
  cvttss2si ebx, xmm8
  cvttss2si esp, xmm8
  cvttss2si ebp, xmm8
  cvttss2si esi, xmm8
  cvttss2si edi, xmm8
  cvttss2si r8d, xmm8
  cvttss2si r9d, xmm8
  cvttss2si r10d, xmm8
  cvttss2si r11d, xmm8
  cvttss2si r12d, xmm8
  cvttss2si r13d, xmm8
  cvttss2si r14d, xmm8
  cvttss2si r15d, xmm8
  cvttss2si rax, xmm8
  cvttss2si rcx, xmm8
  cvttss2si rdx, xmm8
  cvttss2si rbx, xmm8
  cvttss2si rsp, xmm8
  cvttss2si rbp, xmm8
  cvttss2si rsi, xmm8
  cvttss2si rdi, xmm8
  cvttss2si r8, xmm8
  cvttss2si r9, xmm8
  cvttss2si r10, xmm8
  cvttss2si r11, xmm8
  cvttss2si r12, xmm8
  cvttss2si r13, xmm8
  cvttss2si r14, xmm8
  cvttss2si r15, xmm8
  cvttss2si eax, xmm15
  cvttss2si ecx, xmm15
  cvttss2si edx, xmm15
  cvttss2si ebx, xmm15
  cvttss2si esp, xmm15
  cvttss2si ebp, xmm15
  cvttss2si esi, xmm15
  cvttss2si edi, xmm15
  cvttss2si r8d, xmm15
  cvttss2si r9d, xmm15
  cvttss2si r10d, xmm15
  cvttss2si r11d, xmm15
  cvttss2si r12d, xmm15
  cvttss2si r13d, xmm15
  cvttss2si r14d, xmm15
  cvttss2si r15d, xmm15
  cvttss2si rax, xmm15
  cvttss2si rcx, xmm15
  cvttss2si rdx, xmm15
  cvttss2si rbx, xmm15
  cvttss2si rsp, xmm15
  cvttss2si rbp, xmm15
  cvttss2si rsi, xmm15
  cvttss2si rdi, xmm15
  cvttss2si r8, xmm15
  cvttss2si r9, xmm15
  cvttss2si r10, xmm15
  cvttss2si r11, xmm15
  cvttss2si r12, xmm15
  cvttss2si r13, xmm15
  cvttss2si r14, xmm15
  cvttss2si r15, xmm15
  cvttss2si eax, dword ptr [rbx]
  cvttss2si r9, dword ptr [rbx]
  cvttss2si eax, dword ptr [r13+8]
  cvttss2si r9, dword ptr [r13+8]
  cvttss2si eax, dword ptr [r12+rax*8+16]
  cvttss2si r9, dword ptr [r12+rax*8+16]
  cvttss2si eax, dword ptr [v64]
  cvttss2si r9, dword ptr [v64]
  cvtss2si eax, xmm0
  cvtss2si ecx, xmm0
  cvtss2si edx, xmm0
  cvtss2si ebx, xmm0
  cvtss2si esp, xmm0
  cvtss2si ebp, xmm0
  cvtss2si esi, xmm0
  cvtss2si edi, xmm0
  cvtss2si r8d, xmm0
  cvtss2si r9d, xmm0
  cvtss2si r10d, xmm0
  cvtss2si r11d, xmm0
  cvtss2si r12d, xmm0
  cvtss2si r13d, xmm0
  cvtss2si r14d, xmm0
  cvtss2si r15d, xmm0
  cvtss2si rax, xmm0
  cvtss2si rcx, xmm0
  cvtss2si rdx, xmm0
  cvtss2si rbx, xmm0
  cvtss2si rsp, xmm0
  cvtss2si rbp, xmm0
  cvtss2si rsi, xmm0
  cvtss2si rdi, xmm0
  cvtss2si r8, xmm0
  cvtss2si r9, xmm0
  cvtss2si r10, xmm0
  cvtss2si r11, xmm0
  cvtss2si r12, xmm0
  cvtss2si r13, xmm0
  cvtss2si r14, xmm0
  cvtss2si r15, xmm0
  cvtss2si eax, xmm1
  cvtss2si ecx, xmm1
  cvtss2si edx, xmm1
  cvtss2si ebx, xmm1
  cvtss2si esp, xmm1
  cvtss2si ebp, xmm1
  cvtss2si esi, xmm1
  cvtss2si edi, xmm1
  cvtss2si r8d, xmm1
  cvtss2si r9d, xmm1
  cvtss2si r10d, xmm1
  cvtss2si r11d, xmm1
  cvtss2si r12d, xmm1
  cvtss2si r13d, xmm1
  cvtss2si r14d, xmm1
  cvtss2si r15d, xmm1
  cvtss2si rax, xmm1
  cvtss2si rcx, xmm1
  cvtss2si rdx, xmm1
  cvtss2si rbx, xmm1
  cvtss2si rsp, xmm1
  cvtss2si rbp, xmm1
  cvtss2si rsi, xmm1
  cvtss2si rdi, xmm1
  cvtss2si r8, xmm1
  cvtss2si r9, xmm1
  cvtss2si r10, xmm1
  cvtss2si r11, xmm1
  cvtss2si r12, xmm1
  cvtss2si r13, xmm1
  cvtss2si r14, xmm1
  cvtss2si r15, xmm1
  cvtss2si eax, xmm8
  cvtss2si ecx, xmm8
  cvtss2si edx, xmm8
  cvtss2si ebx, xmm8
  cvtss2si esp, xmm8
  cvtss2si ebp, xmm8
  cvtss2si esi, xmm8
  cvtss2si edi, xmm8
  cvtss2si r8d, xmm8
  cvtss2si r9d, xmm8
  cvtss2si r10d, xmm8
  cvtss2si r11d, xmm8
  cvtss2si r12d, xmm8
  cvtss2si r13d, xmm8
  cvtss2si r14d, xmm8
  cvtss2si r15d, xmm8
  cvtss2si rax, xmm8
  cvtss2si rcx, xmm8
  cvtss2si rdx, xmm8
  cvtss2si rbx, xmm8
  cvtss2si rsp, xmm8
  cvtss2si rbp, xmm8
  cvtss2si rsi, xmm8
  cvtss2si rdi, xmm8
  cvtss2si r8, xmm8
  cvtss2si r9, xmm8
  cvtss2si r10, xmm8
  cvtss2si r11, xmm8
  cvtss2si r12, xmm8
  cvtss2si r13, xmm8
  cvtss2si r14, xmm8
  cvtss2si r15, xmm8
  cvtss2si eax, xmm15
  cvtss2si ecx, xmm15
  cvtss2si edx, xmm15
  cvtss2si ebx, xmm15
  cvtss2si esp, xmm15
  cvtss2si ebp, xmm15
  cvtss2si esi, xmm15
  cvtss2si edi, xmm15
  cvtss2si r8d, xmm15
  cvtss2si r9d, xmm15
  cvtss2si r10d, xmm15
  cvtss2si r11d, xmm15
  cvtss2si r12d, xmm15
  cvtss2si r13d, xmm15
  cvtss2si r14d, xmm15
  cvtss2si r15d, xmm15
  cvtss2si rax, xmm15
  cvtss2si rcx, xmm15
  cvtss2si rdx, xmm15
  cvtss2si rbx, xmm15
  cvtss2si rsp, xmm15
  cvtss2si rbp, xmm15
  cvtss2si rsi, xmm15
  cvtss2si rdi, xmm15
  cvtss2si r8, xmm15
  cvtss2si r9, xmm15
  cvtss2si r10, xmm15
  cvtss2si r11, xmm15
  cvtss2si r12, xmm15
  cvtss2si r13, xmm15
  cvtss2si r14, xmm15
  cvtss2si r15, xmm15
  cvtss2si eax, dword ptr [rbx]
  cvtss2si r9, dword ptr [rbx]
  cvtss2si eax, dword ptr [r13+8]
  cvtss2si r9, dword ptr [r13+8]
  cvtss2si eax, dword ptr [r12+rax*8+16]
  cvtss2si r9, dword ptr [r12+rax*8+16]
  cvtss2si eax, dword ptr [v64]
  cvtss2si r9, dword ptr [v64]
  pxor xmm0, xmm1
  pxor xmm1, xmm0
  pxor xmm8, xmm1
  pxor xmm1, xmm8
  pxor xmm15, xmm15
  pxor xmm7, xmm7
  pxor xmm3, xmm12
  pxor xmm1, xmmword ptr [rbx]
  pxor xmm1, xmmword ptr [r13+8]
  pxor xmm1, xmmword ptr [r12+rax*8+16]
  pxor xmm1, xmmword ptr [v64]
  xorpd xmm0, xmm1
  xorpd xmm1, xmm0
  xorpd xmm8, xmm1
  xorpd xmm1, xmm8
  xorpd xmm15, xmm15
  xorpd xmm7, xmm7
  xorpd xmm3, xmm12
  xorpd xmm1, xmmword ptr [rbx]
  xorpd xmm1, xmmword ptr [r13+8]
  xorpd xmm1, xmmword ptr [r12+rax*8+16]
  xorpd xmm1, xmmword ptr [v64]
  xorps xmm0, xmm1
  xorps xmm1, xmm0
  xorps xmm8, xmm1
  xorps xmm1, xmm8
  xorps xmm15, xmm15
  xorps xmm7, xmm7
  xorps xmm3, xmm12
  xorps xmm1, xmmword ptr [rbx]
  xorps xmm1, xmmword ptr [r13+8]
  xorps xmm1, xmmword ptr [r12+rax*8+16]
  xorps xmm1, xmmword ptr [v64]
  andpd xmm0, xmm1
  andpd xmm1, xmm0
  andpd xmm8, xmm1
  andpd xmm1, xmm8
  andpd xmm15, xmm15
  andpd xmm7, xmm7
  andpd xmm3, xmm12
  andpd xmm1, xmmword ptr [rbx]
  andpd xmm1, xmmword ptr [r13+8]
  andpd xmm1, xmmword ptr [r12+rax*8+16]
  andpd xmm1, xmmword ptr [v64]
  andps xmm0, xmm1
  andps xmm1, xmm0
  andps xmm8, xmm1
  andps xmm1, xmm8
  andps xmm15, xmm15
  andps xmm7, xmm7
  andps xmm3, xmm12
  andps xmm1, xmmword ptr [rbx]
  andps xmm1, xmmword ptr [r13+8]
  andps xmm1, xmmword ptr [r12+rax*8+16]
  andps xmm1, xmmword ptr [v64]
  andnpd xmm0, xmm1
  andnpd xmm1, xmm0
  andnpd xmm8, xmm1
  andnpd xmm1, xmm8
  andnpd xmm15, xmm15
  andnpd xmm7, xmm7
  andnpd xmm3, xmm12
  andnpd xmm1, xmmword ptr [rbx]
  andnpd xmm1, xmmword ptr [r13+8]
  andnpd xmm1, xmmword ptr [r12+rax*8+16]
  andnpd xmm1, xmmword ptr [v64]
  andnps xmm0, xmm1
  andnps xmm1, xmm0
  andnps xmm8, xmm1
  andnps xmm1, xmm8
  andnps xmm15, xmm15
  andnps xmm7, xmm7
  andnps xmm3, xmm12
  andnps xmm1, xmmword ptr [rbx]
  andnps xmm1, xmmword ptr [r13+8]
  andnps xmm1, xmmword ptr [r12+rax*8+16]
  andnps xmm1, xmmword ptr [v64]
  orpd xmm0, xmm1
  orpd xmm1, xmm0
  orpd xmm8, xmm1
  orpd xmm1, xmm8
  orpd xmm15, xmm15
  orpd xmm7, xmm7
  orpd xmm3, xmm12
  orpd xmm1, xmmword ptr [rbx]
  orpd xmm1, xmmword ptr [r13+8]
  orpd xmm1, xmmword ptr [r12+rax*8+16]
  orpd xmm1, xmmword ptr [v64]
  orps xmm0, xmm1
  orps xmm1, xmm0
  orps xmm8, xmm1
  orps xmm1, xmm8
  orps xmm15, xmm15
  orps xmm7, xmm7
  orps xmm3, xmm12
  orps xmm1, xmmword ptr [rbx]
  orps xmm1, xmmword ptr [r13+8]
  orps xmm1, xmmword ptr [r12+rax*8+16]
  orps xmm1, xmmword ptr [v64]
  movapd xmm0, xmm1
  movapd xmm1, xmm0
  movapd xmm8, xmm1
  movapd xmm1, xmm8
  movapd xmm15, xmm15
  movapd xmm7, xmm7
  movapd xmm3, xmm12
  movapd xmm1, xmmword ptr [rbx]
  movapd xmm1, xmmword ptr [r13+8]
  movapd xmm1, xmmword ptr [r12+rax*8+16]
  movapd xmm1, xmmword ptr [v64]
  movaps xmm0, xmm1
  movaps xmm1, xmm0
  movaps xmm8, xmm1
  movaps xmm1, xmm8
  movaps xmm15, xmm15
  movaps xmm7, xmm7
  movaps xmm3, xmm12
  movaps xmm1, xmmword ptr [rbx]
  movaps xmm1, xmmword ptr [r13+8]
  movaps xmm1, xmmword ptr [r12+rax*8+16]
  movaps xmm1, xmmword ptr [v64]
  movupd xmm0, xmm1
  movupd xmm1, xmm0
  movupd xmm8, xmm1
  movupd xmm1, xmm8
  movupd xmm15, xmm15
  movupd xmm7, xmm7
  movupd xmm3, xmm12
  movupd xmm1, xmmword ptr [rbx]
  movupd xmm1, xmmword ptr [r13+8]
  movupd xmm1, xmmword ptr [r12+rax*8+16]
  movupd xmm1, xmmword ptr [v64]
  movups xmm0, xmm1
  movups xmm1, xmm0
  movups xmm8, xmm1
  movups xmm1, xmm8
  movups xmm15, xmm15
  movups xmm7, xmm7
  movups xmm3, xmm12
  movups xmm1, xmmword ptr [rbx]
  movups xmm1, xmmword ptr [r13+8]
  movups xmm1, xmmword ptr [r12+rax*8+16]
  movups xmm1, xmmword ptr [v64]
  paddq xmm0, xmm1
  paddq xmm1, xmm0
  paddq xmm8, xmm1
  paddq xmm1, xmm8
  paddq xmm15, xmm15
  paddq xmm7, xmm7
  paddq xmm3, xmm12
  paddq xmm1, xmmword ptr [rbx]
  paddq xmm1, xmmword ptr [r13+8]
  paddq xmm1, xmmword ptr [r12+rax*8+16]
  paddq xmm1, xmmword ptr [v64]
  psubq xmm0, xmm1
  psubq xmm1, xmm0
  psubq xmm8, xmm1
  psubq xmm1, xmm8
  psubq xmm15, xmm15
  psubq xmm7, xmm7
  psubq xmm3, xmm12
  psubq xmm1, xmmword ptr [rbx]
  psubq xmm1, xmmword ptr [r13+8]
  psubq xmm1, xmmword ptr [r12+rax*8+16]
  psubq xmm1, xmmword ptr [v64]
  pand xmm0, xmm1
  pand xmm1, xmm0
  pand xmm8, xmm1
  pand xmm1, xmm8
  pand xmm15, xmm15
  pand xmm7, xmm7
  pand xmm3, xmm12
  pand xmm1, xmmword ptr [rbx]
  pand xmm1, xmmword ptr [r13+8]
  pand xmm1, xmmword ptr [r12+rax*8+16]
  pand xmm1, xmmword ptr [v64]
  por xmm0, xmm1
  por xmm1, xmm0
  por xmm8, xmm1
  por xmm1, xmm8
  por xmm15, xmm15
  por xmm7, xmm7
  por xmm3, xmm12
  por xmm1, xmmword ptr [rbx]
  por xmm1, xmmword ptr [r13+8]
  por xmm1, xmmword ptr [r12+rax*8+16]
  por xmm1, xmmword ptr [v64]
  pandn xmm0, xmm1
  pandn xmm1, xmm0
  pandn xmm8, xmm1
  pandn xmm1, xmm8
  pandn xmm15, xmm15
  pandn xmm7, xmm7
  pandn xmm3, xmm12
  pandn xmm1, xmmword ptr [rbx]
  pandn xmm1, xmmword ptr [r13+8]
  pandn xmm1, xmmword ptr [r12+rax*8+16]
  pandn xmm1, xmmword ptr [v64]
  movapd xmmword ptr [rbx], xmm1
  movapd xmmword ptr [rbx], xmm9
  movapd xmmword ptr [r13+8], xmm1
  movapd xmmword ptr [r13+8], xmm9
  movapd xmmword ptr [r12+rax*8+16], xmm1
  movapd xmmword ptr [r12+rax*8+16], xmm9
  movapd xmmword ptr [v64], xmm1
  movapd xmmword ptr [v64], xmm9
  movaps xmmword ptr [rbx], xmm1
  movaps xmmword ptr [rbx], xmm9
  movaps xmmword ptr [r13+8], xmm1
  movaps xmmword ptr [r13+8], xmm9
  movaps xmmword ptr [r12+rax*8+16], xmm1
  movaps xmmword ptr [r12+rax*8+16], xmm9
  movaps xmmword ptr [v64], xmm1
  movaps xmmword ptr [v64], xmm9
  movupd xmmword ptr [rbx], xmm1
  movupd xmmword ptr [rbx], xmm9
  movupd xmmword ptr [r13+8], xmm1
  movupd xmmword ptr [r13+8], xmm9
  movupd xmmword ptr [r12+rax*8+16], xmm1
  movupd xmmword ptr [r12+rax*8+16], xmm9
  movupd xmmword ptr [v64], xmm1
  movupd xmmword ptr [v64], xmm9
  movups xmmword ptr [rbx], xmm1
  movups xmmword ptr [rbx], xmm9
  movups xmmword ptr [r13+8], xmm1
  movups xmmword ptr [r13+8], xmm9
  movups xmmword ptr [r12+rax*8+16], xmm1
  movups xmmword ptr [r12+rax*8+16], xmm9
  movups xmmword ptr [v64], xmm1
  movups xmmword ptr [v64], xmm9
  movq rax, xmm0
  movq xmm0, rax
  movq rcx, xmm0
  movq xmm0, rcx
  movq rdx, xmm0
  movq xmm0, rdx
  movq rbx, xmm0
  movq xmm0, rbx
  movq rsp, xmm0
  movq xmm0, rsp
  movq rbp, xmm0
  movq xmm0, rbp
  movq rsi, xmm0
  movq xmm0, rsi
  movq rdi, xmm0
  movq xmm0, rdi
  movq r8, xmm0
  movq xmm0, r8
  movq r9, xmm0
  movq xmm0, r9
  movq r10, xmm0
  movq xmm0, r10
  movq r11, xmm0
  movq xmm0, r11
  movq r12, xmm0
  movq xmm0, r12
  movq r13, xmm0
  movq xmm0, r13
  movq r14, xmm0
  movq xmm0, r14
  movq r15, xmm0
  movq xmm0, r15
  movd eax, xmm0
  movd xmm0, eax
  movd ecx, xmm0
  movd xmm0, ecx
  movd edx, xmm0
  movd xmm0, edx
  movd ebx, xmm0
  movd xmm0, ebx
  movd esp, xmm0
  movd xmm0, esp
  movd ebp, xmm0
  movd xmm0, ebp
  movd esi, xmm0
  movd xmm0, esi
  movd edi, xmm0
  movd xmm0, edi
  movd r8d, xmm0
  movd xmm0, r8d
  movd r9d, xmm0
  movd xmm0, r9d
  movd r10d, xmm0
  movd xmm0, r10d
  movd r11d, xmm0
  movd xmm0, r11d
  movd r12d, xmm0
  movd xmm0, r12d
  movd r13d, xmm0
  movd xmm0, r13d
  movd r14d, xmm0
  movd xmm0, r14d
  movd r15d, xmm0
  movd xmm0, r15d
  movq rax, xmm1
  movq xmm1, rax
  movq rcx, xmm1
  movq xmm1, rcx
  movq rdx, xmm1
  movq xmm1, rdx
  movq rbx, xmm1
  movq xmm1, rbx
  movq rsp, xmm1
  movq xmm1, rsp
  movq rbp, xmm1
  movq xmm1, rbp
  movq rsi, xmm1
  movq xmm1, rsi
  movq rdi, xmm1
  movq xmm1, rdi
  movq r8, xmm1
  movq xmm1, r8
  movq r9, xmm1
  movq xmm1, r9
  movq r10, xmm1
  movq xmm1, r10
  movq r11, xmm1
  movq xmm1, r11
  movq r12, xmm1
  movq xmm1, r12
  movq r13, xmm1
  movq xmm1, r13
  movq r14, xmm1
  movq xmm1, r14
  movq r15, xmm1
  movq xmm1, r15
  movd eax, xmm1
  movd xmm1, eax
  movd ecx, xmm1
  movd xmm1, ecx
  movd edx, xmm1
  movd xmm1, edx
  movd ebx, xmm1
  movd xmm1, ebx
  movd esp, xmm1
  movd xmm1, esp
  movd ebp, xmm1
  movd xmm1, ebp
  movd esi, xmm1
  movd xmm1, esi
  movd edi, xmm1
  movd xmm1, edi
  movd r8d, xmm1
  movd xmm1, r8d
  movd r9d, xmm1
  movd xmm1, r9d
  movd r10d, xmm1
  movd xmm1, r10d
  movd r11d, xmm1
  movd xmm1, r11d
  movd r12d, xmm1
  movd xmm1, r12d
  movd r13d, xmm1
  movd xmm1, r13d
  movd r14d, xmm1
  movd xmm1, r14d
  movd r15d, xmm1
  movd xmm1, r15d
  movq rax, xmm8
  movq xmm8, rax
  movq rcx, xmm8
  movq xmm8, rcx
  movq rdx, xmm8
  movq xmm8, rdx
  movq rbx, xmm8
  movq xmm8, rbx
  movq rsp, xmm8
  movq xmm8, rsp
  movq rbp, xmm8
  movq xmm8, rbp
  movq rsi, xmm8
  movq xmm8, rsi
  movq rdi, xmm8
  movq xmm8, rdi
  movq r8, xmm8
  movq xmm8, r8
  movq r9, xmm8
  movq xmm8, r9
  movq r10, xmm8
  movq xmm8, r10
  movq r11, xmm8
  movq xmm8, r11
  movq r12, xmm8
  movq xmm8, r12
  movq r13, xmm8
  movq xmm8, r13
  movq r14, xmm8
  movq xmm8, r14
  movq r15, xmm8
  movq xmm8, r15
  movd eax, xmm8
  movd xmm8, eax
  movd ecx, xmm8
  movd xmm8, ecx
  movd edx, xmm8
  movd xmm8, edx
  movd ebx, xmm8
  movd xmm8, ebx
  movd esp, xmm8
  movd xmm8, esp
  movd ebp, xmm8
  movd xmm8, ebp
  movd esi, xmm8
  movd xmm8, esi
  movd edi, xmm8
  movd xmm8, edi
  movd r8d, xmm8
  movd xmm8, r8d
  movd r9d, xmm8
  movd xmm8, r9d
  movd r10d, xmm8
  movd xmm8, r10d
  movd r11d, xmm8
  movd xmm8, r11d
  movd r12d, xmm8
  movd xmm8, r12d
  movd r13d, xmm8
  movd xmm8, r13d
  movd r14d, xmm8
  movd xmm8, r14d
  movd r15d, xmm8
  movd xmm8, r15d
  movq rax, xmm15
  movq xmm15, rax
  movq rcx, xmm15
  movq xmm15, rcx
  movq rdx, xmm15
  movq xmm15, rdx
  movq rbx, xmm15
  movq xmm15, rbx
  movq rsp, xmm15
  movq xmm15, rsp
  movq rbp, xmm15
  movq xmm15, rbp
  movq rsi, xmm15
  movq xmm15, rsi
  movq rdi, xmm15
  movq xmm15, rdi
  movq r8, xmm15
  movq xmm15, r8
  movq r9, xmm15
  movq xmm15, r9
  movq r10, xmm15
  movq xmm15, r10
  movq r11, xmm15
  movq xmm15, r11
  movq r12, xmm15
  movq xmm15, r12
  movq r13, xmm15
  movq xmm15, r13
  movq r14, xmm15
  movq xmm15, r14
  movq r15, xmm15
  movq xmm15, r15
  movd eax, xmm15
  movd xmm15, eax
  movd ecx, xmm15
  movd xmm15, ecx
  movd edx, xmm15
  movd xmm15, edx
  movd ebx, xmm15
  movd xmm15, ebx
  movd esp, xmm15
  movd xmm15, esp
  movd ebp, xmm15
  movd xmm15, ebp
  movd esi, xmm15
  movd xmm15, esi
  movd edi, xmm15
  movd xmm15, edi
  movd r8d, xmm15
  movd xmm15, r8d
  movd r9d, xmm15
  movd xmm15, r9d
  movd r10d, xmm15
  movd xmm15, r10d
  movd r11d, xmm15
  movd xmm15, r11d
  movd r12d, xmm15
  movd xmm15, r12d
  movd r13d, xmm15
  movd xmm15, r13d
  movd r14d, xmm15
  movd xmm15, r14d
  movd r15d, xmm15
  movd xmm15, r15d
  movq xmm0, xmm1
  movq xmm1, xmm0
  movq xmm8, xmm1
  movq xmm1, xmm8
  movq xmm15, xmm15
  movq xmm7, xmm7
  movq xmm3, xmm12
  movq xmm1, qword ptr [rbx]
  movq qword ptr [rbx], xmm9
  movd xmm1, dword ptr [rbx]
  movd dword ptr [rbx], xmm9
  movq xmm1, qword ptr [r13+8]
  movq qword ptr [r13+8], xmm9
  movd xmm1, dword ptr [r13+8]
  movd dword ptr [r13+8], xmm9
  movq xmm1, qword ptr [r12+rax*8+16]
  movq qword ptr [r12+rax*8+16], xmm9
  movd xmm1, dword ptr [r12+rax*8+16]
  movd dword ptr [r12+rax*8+16], xmm9
  movq xmm1, qword ptr [v64]
  movq qword ptr [v64], xmm9
  movd xmm1, dword ptr [v64]
  movd dword ptr [v64], xmm9
f ENDP
END
