; a17-misc - generated by gen.py, ml64 is the oracle
.DATA
v8 DB 0
v16 DW 0
v32 DD 0
v64 DQ 0
.CODE
f PROC
  shl al, cl
  shl al, 1
  shl al, 5
  shl ah, cl
  shl ah, 1
  shl ah, 5
  shl sil, cl
  shl sil, 1
  shl sil, 5
  shl r9b, cl
  shl r9b, 1
  shl r9b, 5
  shl ax, cl
  shl ax, 1
  shl ax, 5
  shl r10w, cl
  shl r10w, 1
  shl r10w, 5
  shl eax, cl
  shl eax, 1
  shl eax, 5
  shl r11d, cl
  shl r11d, 1
  shl r11d, 5
  shl rax, cl
  shl rax, 1
  shl rax, 5
  shl r12, cl
  shl r12, 1
  shl r12, 5
  shl byte ptr [rbx], cl
  shl byte ptr [rbx], 1
  shl byte ptr [r13+8], 7
  shl byte ptr [v64], 1
  shl byte ptr [v64], 3
  shl word ptr [rbx], cl
  shl word ptr [rbx], 1
  shl word ptr [r13+8], 7
  shl word ptr [v64], 1
  shl word ptr [v64], 3
  shl dword ptr [rbx], cl
  shl dword ptr [rbx], 1
  shl dword ptr [r13+8], 7
  shl dword ptr [v64], 1
  shl dword ptr [v64], 3
  shl qword ptr [rbx], cl
  shl qword ptr [rbx], 1
  shl qword ptr [r13+8], 7
  shl qword ptr [v64], 1
  shl qword ptr [v64], 3
  sal al, cl
  sal al, 1
  sal al, 5
  sal ah, cl
  sal ah, 1
  sal ah, 5
  sal sil, cl
  sal sil, 1
  sal sil, 5
  sal r9b, cl
  sal r9b, 1
  sal r9b, 5
  sal ax, cl
  sal ax, 1
  sal ax, 5
  sal r10w, cl
  sal r10w, 1
  sal r10w, 5
  sal eax, cl
  sal eax, 1
  sal eax, 5
  sal r11d, cl
  sal r11d, 1
  sal r11d, 5
  sal rax, cl
  sal rax, 1
  sal rax, 5
  sal r12, cl
  sal r12, 1
  sal r12, 5
  sal byte ptr [rbx], cl
  sal byte ptr [rbx], 1
  sal byte ptr [r13+8], 7
  sal byte ptr [v64], 1
  sal byte ptr [v64], 3
  sal word ptr [rbx], cl
  sal word ptr [rbx], 1
  sal word ptr [r13+8], 7
  sal word ptr [v64], 1
  sal word ptr [v64], 3
  sal dword ptr [rbx], cl
  sal dword ptr [rbx], 1
  sal dword ptr [r13+8], 7
  sal dword ptr [v64], 1
  sal dword ptr [v64], 3
  sal qword ptr [rbx], cl
  sal qword ptr [rbx], 1
  sal qword ptr [r13+8], 7
  sal qword ptr [v64], 1
  sal qword ptr [v64], 3
  shr al, cl
  shr al, 1
  shr al, 5
  shr ah, cl
  shr ah, 1
  shr ah, 5
  shr sil, cl
  shr sil, 1
  shr sil, 5
  shr r9b, cl
  shr r9b, 1
  shr r9b, 5
  shr ax, cl
  shr ax, 1
  shr ax, 5
  shr r10w, cl
  shr r10w, 1
  shr r10w, 5
  shr eax, cl
  shr eax, 1
  shr eax, 5
  shr r11d, cl
  shr r11d, 1
  shr r11d, 5
  shr rax, cl
  shr rax, 1
  shr rax, 5
  shr r12, cl
  shr r12, 1
  shr r12, 5
  shr byte ptr [rbx], cl
  shr byte ptr [rbx], 1
  shr byte ptr [r13+8], 7
  shr byte ptr [v64], 1
  shr byte ptr [v64], 3
  shr word ptr [rbx], cl
  shr word ptr [rbx], 1
  shr word ptr [r13+8], 7
  shr word ptr [v64], 1
  shr word ptr [v64], 3
  shr dword ptr [rbx], cl
  shr dword ptr [rbx], 1
  shr dword ptr [r13+8], 7
  shr dword ptr [v64], 1
  shr dword ptr [v64], 3
  shr qword ptr [rbx], cl
  shr qword ptr [rbx], 1
  shr qword ptr [r13+8], 7
  shr qword ptr [v64], 1
  shr qword ptr [v64], 3
  sar al, cl
  sar al, 1
  sar al, 5
  sar ah, cl
  sar ah, 1
  sar ah, 5
  sar sil, cl
  sar sil, 1
  sar sil, 5
  sar r9b, cl
  sar r9b, 1
  sar r9b, 5
  sar ax, cl
  sar ax, 1
  sar ax, 5
  sar r10w, cl
  sar r10w, 1
  sar r10w, 5
  sar eax, cl
  sar eax, 1
  sar eax, 5
  sar r11d, cl
  sar r11d, 1
  sar r11d, 5
  sar rax, cl
  sar rax, 1
  sar rax, 5
  sar r12, cl
  sar r12, 1
  sar r12, 5
  sar byte ptr [rbx], cl
  sar byte ptr [rbx], 1
  sar byte ptr [r13+8], 7
  sar byte ptr [v64], 1
  sar byte ptr [v64], 3
  sar word ptr [rbx], cl
  sar word ptr [rbx], 1
  sar word ptr [r13+8], 7
  sar word ptr [v64], 1
  sar word ptr [v64], 3
  sar dword ptr [rbx], cl
  sar dword ptr [rbx], 1
  sar dword ptr [r13+8], 7
  sar dword ptr [v64], 1
  sar dword ptr [v64], 3
  sar qword ptr [rbx], cl
  sar qword ptr [rbx], 1
  sar qword ptr [r13+8], 7
  sar qword ptr [v64], 1
  sar qword ptr [v64], 3
  rol al, cl
  rol al, 1
  rol al, 5
  rol ah, cl
  rol ah, 1
  rol ah, 5
  rol sil, cl
  rol sil, 1
  rol sil, 5
  rol r9b, cl
  rol r9b, 1
  rol r9b, 5
  rol ax, cl
  rol ax, 1
  rol ax, 5
  rol r10w, cl
  rol r10w, 1
  rol r10w, 5
  rol eax, cl
  rol eax, 1
  rol eax, 5
  rol r11d, cl
  rol r11d, 1
  rol r11d, 5
  rol rax, cl
  rol rax, 1
  rol rax, 5
  rol r12, cl
  rol r12, 1
  rol r12, 5
  rol byte ptr [rbx], cl
  rol byte ptr [rbx], 1
  rol byte ptr [r13+8], 7
  rol byte ptr [v64], 1
  rol byte ptr [v64], 3
  rol word ptr [rbx], cl
  rol word ptr [rbx], 1
  rol word ptr [r13+8], 7
  rol word ptr [v64], 1
  rol word ptr [v64], 3
  rol dword ptr [rbx], cl
  rol dword ptr [rbx], 1
  rol dword ptr [r13+8], 7
  rol dword ptr [v64], 1
  rol dword ptr [v64], 3
  rol qword ptr [rbx], cl
  rol qword ptr [rbx], 1
  rol qword ptr [r13+8], 7
  rol qword ptr [v64], 1
  rol qword ptr [v64], 3
  ror al, cl
  ror al, 1
  ror al, 5
  ror ah, cl
  ror ah, 1
  ror ah, 5
  ror sil, cl
  ror sil, 1
  ror sil, 5
  ror r9b, cl
  ror r9b, 1
  ror r9b, 5
  ror ax, cl
  ror ax, 1
  ror ax, 5
  ror r10w, cl
  ror r10w, 1
  ror r10w, 5
  ror eax, cl
  ror eax, 1
  ror eax, 5
  ror r11d, cl
  ror r11d, 1
  ror r11d, 5
  ror rax, cl
  ror rax, 1
  ror rax, 5
  ror r12, cl
  ror r12, 1
  ror r12, 5
  ror byte ptr [rbx], cl
  ror byte ptr [rbx], 1
  ror byte ptr [r13+8], 7
  ror byte ptr [v64], 1
  ror byte ptr [v64], 3
  ror word ptr [rbx], cl
  ror word ptr [rbx], 1
  ror word ptr [r13+8], 7
  ror word ptr [v64], 1
  ror word ptr [v64], 3
  ror dword ptr [rbx], cl
  ror dword ptr [rbx], 1
  ror dword ptr [r13+8], 7
  ror dword ptr [v64], 1
  ror dword ptr [v64], 3
  ror qword ptr [rbx], cl
  ror qword ptr [rbx], 1
  ror qword ptr [r13+8], 7
  ror qword ptr [v64], 1
  ror qword ptr [v64], 3
  rcl al, cl
  rcl al, 1
  rcl al, 5
  rcl ah, cl
  rcl ah, 1
  rcl ah, 5
  rcl sil, cl
  rcl sil, 1
  rcl sil, 5
  rcl r9b, cl
  rcl r9b, 1
  rcl r9b, 5
  rcl ax, cl
  rcl ax, 1
  rcl ax, 5
  rcl r10w, cl
  rcl r10w, 1
  rcl r10w, 5
  rcl eax, cl
  rcl eax, 1
  rcl eax, 5
  rcl r11d, cl
  rcl r11d, 1
  rcl r11d, 5
  rcl rax, cl
  rcl rax, 1
  rcl rax, 5
  rcl r12, cl
  rcl r12, 1
  rcl r12, 5
  rcl byte ptr [rbx], cl
  rcl byte ptr [rbx], 1
  rcl byte ptr [r13+8], 7
  rcl byte ptr [v64], 1
  rcl byte ptr [v64], 3
  rcl word ptr [rbx], cl
  rcl word ptr [rbx], 1
  rcl word ptr [r13+8], 7
  rcl word ptr [v64], 1
  rcl word ptr [v64], 3
  rcl dword ptr [rbx], cl
  rcl dword ptr [rbx], 1
  rcl dword ptr [r13+8], 7
  rcl dword ptr [v64], 1
  rcl dword ptr [v64], 3
  rcl qword ptr [rbx], cl
  rcl qword ptr [rbx], 1
  rcl qword ptr [r13+8], 7
  rcl qword ptr [v64], 1
  rcl qword ptr [v64], 3
  rcr al, cl
  rcr al, 1
  rcr al, 5
  rcr ah, cl
  rcr ah, 1
  rcr ah, 5
  rcr sil, cl
  rcr sil, 1
  rcr sil, 5
  rcr r9b, cl
  rcr r9b, 1
  rcr r9b, 5
  rcr ax, cl
  rcr ax, 1
  rcr ax, 5
  rcr r10w, cl
  rcr r10w, 1
  rcr r10w, 5
  rcr eax, cl
  rcr eax, 1
  rcr eax, 5
  rcr r11d, cl
  rcr r11d, 1
  rcr r11d, 5
  rcr rax, cl
  rcr rax, 1
  rcr rax, 5
  rcr r12, cl
  rcr r12, 1
  rcr r12, 5
  rcr byte ptr [rbx], cl
  rcr byte ptr [rbx], 1
  rcr byte ptr [r13+8], 7
  rcr byte ptr [v64], 1
  rcr byte ptr [v64], 3
  rcr word ptr [rbx], cl
  rcr word ptr [rbx], 1
  rcr word ptr [r13+8], 7
  rcr word ptr [v64], 1
  rcr word ptr [v64], 3
  rcr dword ptr [rbx], cl
  rcr dword ptr [rbx], 1
  rcr dword ptr [r13+8], 7
  rcr dword ptr [v64], 1
  rcr dword ptr [v64], 3
  rcr qword ptr [rbx], cl
  rcr qword ptr [rbx], 1
  rcr qword ptr [r13+8], 7
  rcr qword ptr [v64], 1
  rcr qword ptr [v64], 3
  not al
  not ah
  not sil
  not r9b
  not ax
  not r10w
  not eax
  not r11d
  not rax
  not r12
  not byte ptr [rbx]
  not byte ptr [v64]
  not word ptr [rbx]
  not word ptr [v64]
  not dword ptr [rbx]
  not dword ptr [v64]
  not qword ptr [rbx]
  not qword ptr [v64]
  neg al
  neg ah
  neg sil
  neg r9b
  neg ax
  neg r10w
  neg eax
  neg r11d
  neg rax
  neg r12
  neg byte ptr [rbx]
  neg byte ptr [v64]
  neg word ptr [rbx]
  neg word ptr [v64]
  neg dword ptr [rbx]
  neg dword ptr [v64]
  neg qword ptr [rbx]
  neg qword ptr [v64]
  mul al
  mul ah
  mul sil
  mul r9b
  mul ax
  mul r10w
  mul eax
  mul r11d
  mul rax
  mul r12
  mul byte ptr [rbx]
  mul byte ptr [v64]
  mul word ptr [rbx]
  mul word ptr [v64]
  mul dword ptr [rbx]
  mul dword ptr [v64]
  mul qword ptr [rbx]
  mul qword ptr [v64]
  imul al
  imul ah
  imul sil
  imul r9b
  imul ax
  imul r10w
  imul eax
  imul r11d
  imul rax
  imul r12
  imul byte ptr [rbx]
  imul byte ptr [v64]
  imul word ptr [rbx]
  imul word ptr [v64]
  imul dword ptr [rbx]
  imul dword ptr [v64]
  imul qword ptr [rbx]
  imul qword ptr [v64]
  div al
  div ah
  div sil
  div r9b
  div ax
  div r10w
  div eax
  div r11d
  div rax
  div r12
  div byte ptr [rbx]
  div byte ptr [v64]
  div word ptr [rbx]
  div word ptr [v64]
  div dword ptr [rbx]
  div dword ptr [v64]
  div qword ptr [rbx]
  div qword ptr [v64]
  idiv al
  idiv ah
  idiv sil
  idiv r9b
  idiv ax
  idiv r10w
  idiv eax
  idiv r11d
  idiv rax
  idiv r12
  idiv byte ptr [rbx]
  idiv byte ptr [v64]
  idiv word ptr [rbx]
  idiv word ptr [v64]
  idiv dword ptr [rbx]
  idiv dword ptr [v64]
  idiv qword ptr [rbx]
  idiv qword ptr [v64]
  inc al
  inc ah
  inc sil
  inc r9b
  inc ax
  inc r10w
  inc eax
  inc r11d
  inc rax
  inc r12
  inc byte ptr [rbx]
  inc byte ptr [v64]
  inc word ptr [rbx]
  inc word ptr [v64]
  inc dword ptr [rbx]
  inc dword ptr [v64]
  inc qword ptr [rbx]
  inc qword ptr [v64]
  dec al
  dec ah
  dec sil
  dec r9b
  dec ax
  dec r10w
  dec eax
  dec r11d
  dec rax
  dec r12
  dec byte ptr [rbx]
  dec byte ptr [v64]
  dec word ptr [rbx]
  dec word ptr [v64]
  dec dword ptr [rbx]
  dec dword ptr [v64]
  dec qword ptr [rbx]
  dec qword ptr [v64]
  imul eax, 1
  imul eax, ecx, 1
  imul eax, 5
  imul eax, ecx, 5
  imul eax, -1
  imul eax, ecx, -1
  imul eax, 127
  imul eax, ecx, 127
  imul eax, 128
  imul eax, ecx, 128
  imul eax, -128
  imul eax, ecx, -128
  imul eax, -129
  imul eax, ecx, -129
  imul eax, 1000
  imul eax, ecx, 1000
  imul eax, 32767
  imul eax, ecx, 32767
  imul eax, dword ptr [rbx], 7
  imul eax, dword ptr [rbx], 1000
  imul rax, 1
  imul rax, rcx, 1
  imul rax, 5
  imul rax, rcx, 5
  imul rax, -1
  imul rax, rcx, -1
  imul rax, 127
  imul rax, rcx, 127
  imul rax, 128
  imul rax, rcx, 128
  imul rax, -128
  imul rax, rcx, -128
  imul rax, -129
  imul rax, rcx, -129
  imul rax, 1000
  imul rax, rcx, 1000
  imul rax, 32767
  imul rax, rcx, 32767
  imul rax, qword ptr [rbx], 7
  imul rax, qword ptr [rbx], 1000
  imul r9, 1
  imul r9, r10, 1
  imul r9, 5
  imul r9, r10, 5
  imul r9, -1
  imul r9, r10, -1
  imul r9, 127
  imul r9, r10, 127
  imul r9, 128
  imul r9, r10, 128
  imul r9, -128
  imul r9, r10, -128
  imul r9, -129
  imul r9, r10, -129
  imul r9, 1000
  imul r9, r10, 1000
  imul r9, 32767
  imul r9, r10, 32767
  imul r9, qword ptr [rbx], 7
  imul r9, qword ptr [rbx], 1000
  imul ax, 1
  imul ax, cx, 1
  imul ax, 5
  imul ax, cx, 5
  imul ax, -1
  imul ax, cx, -1
  imul ax, 127
  imul ax, cx, 127
  imul ax, 128
  imul ax, cx, 128
  imul ax, -128
  imul ax, cx, -128
  imul ax, -129
  imul ax, cx, -129
  imul ax, 1000
  imul ax, cx, 1000
  imul ax, 32767
  imul ax, cx, 32767
  imul ax, word ptr [rbx], 7
  imul ax, word ptr [rbx], 1000
  imul r9d, 1
  imul r9d, eax, 1
  imul r9d, 5
  imul r9d, eax, 5
  imul r9d, -1
  imul r9d, eax, -1
  imul r9d, 127
  imul r9d, eax, 127
  imul r9d, 128
  imul r9d, eax, 128
  imul r9d, -128
  imul r9d, eax, -128
  imul r9d, -129
  imul r9d, eax, -129
  imul r9d, 1000
  imul r9d, eax, 1000
  imul r9d, 32767
  imul r9d, eax, 32767
  imul r9d, dword ptr [rbx], 7
  imul r9d, dword ptr [rbx], 1000
  imul ax, cx
  imul r9w, word ptr [rbx]
  int 3
  int 29h
  int 0
  int 255
  ret 0
  ret 8
  ret 65535
  cld
  std
  movsb
  movsw
  movsd
  movsq
  stosb
  stosw
  stosd
  stosq
  lodsb
  lodsq
  scasb
  cmpsb
  rep movsb
  rep movsq
  rep stosb
  rep stosq
  repe cmpsb
  repne scasb
  cwde
  cwd
  cbw
  pause
  hlt
  ud2
  cmc
  clc
  stc
  syscall
  cpuid
  rdtsc
  mfence
  lfence
  sfence
  push ax
  pop ax
  push r9w
  push word ptr [rbx]
  pop word ptr [rbx]
  pushfq
  popfq
  cmove eax, ecx
f ENDP
END
