; a18-xchg-bt-align - generated by gen.py, ml64 is the oracle
.DATA
v8 DB 0
v16 DW 0
v32 DD 0
v64 DQ 0
.CODE
f PROC
  xchg rax, rcx
  xchg rcx, rax
  xchg rax, r8
  xchg r8, rax
  xchg rcx, rdx
  xchg r9, r10
  xchg eax, ecx
  xchg ecx, eax
  xchg ecx, edx
  xchg ax, cx
  xchg cx, ax
  xchg cx, dx
  xchg al, cl
  xchg cl, al
  xchg cl, dl
  xchg sil, r9b
  xchg qword ptr [rbx], rax
  xchg rax, qword ptr [rbx]
  cmpxchg qword ptr [rbx], rax
  lock cmpxchg qword ptr [rbx], rax
  xadd qword ptr [rbx], rax
  lock xadd qword ptr [rbx], rax
  cmpxchg qword ptr [r13+8], rax
  cmpxchg qword ptr [v64], rax
  lock add qword ptr [rbx], rax
  lock inc qword ptr [rbx]
  lock xchg qword ptr [rbx], rax
  xchg qword ptr [rbx], rcx
  xchg rcx, qword ptr [rbx]
  cmpxchg qword ptr [rbx], rcx
  lock cmpxchg qword ptr [rbx], rcx
  xadd qword ptr [rbx], rcx
  lock xadd qword ptr [rbx], rcx
  cmpxchg qword ptr [r13+8], rcx
  cmpxchg qword ptr [v64], rcx
  lock add qword ptr [rbx], rcx
  lock inc qword ptr [rbx]
  lock xchg qword ptr [rbx], rcx
  xchg dword ptr [rbx], ecx
  xchg ecx, dword ptr [rbx]
  cmpxchg dword ptr [rbx], ecx
  lock cmpxchg dword ptr [rbx], ecx
  xadd dword ptr [rbx], ecx
  lock xadd dword ptr [rbx], ecx
  cmpxchg dword ptr [r13+8], ecx
  cmpxchg dword ptr [v64], ecx
  lock add dword ptr [rbx], ecx
  lock inc dword ptr [rbx]
  lock xchg dword ptr [rbx], ecx
  xchg word ptr [rbx], cx
  xchg cx, word ptr [rbx]
  cmpxchg word ptr [rbx], cx
  lock cmpxchg word ptr [rbx], cx
  xadd word ptr [rbx], cx
  lock xadd word ptr [rbx], cx
  cmpxchg word ptr [r13+8], cx
  cmpxchg word ptr [v64], cx
  lock add word ptr [rbx], cx
  lock inc word ptr [rbx]
  lock xchg word ptr [rbx], cx
  xchg byte ptr [rbx], cl
  xchg cl, byte ptr [rbx]
  cmpxchg byte ptr [rbx], cl
  lock cmpxchg byte ptr [rbx], cl
  xadd byte ptr [rbx], cl
  lock xadd byte ptr [rbx], cl
  cmpxchg byte ptr [r13+8], cl
  cmpxchg byte ptr [v64], cl
  lock add byte ptr [rbx], cl
  lock inc byte ptr [rbx]
  lock xchg byte ptr [rbx], cl
  cmpxchg rax, rcx
  xadd rax, rcx
  cmpxchg r9, r10
  xadd r9, r10
  cmpxchg eax, ecx
  xadd eax, ecx
  cmpxchg ax, cx
  xadd ax, cx
  bt rax, rcx
  bt rax, 3
  bt rax, 63
  bt r9, r10
  bt r9, 3
  bt r9, 63
  bt eax, ecx
  bt eax, 3
  bt eax, 63
  bt ax, cx
  bt ax, 3
  bt ax, 63
  bt qword ptr [rbx], rax
  bt qword ptr [rbx], 5
  bt qword ptr [v64], 5
  bt dword ptr [rbx], ecx
  bt dword ptr [rbx], 5
  bt dword ptr [v64], 5
  bt word ptr [rbx], cx
  bt word ptr [rbx], 5
  bt word ptr [v64], 5
  bts rax, rcx
  bts rax, 3
  bts rax, 63
  bts r9, r10
  bts r9, 3
  bts r9, 63
  bts eax, ecx
  bts eax, 3
  bts eax, 63
  bts ax, cx
  bts ax, 3
  bts ax, 63
  bts qword ptr [rbx], rax
  bts qword ptr [rbx], 5
  bts qword ptr [v64], 5
  bts dword ptr [rbx], ecx
  bts dword ptr [rbx], 5
  bts dword ptr [v64], 5
  bts word ptr [rbx], cx
  bts word ptr [rbx], 5
  bts word ptr [v64], 5
  btr rax, rcx
  btr rax, 3
  btr rax, 63
  btr r9, r10
  btr r9, 3
  btr r9, 63
  btr eax, ecx
  btr eax, 3
  btr eax, 63
  btr ax, cx
  btr ax, 3
  btr ax, 63
  btr qword ptr [rbx], rax
  btr qword ptr [rbx], 5
  btr qword ptr [v64], 5
  btr dword ptr [rbx], ecx
  btr dword ptr [rbx], 5
  btr dword ptr [v64], 5
  btr word ptr [rbx], cx
  btr word ptr [rbx], 5
  btr word ptr [v64], 5
  btc rax, rcx
  btc rax, 3
  btc rax, 63
  btc r9, r10
  btc r9, 3
  btc r9, 63
  btc eax, ecx
  btc eax, 3
  btc eax, 63
  btc ax, cx
  btc ax, 3
  btc ax, 63
  btc qword ptr [rbx], rax
  btc qword ptr [rbx], 5
  btc qword ptr [v64], 5
  btc dword ptr [rbx], ecx
  btc dword ptr [rbx], 5
  btc dword ptr [v64], 5
  btc word ptr [rbx], cx
  btc word ptr [rbx], 5
  btc word ptr [v64], 5
  bsr rax, rcx
  bsr r9, r10
  bsr eax, ecx
  bsr ax, cx
  bsr rax, qword ptr [rbx]
  bsr rax, qword ptr [v64]
  bsr ecx, dword ptr [rbx]
  bsr ecx, dword ptr [v64]
  bsr cx, word ptr [rbx]
  bsr cx, word ptr [v64]
  bsf rax, rcx
  bsf r9, r10
  bsf eax, ecx
  bsf ax, cx
  bsf rax, qword ptr [rbx]
  bsf rax, qword ptr [v64]
  bsf ecx, dword ptr [rbx]
  bsf ecx, dword ptr [v64]
  bsf cx, word ptr [rbx]
  bsf cx, word ptr [v64]
  popcnt rax, rcx
  popcnt r9, r10
  popcnt eax, ecx
  popcnt ax, cx
  popcnt rax, qword ptr [rbx]
  popcnt rax, qword ptr [v64]
  popcnt ecx, dword ptr [rbx]
  popcnt ecx, dword ptr [v64]
  popcnt cx, word ptr [rbx]
  popcnt cx, word ptr [v64]
  lzcnt rax, rcx
  lzcnt r9, r10
  lzcnt eax, ecx
  lzcnt ax, cx
  lzcnt rax, qword ptr [rbx]
  lzcnt rax, qword ptr [v64]
  lzcnt ecx, dword ptr [rbx]
  lzcnt ecx, dword ptr [v64]
  lzcnt cx, word ptr [rbx]
  lzcnt cx, word ptr [v64]
  tzcnt rax, rcx
  tzcnt r9, r10
  tzcnt eax, ecx
  tzcnt ax, cx
  tzcnt rax, qword ptr [rbx]
  tzcnt rax, qword ptr [v64]
  tzcnt ecx, dword ptr [rbx]
  tzcnt ecx, dword ptr [v64]
  tzcnt cx, word ptr [rbx]
  tzcnt cx, word ptr [v64]
f ENDP
g1 PROC
  ret
  ALIGN 16
  ret
g1 ENDP
g2 PROC
  ret
  ret
  ALIGN 16
  ret
g2 ENDP
g3 PROC
  ret
  ret
  ret
  ALIGN 16
  ret
g3 ENDP
g4 PROC
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g4 ENDP
g5 PROC
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g5 ENDP
g6 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g6 ENDP
g7 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g7 ENDP
g8 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g8 ENDP
g9 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g9 ENDP
g10 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g10 ENDP
g11 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g11 ENDP
g12 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g12 ENDP
g13 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g13 ENDP
g14 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g14 ENDP
g15 PROC
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ret
  ALIGN 16
  ret
g15 ENDP
h PROC
  ret
  ALIGN 2
  ret
  ALIGN 4
  ret
  ALIGN 8
  ret
h ENDP
END
