; a19-maybe - generated by gen.py, ml64 is the oracle
.DATA
v8 DB 0
v16 DW 0
v32 DD 0
v64 DQ 0
.CODE
f PROC
  test al, byte ptr [rbx]
  test byte ptr [rbx], al
  test rax, qword ptr [rbx]
  test eax, dword ptr [v32]
  movzx ax, ah
  cvtsi2sd xmm0, dword ptr [rbx]
  cvtsi2sd xmm0, qword ptr [rbx]
  movsd xmm0, v64
  movss xmm0, v32
  movsd v64, xmm0
  ucomisd xmm0, v64
  addsd xmm0, v64
  movq xmm0, v64
  movq v64, xmm0
  movd xmm0, v32
  pxor xmm0, [rbx]
  movapd xmm0, [rbx]
  movapd [rbx], xmm0
  movdqa xmm0, xmm1
  movdqu xmm0, xmmword ptr [rbx]
  movdqu xmmword ptr [rbx], xmm0
  cvttsd2si eax, v64
  cvtsi2sd xmm0, v32
  cvtsi2sd xmm0, v64
  shl v64, 1
  shl v64, cl
  shl v64, 3
  inc v64
  neg v32
  not v8
  imul rax, v64
  imul rax, v64, 5
  cmpxchg v64, rax
  xadd v32, eax
  bt v64, 3
  bsr rax, v64
  movzx eax, v8
  movsx rax, v16
  movsxd rax, v32
  sete v8
  cmove rax, v64
  mov rax, v64
  mov eax, v32
  mov ax, v16
  mov al, v8
  mov v8, al
  mov v8, 1
  add v32, 1
  cmp v64, 0
  cmp v16, 1000
  mov rax, offset v64
  mov r9, offset f
  lea rax, v64
  lea rax, [v64+8]
  mov rax, [v64+8]
  mov eax, dword ptr v32[4]
  mov eax, dword ptr [v32][4]
  mov rax, qword ptr [v64+rcx*8]
  mov rax, qword ptr [rcx*8+v64]
  mov rax, qword ptr v64[rcx*8]
  mov rax, qword ptr [rbx+v64]
  lea rax, [v64+rcx]
  mov rax, [rax+rsp]
  mov rax, [rsp+rax]
  mov rax, 8[rbx]
  mov rax, [rbx][8]
  mov rax, [rbx][rcx]
  mov rax, [rbx][rcx*4]
  mov rax, [rbx+rcx*1]
  mov rax, [rcx*1]
  mov rax, [rcx*1+8]
  jmp near ptr f
  call near ptr f
  call qword ptr [v64]
  call v64
  jmp v64
  call qword ptr v64
  jmp qword ptr [rbx+rcx*8]
  mov rax, [f]
  mov rax, qword ptr [f]
  mov rax, f
  lea rax, f
  lea rax, [f]
  mov rax, qword ptr f
  mov rax, 0FFFFFFFFh
  mov rax, 4294967295
  mov rax, -1
  mov rax, 0FFFFFFFFFFFFFFFFh
  mov rax, 18446744073709551615
  mov rax, 18446744073709551608
  mov rax, 2147483648
  mov rax, 80000000h
  mov rax, 100000000h
  mov rax, 0000000080000000h
  mov rax, 00000000000000000000000000000001h
  mov rcx, 000000001h
  mov rcx, 0000000001h
  mov rcx, 4294967296
  mov rcx, 04294967296
  mov rax, 1 shl 33
  mov eax, 7 mod 3
  mov eax, 7 and 3
  mov eax, 7 or 8
  mov eax, not 0
  mov eax, 6 xor 3
  mov eax, 256 shr 4
  mov eax, +5
  mov eax, - -5
  mov eax, low 1234h
  mov eax, high 1234h
  mov eax, 10o
  mov eax, 10q
  mov eax, 1010b
  mov eax, 10y
  mov eax, 10t
  mov eax, 10d
  mov eax, 'a'
  mov eax, 'ab'
  mov eax, "ab"
  mov rax, 'abcdefgh'
  mov eax, 1 eq 1
  mov eax, 1 lt 2
  mov eax, 3 gt 2
  mov eax, 1 ne 1
  mov eax, 0 le 0
  mov eax, 0 ge 1
f ENDP
END
