; Generated by cxx1 for x86_64-windows, in MASM syntax for ml64.
; The instruction selection is the same one the Linux backend makes;
; only the spelling is Microsoft's. See src/backend/Masm.cpp.

OPTION DOTNAME
OPTION NOSCOPED
OPTION PROC:PRIVATE

PUBLIC ??0E@@QEAA@AEBU0@@Z
PUBLIC ??0E@@QEAA@H@Z
PUBLIC ??1E@@QEAA@XZ
PUBLIC main
EXTERN _CxxThrowException:PROC
EXTERN __CxxFrameHandler3:PROC
EXTERN printf:PROC


EXTRN ??_7type_info@@6B@:QWORD
.data$r SEGMENT ALIGN(16) 'DATA'
??_R0H@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.H', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA'
_CT??_R0H@84 DD 01H
  DD imagerel ??_R0H@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 4
  DD 00H
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA'
_CTA1H DD 1
  DD imagerel _CT??_R0H@84
_TI1H DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA1H
.xdata$x ENDS
.data$r SEGMENT ALIGN(16) 'DATA'
??_R0?AUE@@@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.?AUE@@', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA'
_CT??_R0?AUE@@@8??0E@@QEAA@AEBU0@@Z4 DD 00H
  DD imagerel ??_R0?AUE@@@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 4
  DD imagerel ??0E@@QEAA@AEBU0@@Z
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA'
_CTA1?AUE@@ DD 1
  DD imagerel _CT??_R0?AUE@@@8??0E@@QEAA@AEBU0@@Z4
_TI1?AUE@@ DD 00H
  DD imagerel ??1E@@QEAA@XZ
  DD 00H
  DD imagerel _CTA1?AUE@@
.xdata$x ENDS

.CONST
$_L_str_0 DB 37, 100, 32, 37, 100, 32, 37, 100, 32, 37, 100, 32, 37, 103, 10, 0
$_L_str_1 DB 37, 100, 32, 37, 100, 32, 37, 100, 32, 37, 100, 32, 37, 100, 32, 37
  DB 100, 10, 0
$_L_str_2 DB 108, 105, 118, 101, 32, 37, 100, 10, 0

.DATA?
  ALIGN 4
live DB 4 DUP (?)

.CODE
??0E@@QEAA@H@Z PROC
$LNbeg$??0E@@QEAA@H@Z:
  push rbp
$LNpush$??0E@@QEAA@H@Z:
  sub rsp, 16
$LNalloc$??0E@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0E@@QEAA@H@Z:
$LNprolog$??0E@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp], rax
  mov rax, rdx
  mov DWORD PTR [rbp+12], eax
  lea rax, [rbp+12]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [live]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  mov rax, 0
$_L_return_??0E@@QEAA@H@Z:
  mov rax, [rbp]
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??0E@@QEAA@H@Z:
??0E@@QEAA@H@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??0E@@QEAA@H@Z DD imagerel $LNbeg$??0E@@QEAA@H@Z
  DD imagerel $LNend$??0E@@QEAA@H@Z
  DD imagerel $unwind$??0E@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??0E@@QEAA@H@Z DB 01H
  DB $LNprolog$??0E@@QEAA@H@Z-$LNbeg$??0E@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0E@@QEAA@H@Z-$LNbeg$??0E@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0E@@QEAA@H@Z-$LNbeg$??0E@@QEAA@H@Z
  DB 012H
  DB $LNpush$??0E@@QEAA@H@Z-$LNbeg$??0E@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
??0E@@QEAA@AEBU0@@Z PROC
$LNbeg$??0E@@QEAA@AEBU0@@Z:
  push rbp
$LNpush$??0E@@QEAA@AEBU0@@Z:
  sub rsp, 16
$LNalloc$??0E@@QEAA@AEBU0@@Z:
  mov rbp, rsp
$LNfp$??0E@@QEAA@AEBU0@@Z:
$LNprolog$??0E@@QEAA@AEBU0@@Z:
  mov rax, rcx
  mov QWORD PTR [rbp], rax
  mov rax, rdx
  mov QWORD PTR [rbp+8], rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  movsxd rax, eax
  push rax
  lea rax, [rbp]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [live]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  mov rax, 0
$_L_return_??0E@@QEAA@AEBU0@@Z:
  mov rax, [rbp]
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??0E@@QEAA@AEBU0@@Z:
??0E@@QEAA@AEBU0@@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??0E@@QEAA@AEBU0@@Z DD imagerel $LNbeg$??0E@@QEAA@AEBU0@@Z
  DD imagerel $LNend$??0E@@QEAA@AEBU0@@Z
  DD imagerel $unwind$??0E@@QEAA@AEBU0@@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??0E@@QEAA@AEBU0@@Z DB 01H
  DB $LNprolog$??0E@@QEAA@AEBU0@@Z-$LNbeg$??0E@@QEAA@AEBU0@@Z
  DB 3
  DB 05H
  DB $LNfp$??0E@@QEAA@AEBU0@@Z-$LNbeg$??0E@@QEAA@AEBU0@@Z
  DB 03H
  DB $LNalloc$??0E@@QEAA@AEBU0@@Z-$LNbeg$??0E@@QEAA@AEBU0@@Z
  DB 012H
  DB $LNpush$??0E@@QEAA@AEBU0@@Z-$LNbeg$??0E@@QEAA@AEBU0@@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
??1E@@QEAA@XZ PROC
$LNbeg$??1E@@QEAA@XZ:
  push rbp
$LNpush$??1E@@QEAA@XZ:
  sub rsp, 16
$LNalloc$??1E@@QEAA@XZ:
  mov rbp, rsp
$LNfp$??1E@@QEAA@XZ:
$LNprolog$??1E@@QEAA@XZ:
  mov rax, rcx
  mov QWORD PTR [rbp+8], rax
  lea rax, [live]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  sub rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  mov rax, 0
$_L_return_??1E@@QEAA@XZ:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??1E@@QEAA@XZ:
??1E@@QEAA@XZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??1E@@QEAA@XZ DD imagerel $LNbeg$??1E@@QEAA@XZ
  DD imagerel $LNend$??1E@@QEAA@XZ
  DD imagerel $unwind$??1E@@QEAA@XZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??1E@@QEAA@XZ DB 01H
  DB $LNprolog$??1E@@QEAA@XZ-$LNbeg$??1E@@QEAA@XZ
  DB 3
  DB 05H
  DB $LNfp$??1E@@QEAA@XZ-$LNbeg$??1E@@QEAA@XZ
  DB 03H
  DB $LNalloc$??1E@@QEAA@XZ-$LNbeg$??1E@@QEAA@XZ
  DB 012H
  DB $LNpush$??1E@@QEAA@XZ-$LNbeg$??1E@@QEAA@XZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
?boom@@YAXH@Z PROC
$LNbeg$?boom@@YAXH@Z:
  push rbp
$LNpush$?boom@@YAXH@Z:
  sub rsp, 48
$LNalloc$?boom@@YAXH@Z:
  mov rbp, rsp
$LNfp$?boom@@YAXH@Z:
$LNprolog$?boom@@YAXH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+44], eax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+40]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+40]
  push rax
  lea rax, [_TI1H]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
  mov rax, 0
$_L_return_?boom@@YAXH@Z:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$?boom@@YAXH@Z:
?boom@@YAXH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?boom@@YAXH@Z DD imagerel $LNbeg$?boom@@YAXH@Z
  DD imagerel $LNend$?boom@@YAXH@Z
  DD imagerel $unwind$?boom@@YAXH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?boom@@YAXH@Z DB 01H
  DB $LNprolog$?boom@@YAXH@Z-$LNbeg$?boom@@YAXH@Z
  DB 3
  DB 05H
  DB $LNfp$?boom@@YAXH@Z-$LNbeg$?boom@@YAXH@Z
  DB 03H
  DB $LNalloc$?boom@@YAXH@Z-$LNbeg$?boom@@YAXH@Z
  DB 052H
  DB $LNpush$?boom@@YAXH@Z-$LNbeg$?boom@@YAXH@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?boomE@@YAXH@Z PROC
$LNbeg$?boomE@@YAXH@Z:
  push rbp
$LNpush$?boomE@@YAXH@Z:
  sub rsp, 48
$LNalloc$?boomE@@YAXH@Z:
  mov rbp, rsp
$LNfp$?boomE@@YAXH@Z:
$LNprolog$?boomE@@YAXH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+44], eax
  mov rax, 0
  push rax
  lea rax, [rbp+36]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+32]
  push rax
  sub rsp, 8
  lea rax, [rbp+40]
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ??0E@@QEAA@H@Z
  add rsp, 40
  mov rax, 1
  push rax
  lea rax, [rbp+36]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+40]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0E@@QEAA@AEBU0@@Z
  lea rax, [rbp+36]
  movsxd rax, DWORD PTR [rax]
  cmp rax, 0
  je $_L_?boomE@@YAXH@Z_end_0
  lea rax, [rbp+40]
  push rax
  pop rcx
  mov rax, 0
  call ??1E@@QEAA@XZ
  mov rax, 0
  push rax
  lea rax, [rbp+36]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?boomE@@YAXH@Z_end_0:
  lea rax, [rbp+32]
  push rax
  lea rax, [_TI1?AUE@@]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
  mov rax, 0
$_L_return_?boomE@@YAXH@Z:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$?boomE@@YAXH@Z:
?boomE@@YAXH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?boomE@@YAXH@Z DD imagerel $LNbeg$?boomE@@YAXH@Z
  DD imagerel $LNend$?boomE@@YAXH@Z
  DD imagerel $unwind$?boomE@@YAXH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?boomE@@YAXH@Z DB 01H
  DB $LNprolog$?boomE@@YAXH@Z-$LNbeg$?boomE@@YAXH@Z
  DB 3
  DB 05H
  DB $LNfp$?boomE@@YAXH@Z-$LNbeg$?boomE@@YAXH@Z
  DB 03H
  DB $LNalloc$?boomE@@YAXH@Z-$LNbeg$?boomE@@YAXH@Z
  DB 052H
  DB $LNpush$?boomE@@YAXH@Z-$LNbeg$?boomE@@YAXH@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?retInt@@YAHH@Z PROC
$LNbeg$?retInt@@YAHH@Z:
  push rbp
$LNpush$?retInt@@YAHH@Z:
  sub rsp, 80
$LNalloc$?retInt@@YAHH@Z:
  mov rbp, rsp
$LNfp$?retInt@@YAHH@Z:
$LNprolog$?retInt@@YAHH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+76], eax
  mov QWORD PTR [rbp+40], -2
$_L_?retInt@@YAHH@Z_try_0:
  lea rax, [rbp+76]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
  nop
$_L_?retInt@@YAHH@Z_tryend_0:
$_L_?retInt@@YAHH@Z_caught_0:
  jmp $_L_?retInt@@YAHH@Z_user_$msskip5
$_L_?retInt@@YAHH@Z_user_$msret4:
  lea rax, [rbp+52]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?retInt@@YAHH@Z
$_L_?retInt@@YAHH@Z_user_$msskip5:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?retInt@@YAHH@Z
  mov rax, 0
$_L_return_?retInt@@YAHH@Z:
  lea rsp, [rbp+80]
  pop rbp
  ret
$LNend$?retInt@@YAHH@Z:
?retInt@@YAHH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retInt@@YAHH@Z DD imagerel $LNbeg$?retInt@@YAHH@Z
  DD imagerel $LNend$?retInt@@YAHH@Z
  DD imagerel $unwind$?retInt@@YAHH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retInt@@YAHH@Z DB 019H
  DB $LNprolog$?retInt@@YAHH@Z-$LNbeg$?retInt@@YAHH@Z
  DB 3
  DB 05H
  DB $LNfp$?retInt@@YAHH@Z-$LNbeg$?retInt@@YAHH@Z
  DB 03H
  DB $LNalloc$?retInt@@YAHH@Z-$LNbeg$?retInt@@YAHH@Z
  DB 092H
  DB $LNpush$?retInt@@YAHH@Z-$LNbeg$?retInt@@YAHH@Z
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retInt@@YAHH@Z
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?retInt@@YAHH@Z$catch$0 PROC
$LNbeg$?retInt@@YAHH@Z$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?retInt@@YAHH@Z$catch$0:
  sub rsp, 32
$LNprolog$?retInt@@YAHH@Z$catch$0:
  mov rbp, rdx
  mov rax, 10
  push rax
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul eax, r10d
  movsxd rax, eax
  push rax
  lea rax, [rbp+52]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?retInt@@YAHH@Z_user_$msret4]
  jmp $LNleave$?retInt@@YAHH@Z$catch$0
  lea rax, $_L_?retInt@@YAHH@Z_caught_0
$LNleave$?retInt@@YAHH@Z$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?retInt@@YAHH@Z$catch$0:
?retInt@@YAHH@Z$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retInt@@YAHH@Z$catch$0 DB 019H
  DB $LNprolog$?retInt@@YAHH@Z$catch$0-$LNbeg$?retInt@@YAHH@Z$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?retInt@@YAHH@Z$catch$0-$LNbeg$?retInt@@YAHH@Z$catch$0
  DB 032H
  DB $LNpush$?retInt@@YAHH@Z$catch$0-$LNbeg$?retInt@@YAHH@Z$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retInt@@YAHH@Z
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?retInt@@YAHH@Z DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?retInt@@YAHH@Z
  DD 1
  DD imagerel $tryMap$?retInt@@YAHH@Z
  DD 4
  DD imagerel $ip2state$?retInt@@YAHH@Z
  DD 40
  DD 00H
  DD 01H
$stateUnwindMap$?retInt@@YAHH@Z DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?retInt@@YAHH@Z DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?retInt@@YAHH@Z
$handlerMap$0$?retInt@@YAHH@Z DD 0
  DD imagerel ??_R0H@8
  DD 56
  DD imagerel ?retInt@@YAHH@Z$catch$0
  DD 56
$ip2state$?retInt@@YAHH@Z DD imagerel $LNbeg$?retInt@@YAHH@Z
  DD 0ffffffffH
  DD imagerel $_L_?retInt@@YAHH@Z_try_0
  DD 0
  DD imagerel $_L_?retInt@@YAHH@Z_tryend_0
  DD 0ffffffffH
  DD imagerel ?retInt@@YAHH@Z$catch$0
  DD 1
.xdata ENDS

.CODE
?retVal@@YAHH@Z PROC
$LNbeg$?retVal@@YAHH@Z:
  push rbp
$LNpush$?retVal@@YAHH@Z:
  sub rsp, 80
$LNalloc$?retVal@@YAHH@Z:
  mov rbp, rsp
$LNfp$?retVal@@YAHH@Z:
$LNprolog$?retVal@@YAHH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+76], eax
  mov QWORD PTR [rbp+40], -2
$_L_?retVal@@YAHH@Z_try_0:
  lea rax, [rbp+76]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?boomE@@YAXH@Z
  nop
$_L_?retVal@@YAHH@Z_tryend_0:
$_L_?retVal@@YAHH@Z_caught_0:
  jmp $_L_?retVal@@YAHH@Z_user_$msskip9
$_L_?retVal@@YAHH@Z_user_$msret8:
  lea rax, [rbp+52]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?retVal@@YAHH@Z
$_L_?retVal@@YAHH@Z_user_$msskip9:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?retVal@@YAHH@Z
  mov rax, 0
$_L_return_?retVal@@YAHH@Z:
  lea rsp, [rbp+80]
  pop rbp
  ret
$LNend$?retVal@@YAHH@Z:
?retVal@@YAHH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retVal@@YAHH@Z DD imagerel $LNbeg$?retVal@@YAHH@Z
  DD imagerel $LNend$?retVal@@YAHH@Z
  DD imagerel $unwind$?retVal@@YAHH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retVal@@YAHH@Z DB 019H
  DB $LNprolog$?retVal@@YAHH@Z-$LNbeg$?retVal@@YAHH@Z
  DB 3
  DB 05H
  DB $LNfp$?retVal@@YAHH@Z-$LNbeg$?retVal@@YAHH@Z
  DB 03H
  DB $LNalloc$?retVal@@YAHH@Z-$LNbeg$?retVal@@YAHH@Z
  DB 092H
  DB $LNpush$?retVal@@YAHH@Z-$LNbeg$?retVal@@YAHH@Z
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retVal@@YAHH@Z
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?retVal@@YAHH@Z$catch$0 PROC
$LNbeg$?retVal@@YAHH@Z$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?retVal@@YAHH@Z$catch$0:
  sub rsp, 32
$LNprolog$?retVal@@YAHH@Z$catch$0:
  mov rbp, rdx
  mov rax, 1
  push rax
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  pop r10
  add eax, r10d
  movsxd rax, eax
  push rax
  lea rax, [rbp+52]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+56]
  push rax
  pop rcx
  mov rax, 0
  call ??1E@@QEAA@XZ
  lea rax, [$_L_?retVal@@YAHH@Z_user_$msret8]
  jmp $LNleave$?retVal@@YAHH@Z$catch$0
  lea rax, [rbp+56]
  push rax
  pop rcx
  mov rax, 0
  call ??1E@@QEAA@XZ
  lea rax, $_L_?retVal@@YAHH@Z_caught_0
$LNleave$?retVal@@YAHH@Z$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?retVal@@YAHH@Z$catch$0:
?retVal@@YAHH@Z$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retVal@@YAHH@Z$catch$0 DB 019H
  DB $LNprolog$?retVal@@YAHH@Z$catch$0-$LNbeg$?retVal@@YAHH@Z$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?retVal@@YAHH@Z$catch$0-$LNbeg$?retVal@@YAHH@Z$catch$0
  DB 032H
  DB $LNpush$?retVal@@YAHH@Z$catch$0-$LNbeg$?retVal@@YAHH@Z$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retVal@@YAHH@Z
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?retVal@@YAHH@Z DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?retVal@@YAHH@Z
  DD 1
  DD imagerel $tryMap$?retVal@@YAHH@Z
  DD 4
  DD imagerel $ip2state$?retVal@@YAHH@Z
  DD 40
  DD 00H
  DD 01H
$stateUnwindMap$?retVal@@YAHH@Z DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?retVal@@YAHH@Z DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?retVal@@YAHH@Z
$handlerMap$0$?retVal@@YAHH@Z DD 0
  DD imagerel ??_R0?AUE@@@8
  DD 56
  DD imagerel ?retVal@@YAHH@Z$catch$0
  DD 56
$ip2state$?retVal@@YAHH@Z DD imagerel $LNbeg$?retVal@@YAHH@Z
  DD 0ffffffffH
  DD imagerel $_L_?retVal@@YAHH@Z_try_0
  DD 0
  DD imagerel $_L_?retVal@@YAHH@Z_tryend_0
  DD 0ffffffffH
  DD imagerel ?retVal@@YAHH@Z$catch$0
  DD 1
.xdata ENDS

.CODE
?retVoid@@YAXPEAH@Z PROC
$LNbeg$?retVoid@@YAXPEAH@Z:
  push rbp
$LNpush$?retVoid@@YAXPEAH@Z:
  sub rsp, 64
$LNalloc$?retVoid@@YAXPEAH@Z:
  mov rbp, rsp
$LNfp$?retVoid@@YAXPEAH@Z:
$LNprolog$?retVoid@@YAXPEAH@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+56], rax
  mov QWORD PTR [rbp+32], -2
$_L_?retVoid@@YAXPEAH@Z_try_0:
  mov rax, 3
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
  nop
$_L_?retVoid@@YAXPEAH@Z_tryend_0:
$_L_?retVoid@@YAXPEAH@Z_caught_0:
  jmp $_L_?retVoid@@YAXPEAH@Z_user_$msskip12
$_L_?retVoid@@YAXPEAH@Z_user_$msret11:
  jmp $_L_return_?retVoid@@YAXPEAH@Z
$_L_?retVoid@@YAXPEAH@Z_user_$msskip12:
  mov rax, 1
  neg eax
  movsxd rax, eax
  push rax
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
$_L_return_?retVoid@@YAXPEAH@Z:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?retVoid@@YAXPEAH@Z:
?retVoid@@YAXPEAH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retVoid@@YAXPEAH@Z DD imagerel $LNbeg$?retVoid@@YAXPEAH@Z
  DD imagerel $LNend$?retVoid@@YAXPEAH@Z
  DD imagerel $unwind$?retVoid@@YAXPEAH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retVoid@@YAXPEAH@Z DB 019H
  DB $LNprolog$?retVoid@@YAXPEAH@Z-$LNbeg$?retVoid@@YAXPEAH@Z
  DB 3
  DB 05H
  DB $LNfp$?retVoid@@YAXPEAH@Z-$LNbeg$?retVoid@@YAXPEAH@Z
  DB 03H
  DB $LNalloc$?retVoid@@YAXPEAH@Z-$LNbeg$?retVoid@@YAXPEAH@Z
  DB 072H
  DB $LNpush$?retVoid@@YAXPEAH@Z-$LNbeg$?retVoid@@YAXPEAH@Z
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retVoid@@YAXPEAH@Z
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?retVoid@@YAXPEAH@Z$catch$0 PROC
$LNbeg$?retVoid@@YAXPEAH@Z$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?retVoid@@YAXPEAH@Z$catch$0:
  sub rsp, 32
$LNprolog$?retVoid@@YAXPEAH@Z$catch$0:
  mov rbp, rdx
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?retVoid@@YAXPEAH@Z_user_$msret11]
  jmp $LNleave$?retVoid@@YAXPEAH@Z$catch$0
  lea rax, $_L_?retVoid@@YAXPEAH@Z_caught_0
$LNleave$?retVoid@@YAXPEAH@Z$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?retVoid@@YAXPEAH@Z$catch$0:
?retVoid@@YAXPEAH@Z$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retVoid@@YAXPEAH@Z$catch$0 DB 019H
  DB $LNprolog$?retVoid@@YAXPEAH@Z$catch$0-$LNbeg$?retVoid@@YAXPEAH@Z$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?retVoid@@YAXPEAH@Z$catch$0-$LNbeg$?retVoid@@YAXPEAH@Z$catch$0
  DB 032H
  DB $LNpush$?retVoid@@YAXPEAH@Z$catch$0-$LNbeg$?retVoid@@YAXPEAH@Z$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retVoid@@YAXPEAH@Z
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?retVoid@@YAXPEAH@Z DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?retVoid@@YAXPEAH@Z
  DD 1
  DD imagerel $tryMap$?retVoid@@YAXPEAH@Z
  DD 4
  DD imagerel $ip2state$?retVoid@@YAXPEAH@Z
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$?retVoid@@YAXPEAH@Z DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?retVoid@@YAXPEAH@Z DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?retVoid@@YAXPEAH@Z
$handlerMap$0$?retVoid@@YAXPEAH@Z DD 0
  DD imagerel ??_R0H@8
  DD 40
  DD imagerel ?retVoid@@YAXPEAH@Z$catch$0
  DD 56
$ip2state$?retVoid@@YAXPEAH@Z DD imagerel $LNbeg$?retVoid@@YAXPEAH@Z
  DD 0ffffffffH
  DD imagerel $_L_?retVoid@@YAXPEAH@Z_try_0
  DD 0
  DD imagerel $_L_?retVoid@@YAXPEAH@Z_tryend_0
  DD 0ffffffffH
  DD imagerel ?retVoid@@YAXPEAH@Z$catch$0
  DD 1
.xdata ENDS

.CODE
?retBig@@YA?AUBig@@XZ PROC
$LNbeg$?retBig@@YA?AUBig@@XZ:
  push rbp
$LNpush$?retBig@@YA?AUBig@@XZ:
  sub rsp, 128
$LNalloc$?retBig@@YA?AUBig@@XZ:
  mov rbp, rsp
$LNfp$?retBig@@YA?AUBig@@XZ:
$LNprolog$?retBig@@YA?AUBig@@XZ:
  mov [rbp+120], rcx
  mov rax, 1
  push rax
  lea rax, [rbp+96]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 2
  push rax
  lea rax, [rbp+96]
  add rax, 4
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 3
  push rax
  lea rax, [rbp+96]
  add rax, 8
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 4
  push rax
  lea rax, [rbp+96]
  add rax, 12
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 5
  push rax
  lea rax, [rbp+96]
  add rax, 16
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov QWORD PTR [rbp+40], -2
$_L_?retBig@@YA?AUBig@@XZ_try_0:
  mov rax, 9
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
  nop
$_L_?retBig@@YA?AUBig@@XZ_tryend_0:
$_L_?retBig@@YA?AUBig@@XZ_caught_0:
  jmp $_L_?retBig@@YA?AUBig@@XZ_user_$msskip16
$_L_?retBig@@YA?AUBig@@XZ_user_$msret15:
  lea rax, [rbp+48]
  mov r10, [rbp+120]
  mov rcx, [rax]
  mov [r10], rcx
  mov rcx, [rax+8]
  mov [r10+8], rcx
  mov ecx, DWORD PTR [rax+16]
  mov DWORD PTR [r10+16], ecx
  mov rax, [rbp+120]
  jmp $_L_return_?retBig@@YA?AUBig@@XZ
$_L_?retBig@@YA?AUBig@@XZ_user_$msskip16:
  mov rax, 1
  neg eax
  movsxd rax, eax
  push rax
  lea rax, [rbp+96]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+96]
  mov r10, [rbp+120]
  mov rcx, [rax]
  mov [r10], rcx
  mov rcx, [rax+8]
  mov [r10+8], rcx
  mov ecx, DWORD PTR [rax+16]
  mov DWORD PTR [r10+16], ecx
  mov rax, [rbp+120]
  jmp $_L_return_?retBig@@YA?AUBig@@XZ
  mov rax, [rbp+120]
$_L_return_?retBig@@YA?AUBig@@XZ:
  lea rsp, [rbp+128]
  pop rbp
  ret
$LNend$?retBig@@YA?AUBig@@XZ:
?retBig@@YA?AUBig@@XZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retBig@@YA?AUBig@@XZ DD imagerel $LNbeg$?retBig@@YA?AUBig@@XZ
  DD imagerel $LNend$?retBig@@YA?AUBig@@XZ
  DD imagerel $unwind$?retBig@@YA?AUBig@@XZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retBig@@YA?AUBig@@XZ DB 019H
  DB $LNprolog$?retBig@@YA?AUBig@@XZ-$LNbeg$?retBig@@YA?AUBig@@XZ
  DB 3
  DB 05H
  DB $LNfp$?retBig@@YA?AUBig@@XZ-$LNbeg$?retBig@@YA?AUBig@@XZ
  DB 03H
  DB $LNalloc$?retBig@@YA?AUBig@@XZ-$LNbeg$?retBig@@YA?AUBig@@XZ
  DB 0F2H
  DB $LNpush$?retBig@@YA?AUBig@@XZ-$LNbeg$?retBig@@YA?AUBig@@XZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retBig@@YA?AUBig@@XZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?retBig@@YA?AUBig@@XZ$catch$0 PROC
$LNbeg$?retBig@@YA?AUBig@@XZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?retBig@@YA?AUBig@@XZ$catch$0:
  sub rsp, 32
$LNprolog$?retBig@@YA?AUBig@@XZ$catch$0:
  mov rbp, rdx
  lea rax, [rbp+80]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+96]
  add rax, 16
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+96]
  push rax
  lea rax, [rbp+48]
  mov r10, rax
  pop rax
  mov rcx, [rax]
  mov [r10], rcx
  mov rcx, [rax+8]
  mov [r10+8], rcx
  mov ecx, DWORD PTR [rax+16]
  mov DWORD PTR [r10+16], ecx
  mov rax, r10
  lea rax, [$_L_?retBig@@YA?AUBig@@XZ_user_$msret15]
  jmp $LNleave$?retBig@@YA?AUBig@@XZ$catch$0
  lea rax, $_L_?retBig@@YA?AUBig@@XZ_caught_0
$LNleave$?retBig@@YA?AUBig@@XZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?retBig@@YA?AUBig@@XZ$catch$0:
?retBig@@YA?AUBig@@XZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retBig@@YA?AUBig@@XZ$catch$0 DB 019H
  DB $LNprolog$?retBig@@YA?AUBig@@XZ$catch$0-$LNbeg$?retBig@@YA?AUBig@@XZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?retBig@@YA?AUBig@@XZ$catch$0-$LNbeg$?retBig@@YA?AUBig@@XZ$catch$0
  DB 032H
  DB $LNpush$?retBig@@YA?AUBig@@XZ$catch$0-$LNbeg$?retBig@@YA?AUBig@@XZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retBig@@YA?AUBig@@XZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?retBig@@YA?AUBig@@XZ DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?retBig@@YA?AUBig@@XZ
  DD 1
  DD imagerel $tryMap$?retBig@@YA?AUBig@@XZ
  DD 4
  DD imagerel $ip2state$?retBig@@YA?AUBig@@XZ
  DD 40
  DD 00H
  DD 01H
$stateUnwindMap$?retBig@@YA?AUBig@@XZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?retBig@@YA?AUBig@@XZ DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?retBig@@YA?AUBig@@XZ
$handlerMap$0$?retBig@@YA?AUBig@@XZ DD 0
  DD imagerel ??_R0H@8
  DD 80
  DD imagerel ?retBig@@YA?AUBig@@XZ$catch$0
  DD 56
$ip2state$?retBig@@YA?AUBig@@XZ DD imagerel $LNbeg$?retBig@@YA?AUBig@@XZ
  DD 0ffffffffH
  DD imagerel $_L_?retBig@@YA?AUBig@@XZ_try_0
  DD 0
  DD imagerel $_L_?retBig@@YA?AUBig@@XZ_tryend_0
  DD 0ffffffffH
  DD imagerel ?retBig@@YA?AUBig@@XZ$catch$0
  DD 1
.xdata ENDS

.CODE
?retDouble@@YANXZ PROC
$LNbeg$?retDouble@@YANXZ:
  push rbp
$LNpush$?retDouble@@YANXZ:
  sub rsp, 64
$LNalloc$?retDouble@@YANXZ:
  mov rbp, rsp
$LNfp$?retDouble@@YANXZ:
$LNprolog$?retDouble@@YANXZ:
  mov QWORD PTR [rbp+32], -2
$_L_?retDouble@@YANXZ_try_0:
  mov rax, 2
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
  nop
$_L_?retDouble@@YANXZ_tryend_0:
$_L_?retDouble@@YANXZ_caught_0:
  jmp $_L_?retDouble@@YANXZ_user_$msskip20
$_L_?retDouble@@YANXZ_user_$msret19:
  lea rax, [rbp+40]
  movsd xmm0, QWORD PTR [rax]
  jmp $_L_return_?retDouble@@YANXZ
$_L_?retDouble@@YANXZ_user_$msskip20:
  mov rax, 4607182418800017408
  movq xmm0, rax
  mov rax, 9223372036854775808
  movq xmm1, rax
  xorpd xmm0, xmm1
  jmp $_L_return_?retDouble@@YANXZ
  pxor xmm0, xmm0
$_L_return_?retDouble@@YANXZ:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?retDouble@@YANXZ:
?retDouble@@YANXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retDouble@@YANXZ DD imagerel $LNbeg$?retDouble@@YANXZ
  DD imagerel $LNend$?retDouble@@YANXZ
  DD imagerel $unwind$?retDouble@@YANXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retDouble@@YANXZ DB 019H
  DB $LNprolog$?retDouble@@YANXZ-$LNbeg$?retDouble@@YANXZ
  DB 3
  DB 05H
  DB $LNfp$?retDouble@@YANXZ-$LNbeg$?retDouble@@YANXZ
  DB 03H
  DB $LNalloc$?retDouble@@YANXZ-$LNbeg$?retDouble@@YANXZ
  DB 072H
  DB $LNpush$?retDouble@@YANXZ-$LNbeg$?retDouble@@YANXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retDouble@@YANXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?retDouble@@YANXZ$catch$0 PROC
$LNbeg$?retDouble@@YANXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?retDouble@@YANXZ$catch$0:
  sub rsp, 32
$LNprolog$?retDouble@@YANXZ$catch$0:
  mov rbp, rdx
  mov rax, 4609434218613702656
  movq xmm0, rax
  sub rsp, 8
  movsd QWORD PTR [rsp], xmm0
  lea rax, [rbp+48]
  movsxd rax, DWORD PTR [rax]
  cvtsi2sd xmm0, rax
  movsd xmm1, QWORD PTR [rsp]
  add rsp, 8
  mulsd xmm0, xmm1
  sub rsp, 8
  movsd QWORD PTR [rsp], xmm0
  lea rax, [rbp+40]
  mov r10, rax
  movsd xmm0, QWORD PTR [rsp]
  add rsp, 8
  movsd QWORD PTR [r10], xmm0
  lea rax, [$_L_?retDouble@@YANXZ_user_$msret19]
  jmp $LNleave$?retDouble@@YANXZ$catch$0
  lea rax, $_L_?retDouble@@YANXZ_caught_0
$LNleave$?retDouble@@YANXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?retDouble@@YANXZ$catch$0:
?retDouble@@YANXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?retDouble@@YANXZ$catch$0 DB 019H
  DB $LNprolog$?retDouble@@YANXZ$catch$0-$LNbeg$?retDouble@@YANXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?retDouble@@YANXZ$catch$0-$LNbeg$?retDouble@@YANXZ$catch$0
  DB 032H
  DB $LNpush$?retDouble@@YANXZ$catch$0-$LNbeg$?retDouble@@YANXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?retDouble@@YANXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?retDouble@@YANXZ DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?retDouble@@YANXZ
  DD 1
  DD imagerel $tryMap$?retDouble@@YANXZ
  DD 4
  DD imagerel $ip2state$?retDouble@@YANXZ
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$?retDouble@@YANXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?retDouble@@YANXZ DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?retDouble@@YANXZ
$handlerMap$0$?retDouble@@YANXZ DD 0
  DD imagerel ??_R0H@8
  DD 48
  DD imagerel ?retDouble@@YANXZ$catch$0
  DD 56
$ip2state$?retDouble@@YANXZ DD imagerel $LNbeg$?retDouble@@YANXZ
  DD 0ffffffffH
  DD imagerel $_L_?retDouble@@YANXZ_try_0
  DD 0
  DD imagerel $_L_?retDouble@@YANXZ_tryend_0
  DD 0ffffffffH
  DD imagerel ?retDouble@@YANXZ$catch$0
  DD 1
.xdata ENDS

.CODE
?loopBreak@@YAHXZ PROC
$LNbeg$?loopBreak@@YAHXZ:
  push rbp
$LNpush$?loopBreak@@YAHXZ:
  sub rsp, 64
$LNalloc$?loopBreak@@YAHXZ:
  mov rbp, rsp
$LNfp$?loopBreak@@YAHXZ:
$LNprolog$?loopBreak@@YAHXZ:
  mov rax, 0
  push rax
  lea rax, [rbp+60]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
  push rax
  lea rax, [rbp+56]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?loopBreak@@YAHXZ_begin_0:
  mov rax, 10
  push rax
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setl al
  movzx rax, al
  cmp rax, 0
  je $_L_?loopBreak@@YAHXZ_end_0
  mov QWORD PTR [rbp+32], -2
$_L_?loopBreak@@YAHXZ_try_1:
  mov rax, 4
  push rax
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?loopBreak@@YAHXZ_end_2
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
$_L_?loopBreak@@YAHXZ_end_2:
  lea rax, [rbp+60]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
$_L_?loopBreak@@YAHXZ_tryend_1:
$_L_?loopBreak@@YAHXZ_caught_1:
  jmp $_L_?loopBreak@@YAHXZ_user_$msskip23
$_L_?loopBreak@@YAHXZ_user_$msbrk22:
  jmp $_L_?loopBreak@@YAHXZ_end_0
$_L_?loopBreak@@YAHXZ_user_$msskip23:
$_L_?loopBreak@@YAHXZ_step_0:
  lea rax, [rbp+56]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_?loopBreak@@YAHXZ_begin_0
$_L_?loopBreak@@YAHXZ_end_0:
  lea rax, [rbp+60]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?loopBreak@@YAHXZ
  mov rax, 0
$_L_return_?loopBreak@@YAHXZ:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?loopBreak@@YAHXZ:
?loopBreak@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?loopBreak@@YAHXZ DD imagerel $LNbeg$?loopBreak@@YAHXZ
  DD imagerel $LNend$?loopBreak@@YAHXZ
  DD imagerel $unwind$?loopBreak@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?loopBreak@@YAHXZ DB 019H
  DB $LNprolog$?loopBreak@@YAHXZ-$LNbeg$?loopBreak@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?loopBreak@@YAHXZ-$LNbeg$?loopBreak@@YAHXZ
  DB 03H
  DB $LNalloc$?loopBreak@@YAHXZ-$LNbeg$?loopBreak@@YAHXZ
  DB 072H
  DB $LNpush$?loopBreak@@YAHXZ-$LNbeg$?loopBreak@@YAHXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?loopBreak@@YAHXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?loopBreak@@YAHXZ$catch$0 PROC
$LNbeg$?loopBreak@@YAHXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?loopBreak@@YAHXZ$catch$0:
  sub rsp, 32
$LNprolog$?loopBreak@@YAHXZ$catch$0:
  mov rbp, rdx
  lea rax, [$_L_?loopBreak@@YAHXZ_user_$msbrk22]
  jmp $LNleave$?loopBreak@@YAHXZ$catch$0
  lea rax, $_L_?loopBreak@@YAHXZ_caught_1
$LNleave$?loopBreak@@YAHXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?loopBreak@@YAHXZ$catch$0:
?loopBreak@@YAHXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?loopBreak@@YAHXZ$catch$0 DB 019H
  DB $LNprolog$?loopBreak@@YAHXZ$catch$0-$LNbeg$?loopBreak@@YAHXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?loopBreak@@YAHXZ$catch$0-$LNbeg$?loopBreak@@YAHXZ$catch$0
  DB 032H
  DB $LNpush$?loopBreak@@YAHXZ$catch$0-$LNbeg$?loopBreak@@YAHXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?loopBreak@@YAHXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?loopBreak@@YAHXZ DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?loopBreak@@YAHXZ
  DD 1
  DD imagerel $tryMap$?loopBreak@@YAHXZ
  DD 4
  DD imagerel $ip2state$?loopBreak@@YAHXZ
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$?loopBreak@@YAHXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?loopBreak@@YAHXZ DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?loopBreak@@YAHXZ
$handlerMap$0$?loopBreak@@YAHXZ DD 0
  DD imagerel ??_R0H@8
  DD 0
  DD imagerel ?loopBreak@@YAHXZ$catch$0
  DD 56
$ip2state$?loopBreak@@YAHXZ DD imagerel $LNbeg$?loopBreak@@YAHXZ
  DD 0ffffffffH
  DD imagerel $_L_?loopBreak@@YAHXZ_try_1
  DD 0
  DD imagerel $_L_?loopBreak@@YAHXZ_tryend_1
  DD 0ffffffffH
  DD imagerel ?loopBreak@@YAHXZ$catch$0
  DD 1
.xdata ENDS

.CODE
?loopContinue@@YAHXZ PROC
$LNbeg$?loopContinue@@YAHXZ:
  push rbp
$LNpush$?loopContinue@@YAHXZ:
  sub rsp, 64
$LNalloc$?loopContinue@@YAHXZ:
  mov rbp, rsp
$LNfp$?loopContinue@@YAHXZ:
$LNprolog$?loopContinue@@YAHXZ:
  mov rax, 0
  push rax
  lea rax, [rbp+60]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
  push rax
  lea rax, [rbp+56]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?loopContinue@@YAHXZ_begin_0:
  mov rax, 6
  push rax
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setl al
  movzx rax, al
  cmp rax, 0
  je $_L_?loopContinue@@YAHXZ_end_0
  mov QWORD PTR [rbp+32], -2
$_L_?loopContinue@@YAHXZ_try_1:
  mov rax, 2
  push rax
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cdq
  idiv r10d
  mov eax, edx
  movsxd rax, eax
  cmp rax, 0
  je $_L_?loopContinue@@YAHXZ_end_2
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
$_L_?loopContinue@@YAHXZ_end_2:
  nop
$_L_?loopContinue@@YAHXZ_tryend_1:
$_L_?loopContinue@@YAHXZ_caught_1:
  jmp $_L_?loopContinue@@YAHXZ_user_$msskip26
$_L_?loopContinue@@YAHXZ_user_$mscont25:
  jmp $_L_?loopContinue@@YAHXZ_step_0
$_L_?loopContinue@@YAHXZ_user_$msskip26:
  mov rax, 100
  push rax
  lea rax, [rbp+60]
  movsxd rax, DWORD PTR [rax]
  pop r10
  add eax, r10d
  movsxd rax, eax
  push rax
  lea rax, [rbp+60]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?loopContinue@@YAHXZ_step_0:
  lea rax, [rbp+56]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_?loopContinue@@YAHXZ_begin_0
$_L_?loopContinue@@YAHXZ_end_0:
  lea rax, [rbp+60]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?loopContinue@@YAHXZ
  mov rax, 0
$_L_return_?loopContinue@@YAHXZ:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?loopContinue@@YAHXZ:
?loopContinue@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?loopContinue@@YAHXZ DD imagerel $LNbeg$?loopContinue@@YAHXZ
  DD imagerel $LNend$?loopContinue@@YAHXZ
  DD imagerel $unwind$?loopContinue@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?loopContinue@@YAHXZ DB 019H
  DB $LNprolog$?loopContinue@@YAHXZ-$LNbeg$?loopContinue@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?loopContinue@@YAHXZ-$LNbeg$?loopContinue@@YAHXZ
  DB 03H
  DB $LNalloc$?loopContinue@@YAHXZ-$LNbeg$?loopContinue@@YAHXZ
  DB 072H
  DB $LNpush$?loopContinue@@YAHXZ-$LNbeg$?loopContinue@@YAHXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?loopContinue@@YAHXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?loopContinue@@YAHXZ$catch$0 PROC
$LNbeg$?loopContinue@@YAHXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?loopContinue@@YAHXZ$catch$0:
  sub rsp, 32
$LNprolog$?loopContinue@@YAHXZ$catch$0:
  mov rbp, rdx
  lea rax, [$_L_?loopContinue@@YAHXZ_user_$mscont25]
  jmp $LNleave$?loopContinue@@YAHXZ$catch$0
  lea rax, $_L_?loopContinue@@YAHXZ_caught_1
$LNleave$?loopContinue@@YAHXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?loopContinue@@YAHXZ$catch$0:
?loopContinue@@YAHXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?loopContinue@@YAHXZ$catch$0 DB 019H
  DB $LNprolog$?loopContinue@@YAHXZ$catch$0-$LNbeg$?loopContinue@@YAHXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?loopContinue@@YAHXZ$catch$0-$LNbeg$?loopContinue@@YAHXZ$catch$0
  DB 032H
  DB $LNpush$?loopContinue@@YAHXZ$catch$0-$LNbeg$?loopContinue@@YAHXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?loopContinue@@YAHXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?loopContinue@@YAHXZ DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?loopContinue@@YAHXZ
  DD 1
  DD imagerel $tryMap$?loopContinue@@YAHXZ
  DD 4
  DD imagerel $ip2state$?loopContinue@@YAHXZ
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$?loopContinue@@YAHXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?loopContinue@@YAHXZ DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?loopContinue@@YAHXZ
$handlerMap$0$?loopContinue@@YAHXZ DD 0
  DD imagerel ??_R0H@8
  DD 0
  DD imagerel ?loopContinue@@YAHXZ$catch$0
  DD 56
$ip2state$?loopContinue@@YAHXZ DD imagerel $LNbeg$?loopContinue@@YAHXZ
  DD 0ffffffffH
  DD imagerel $_L_?loopContinue@@YAHXZ_try_1
  DD 0
  DD imagerel $_L_?loopContinue@@YAHXZ_tryend_1
  DD 0ffffffffH
  DD imagerel ?loopContinue@@YAHXZ$catch$0
  DD 1
.xdata ENDS

.CODE
?twoTries@@YAHH@Z PROC
$LNbeg$?twoTries@@YAHH@Z:
  push rbp
$LNpush$?twoTries@@YAHH@Z:
  sub rsp, 96
$LNalloc$?twoTries@@YAHH@Z:
  mov rbp, rsp
$LNfp$?twoTries@@YAHH@Z:
$LNprolog$?twoTries@@YAHH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+92], eax
  mov QWORD PTR [rbp+56], -2
$_L_?twoTries@@YAHH@Z_try_0:
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
  nop
$_L_?twoTries@@YAHH@Z_tryend_0:
$_L_?twoTries@@YAHH@Z_caught_0:
  jmp $_L_?twoTries@@YAHH@Z_user_$msskip30
$_L_?twoTries@@YAHH@Z_user_$msret29:
  lea rax, [rbp+68]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?twoTries@@YAHH@Z
$_L_?twoTries@@YAHH@Z_user_$msskip30:
  mov QWORD PTR [rbp+56], -2
$_L_?twoTries@@YAHH@Z_try_2:
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?boom@@YAXH@Z
  nop
$_L_?twoTries@@YAHH@Z_tryend_2:
$_L_?twoTries@@YAHH@Z_caught_2:
  jmp $_L_?twoTries@@YAHH@Z_user_$msskip34
$_L_?twoTries@@YAHH@Z_user_$msret33:
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?twoTries@@YAHH@Z
$_L_?twoTries@@YAHH@Z_user_$msskip34:
  mov rax, 33
  jmp $_L_return_?twoTries@@YAHH@Z
  mov rax, 0
$_L_return_?twoTries@@YAHH@Z:
  lea rsp, [rbp+96]
  pop rbp
  ret
$LNend$?twoTries@@YAHH@Z:
?twoTries@@YAHH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?twoTries@@YAHH@Z DD imagerel $LNbeg$?twoTries@@YAHH@Z
  DD imagerel $LNend$?twoTries@@YAHH@Z
  DD imagerel $unwind$?twoTries@@YAHH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?twoTries@@YAHH@Z DB 019H
  DB $LNprolog$?twoTries@@YAHH@Z-$LNbeg$?twoTries@@YAHH@Z
  DB 3
  DB 05H
  DB $LNfp$?twoTries@@YAHH@Z-$LNbeg$?twoTries@@YAHH@Z
  DB 03H
  DB $LNalloc$?twoTries@@YAHH@Z-$LNbeg$?twoTries@@YAHH@Z
  DB 0B2H
  DB $LNpush$?twoTries@@YAHH@Z-$LNbeg$?twoTries@@YAHH@Z
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?twoTries@@YAHH@Z
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?twoTries@@YAHH@Z$catch$0 PROC
$LNbeg$?twoTries@@YAHH@Z$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?twoTries@@YAHH@Z$catch$0:
  sub rsp, 32
$LNprolog$?twoTries@@YAHH@Z$catch$0:
  mov rbp, rdx
  mov rax, 1
  push rax
  lea rax, [rbp+72]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?twoTries@@YAHH@Z_end_1
  mov rax, 11
  push rax
  lea rax, [rbp+68]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?twoTries@@YAHH@Z_user_$msret29]
  jmp $LNleave$?twoTries@@YAHH@Z$catch$0
$_L_?twoTries@@YAHH@Z_end_1:
  lea rax, $_L_?twoTries@@YAHH@Z_caught_0
$LNleave$?twoTries@@YAHH@Z$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?twoTries@@YAHH@Z$catch$0:
?twoTries@@YAHH@Z$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?twoTries@@YAHH@Z$catch$0 DB 019H
  DB $LNprolog$?twoTries@@YAHH@Z$catch$0-$LNbeg$?twoTries@@YAHH@Z$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?twoTries@@YAHH@Z$catch$0-$LNbeg$?twoTries@@YAHH@Z$catch$0
  DB 032H
  DB $LNpush$?twoTries@@YAHH@Z$catch$0-$LNbeg$?twoTries@@YAHH@Z$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?twoTries@@YAHH@Z
.xdata ENDS

.text$x SEGMENT ALIGN(16) 'CODE'
?twoTries@@YAHH@Z$catch$1 PROC
$LNbeg$?twoTries@@YAHH@Z$catch$1:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?twoTries@@YAHH@Z$catch$1:
  sub rsp, 32
$LNprolog$?twoTries@@YAHH@Z$catch$1:
  mov rbp, rdx
  mov rax, 2
  push rax
  lea rax, [rbp+72]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?twoTries@@YAHH@Z_end_3
  mov rax, 22
  push rax
  lea rax, [rbp+40]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?twoTries@@YAHH@Z_user_$msret33]
  jmp $LNleave$?twoTries@@YAHH@Z$catch$1
$_L_?twoTries@@YAHH@Z_end_3:
  lea rax, $_L_?twoTries@@YAHH@Z_caught_2
$LNleave$?twoTries@@YAHH@Z$catch$1:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?twoTries@@YAHH@Z$catch$1:
?twoTries@@YAHH@Z$catch$1 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?twoTries@@YAHH@Z$catch$1 DB 019H
  DB $LNprolog$?twoTries@@YAHH@Z$catch$1-$LNbeg$?twoTries@@YAHH@Z$catch$1
  DB 02H
  DB 00H
  DB $LNprolog$?twoTries@@YAHH@Z$catch$1-$LNbeg$?twoTries@@YAHH@Z$catch$1
  DB 032H
  DB $LNpush$?twoTries@@YAHH@Z$catch$1-$LNbeg$?twoTries@@YAHH@Z$catch$1
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?twoTries@@YAHH@Z
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?twoTries@@YAHH@Z DD 019930522H
  DD 4
  DD imagerel $stateUnwindMap$?twoTries@@YAHH@Z
  DD 2
  DD imagerel $tryMap$?twoTries@@YAHH@Z
  DD 7
  DD imagerel $ip2state$?twoTries@@YAHH@Z
  DD 56
  DD 00H
  DD 01H
$stateUnwindMap$?twoTries@@YAHH@Z DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?twoTries@@YAHH@Z DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?twoTries@@YAHH@Z
  DD 2
  DD 2
  DD 3
  DD 1
  DD imagerel $handlerMap$1$?twoTries@@YAHH@Z
$handlerMap$0$?twoTries@@YAHH@Z DD 0
  DD imagerel ??_R0H@8
  DD 72
  DD imagerel ?twoTries@@YAHH@Z$catch$0
  DD 56
$handlerMap$1$?twoTries@@YAHH@Z DD 0
  DD imagerel ??_R0H@8
  DD 72
  DD imagerel ?twoTries@@YAHH@Z$catch$1
  DD 56
$ip2state$?twoTries@@YAHH@Z DD imagerel $LNbeg$?twoTries@@YAHH@Z
  DD 0ffffffffH
  DD imagerel $_L_?twoTries@@YAHH@Z_try_0
  DD 0
  DD imagerel $_L_?twoTries@@YAHH@Z_tryend_0
  DD 0ffffffffH
  DD imagerel $_L_?twoTries@@YAHH@Z_try_2
  DD 2
  DD imagerel $_L_?twoTries@@YAHH@Z_tryend_2
  DD 0ffffffffH
  DD imagerel ?twoTries@@YAHH@Z$catch$0
  DD 1
  DD imagerel ?twoTries@@YAHH@Z$catch$1
  DD 3
.xdata ENDS

.CODE
?noThrow@@YAHXZ PROC
$LNbeg$?noThrow@@YAHXZ:
  push rbp
$LNpush$?noThrow@@YAHXZ:
  sub rsp, 32
$LNalloc$?noThrow@@YAHXZ:
  mov rbp, rsp
$LNfp$?noThrow@@YAHXZ:
$LNprolog$?noThrow@@YAHXZ:
  mov QWORD PTR [rbp+8], -2
$_L_?noThrow@@YAHXZ_try_0:
$_L_?noThrow@@YAHXZ_tryend_0:
$_L_?noThrow@@YAHXZ_caught_0:
  jmp $_L_?noThrow@@YAHXZ_user_$msskip38
$_L_?noThrow@@YAHXZ_user_$msret37:
  lea rax, [rbp+16]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?noThrow@@YAHXZ
$_L_?noThrow@@YAHXZ_user_$msskip38:
  mov rax, 6
  jmp $_L_return_?noThrow@@YAHXZ
  mov rax, 0
$_L_return_?noThrow@@YAHXZ:
  lea rsp, [rbp+32]
  pop rbp
  ret
$LNend$?noThrow@@YAHXZ:
?noThrow@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?noThrow@@YAHXZ DD imagerel $LNbeg$?noThrow@@YAHXZ
  DD imagerel $LNend$?noThrow@@YAHXZ
  DD imagerel $unwind$?noThrow@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?noThrow@@YAHXZ DB 019H
  DB $LNprolog$?noThrow@@YAHXZ-$LNbeg$?noThrow@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?noThrow@@YAHXZ-$LNbeg$?noThrow@@YAHXZ
  DB 03H
  DB $LNalloc$?noThrow@@YAHXZ-$LNbeg$?noThrow@@YAHXZ
  DB 032H
  DB $LNpush$?noThrow@@YAHXZ-$LNbeg$?noThrow@@YAHXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?noThrow@@YAHXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?noThrow@@YAHXZ$catch$0 PROC
$LNbeg$?noThrow@@YAHXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?noThrow@@YAHXZ$catch$0:
  sub rsp, 32
$LNprolog$?noThrow@@YAHXZ$catch$0:
  mov rbp, rdx
  mov rax, 5
  push rax
  lea rax, [rbp+16]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?noThrow@@YAHXZ_user_$msret37]
  jmp $LNleave$?noThrow@@YAHXZ$catch$0
  lea rax, $_L_?noThrow@@YAHXZ_caught_0
$LNleave$?noThrow@@YAHXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?noThrow@@YAHXZ$catch$0:
?noThrow@@YAHXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?noThrow@@YAHXZ$catch$0 DB 019H
  DB $LNprolog$?noThrow@@YAHXZ$catch$0-$LNbeg$?noThrow@@YAHXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?noThrow@@YAHXZ$catch$0-$LNbeg$?noThrow@@YAHXZ$catch$0
  DB 032H
  DB $LNpush$?noThrow@@YAHXZ$catch$0-$LNbeg$?noThrow@@YAHXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?noThrow@@YAHXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?noThrow@@YAHXZ DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?noThrow@@YAHXZ
  DD 1
  DD imagerel $tryMap$?noThrow@@YAHXZ
  DD 4
  DD imagerel $ip2state$?noThrow@@YAHXZ
  DD 8
  DD 00H
  DD 01H
$stateUnwindMap$?noThrow@@YAHXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?noThrow@@YAHXZ DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?noThrow@@YAHXZ
$handlerMap$0$?noThrow@@YAHXZ DD 0
  DD imagerel ??_R0H@8
  DD 0
  DD imagerel ?noThrow@@YAHXZ$catch$0
  DD 56
$ip2state$?noThrow@@YAHXZ DD imagerel $LNbeg$?noThrow@@YAHXZ
  DD 0ffffffffH
  DD imagerel $_L_?noThrow@@YAHXZ_try_0
  DD 0
  DD imagerel $_L_?noThrow@@YAHXZ_tryend_0
  DD 0ffffffffH
  DD imagerel ?noThrow@@YAHXZ$catch$0
  DD 1
.xdata ENDS

.CODE
main PROC
$LNbeg$main:
  push rbp
$LNpush$main:
  sub rsp, 128
$LNalloc$main:
  mov rbp, rsp
$LNfp$main:
$LNprolog$main:
  mov rax, 0
  push rax
  lea rax, [rbp+124]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+124]
  push rax
  pop rcx
  mov rax, 0
  call ?retVoid@@YAXPEAH@Z
  lea rcx, [rbp+96]
  mov rax, 0
  call ?retBig@@YA?AUBig@@XZ
  lea rax, [rbp+96]
  push rax
  lea rax, [rbp+64]
  mov r10, rax
  pop rax
  mov rcx, [rax]
  mov [r10], rcx
  mov rcx, [rax+8]
  mov [r10+8], rcx
  mov ecx, DWORD PTR [rax+16]
  mov DWORD PTR [r10+16], ecx
  mov rax, r10
  mov rax, 0
  call ?retDouble@@YANXZ
  movsd QWORD PTR [rsp+40], xmm0
  lea rax, [rbp+64]
  add rax, 16
  movsxd rax, DWORD PTR [rax]
  mov [rsp+32], rax
  lea rax, [$_L_str_0]
  push rax
  sub rsp, 8
  mov rax, 7
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?retInt@@YAHH@Z
  add rsp, 40
  movsxd rax, eax
  push rax
  mov rax, 4
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?retVal@@YAHH@Z
  add rsp, 32
  movsxd rax, eax
  push rax
  lea rax, [rbp+124]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop r9
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
  call ?noThrow@@YAHXZ
  movsxd rax, eax
  mov [rsp+48], rax
  mov rax, 3
  push rax
  pop rcx
  mov rax, 0
  call ?twoTries@@YAHH@Z
  movsxd rax, eax
  mov [rsp+40], rax
  mov rax, 2
  push rax
  pop rcx
  mov rax, 0
  call ?twoTries@@YAHH@Z
  movsxd rax, eax
  mov [rsp+32], rax
  lea rax, [$_L_str_1]
  push rax
  sub rsp, 8
  mov rax, 0
  sub rsp, 32
  call ?loopBreak@@YAHXZ
  add rsp, 40
  movsxd rax, eax
  push rax
  mov rax, 0
  sub rsp, 32
  call ?loopContinue@@YAHXZ
  add rsp, 32
  movsxd rax, eax
  push rax
  sub rsp, 8
  mov rax, 1
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?twoTries@@YAHH@Z
  add rsp, 40
  movsxd rax, eax
  push rax
  pop r9
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, [$_L_str_2]
  push rax
  lea rax, [live]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
  jmp $_L_return_main
  mov rax, 0
$_L_return_main:
  lea rsp, [rbp+128]
  pop rbp
  ret
$LNend$main:
main ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main DD imagerel $LNbeg$main
  DD imagerel $LNend$main
  DD imagerel $unwind$main
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main DB 01H
  DB $LNprolog$main-$LNbeg$main
  DB 3
  DB 05H
  DB $LNfp$main-$LNbeg$main
  DB 03H
  DB $LNalloc$main-$LNbeg$main
  DB 0F2H
  DB $LNpush$main-$LNbeg$main
  DB 050H
  DW 0
.xdata ENDS

.CODE

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retInt@@YAHH@Z$catch$0 DD imagerel $LNbeg$?retInt@@YAHH@Z$catch$0
  DD imagerel $LNend$?retInt@@YAHH@Z$catch$0
  DD imagerel $unwind$?retInt@@YAHH@Z$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retVal@@YAHH@Z$catch$0 DD imagerel $LNbeg$?retVal@@YAHH@Z$catch$0
  DD imagerel $LNend$?retVal@@YAHH@Z$catch$0
  DD imagerel $unwind$?retVal@@YAHH@Z$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retVoid@@YAXPEAH@Z$catch$0 DD imagerel $LNbeg$?retVoid@@YAXPEAH@Z$catch$0
  DD imagerel $LNend$?retVoid@@YAXPEAH@Z$catch$0
  DD imagerel $unwind$?retVoid@@YAXPEAH@Z$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retBig@@YA?AUBig@@XZ$catch$0 DD imagerel $LNbeg$?retBig@@YA?AUBig@@XZ$catch$0
  DD imagerel $LNend$?retBig@@YA?AUBig@@XZ$catch$0
  DD imagerel $unwind$?retBig@@YA?AUBig@@XZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?retDouble@@YANXZ$catch$0 DD imagerel $LNbeg$?retDouble@@YANXZ$catch$0
  DD imagerel $LNend$?retDouble@@YANXZ$catch$0
  DD imagerel $unwind$?retDouble@@YANXZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?loopBreak@@YAHXZ$catch$0 DD imagerel $LNbeg$?loopBreak@@YAHXZ$catch$0
  DD imagerel $LNend$?loopBreak@@YAHXZ$catch$0
  DD imagerel $unwind$?loopBreak@@YAHXZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?loopContinue@@YAHXZ$catch$0 DD imagerel $LNbeg$?loopContinue@@YAHXZ$catch$0
  DD imagerel $LNend$?loopContinue@@YAHXZ$catch$0
  DD imagerel $unwind$?loopContinue@@YAHXZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?twoTries@@YAHH@Z$catch$0 DD imagerel $LNbeg$?twoTries@@YAHH@Z$catch$0
  DD imagerel $LNend$?twoTries@@YAHH@Z$catch$0
  DD imagerel $unwind$?twoTries@@YAHH@Z$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?twoTries@@YAHH@Z$catch$1 DD imagerel $LNbeg$?twoTries@@YAHH@Z$catch$1
  DD imagerel $LNend$?twoTries@@YAHH@Z$catch$1
  DD imagerel $unwind$?twoTries@@YAHH@Z$catch$1
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?noThrow@@YAHXZ$catch$0 DD imagerel $LNbeg$?noThrow@@YAHXZ$catch$0
  DD imagerel $LNend$?noThrow@@YAHXZ$catch$0
  DD imagerel $unwind$?noThrow@@YAHXZ$catch$0
.pdata ENDS

END
