; Generated by cxx1 for x86_64-windows, in MASM syntax for ml64.
; The instruction selection is the same one the Linux backend makes;
; only the spelling is Microsoft's. See src/backend/Masm.cpp.

OPTION DOTNAME
OPTION NOSCOPED
OPTION PROC:PRIVATE

PUBLIC ??0Loud@@QEAA@H@Z
PUBLIC ?addressed@?$C@H@@2HA
PUBLIC ?bound@?$C@H@@2HA
PUBLIC ?built@?$C@H@@2ULoud@@A
PUBLIC ?built@?$C@H@@2ULoud@@A$guard
PUBLIC ?get@?$C@H@@QEBAHXZ
PUBLIC ?other@?$C@H@@2HA
PUBLIC ?other@?$C@H@@2HA$guard
PUBLIC ?read@?$C@H@@2HA
PUBLIC ?viaMember@?$C@H@@2HA
PUBLIC ?viaOther@?$C@H@@2HA
PUBLIC main
EXTERN printf:PROC


.CONST
$_L_str_0 DB 76, 111, 117, 100, 40, 37, 100, 41, 10, 0
$_L_str_1 DB 37, 100, 32, 37, 100, 32, 37, 100, 32, 37, 100, 32, 37, 100, 10, 0
$_L_str_2 DB 37, 100, 32, 37, 100, 10, 0

.DATA
  ALIGN 4
?read@?$C@H@@2HA DD 1
  ALIGN 4
?addressed@?$C@H@@2HA DD 2
  ALIGN 4
?bound@?$C@H@@2HA DD 3
  ALIGN 4
?viaMember@?$C@H@@2HA DD 4
  ALIGN 4
?viaOther@?$C@H@@2HA DD 5

.DATA?
  ALIGN 4
?other@?$C@H@@2HA$guard DB 4 DUP (?)
  ALIGN 4
?other@?$C@H@@2HA DB 4 DUP (?)
  ALIGN 4
?built@?$C@H@@2ULoud@@A$guard DB 4 DUP (?)
  ALIGN 4
?built@?$C@H@@2ULoud@@A DB 4 DUP (?)

.CODE
??0Loud@@QEAA@H@Z PROC
$LNbeg$??0Loud@@QEAA@H@Z:
  push rbp
$LNpush$??0Loud@@QEAA@H@Z:
  sub rsp, 48
$LNalloc$??0Loud@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0Loud@@QEAA@H@Z:
$LNprolog$??0Loud@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+32], rax
  mov rax, rdx
  mov DWORD PTR [rbp+44], eax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_str_0]
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
$_L_return_??0Loud@@QEAA@H@Z:
  mov rax, [rbp+32]
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??0Loud@@QEAA@H@Z:
??0Loud@@QEAA@H@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??0Loud@@QEAA@H@Z DD imagerel $LNbeg$??0Loud@@QEAA@H@Z
  DD imagerel $LNend$??0Loud@@QEAA@H@Z
  DD imagerel $unwind$??0Loud@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??0Loud@@QEAA@H@Z DB 01H
  DB $LNprolog$??0Loud@@QEAA@H@Z-$LNbeg$??0Loud@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0Loud@@QEAA@H@Z-$LNbeg$??0Loud@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0Loud@@QEAA@H@Z-$LNbeg$??0Loud@@QEAA@H@Z
  DB 052H
  DB $LNpush$??0Loud@@QEAA@H@Z-$LNbeg$??0Loud@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
main PROC
$LNbeg$main:
  push rbp
$LNpush$main:
  sub rsp, 80
$LNalloc$main:
  mov rbp, rsp
$LNfp$main:
$LNprolog$main:
  lea rax, [rbp+78]
  lea rax, [?addressed@?$C@H@@2HA]
  push rax
  lea rax, [rbp+64]
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  lea rax, [?bound@?$C@H@@2HA]
  push rax
  lea rax, [rbp+56]
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  mov rax, 30
  push rax
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  pop r10
  add eax, r10d
  movsxd rax, eax
  push rax
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [?other@?$C@H@@2HA]
  movsxd rax, DWORD PTR [rax]
  mov [rsp+40], rax
  lea rax, [rbp+79]
  push rax
  pop rcx
  mov rax, 0
  call ?get@?$C@H@@QEBAHXZ
  movsxd rax, eax
  mov [rsp+32], rax
  lea rax, [$_L_str_1]
  push rax
  lea rax, [?read@?$C@H@@2HA]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+64]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [?bound@?$C@H@@2HA]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop r9
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, [$_L_str_2]
  push rax
  mov rax, 4
  movsxd rax, eax
  push rax
  lea rax, [?built@?$C@H@@2ULoud@@A]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
  jmp $_L_return_main
  mov rax, 0
$_L_return_main:
  lea rsp, [rbp+80]
  pop rbp
  ret
$LNend$main:
main ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main DD imagerel $LNbeg$main
  DD imagerel $LNend$main
  DD imagerel $unwind$main
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main DB 01H
  DB $LNprolog$main-$LNbeg$main
  DB 3
  DB 05H
  DB $LNfp$main-$LNbeg$main
  DB 03H
  DB $LNalloc$main-$LNbeg$main
  DB 092H
  DB $LNpush$main-$LNbeg$main
  DB 050H
  DW 0
.xdata ENDS

.CODE
?get@?$C@H@@QEBAHXZ PROC
$LNbeg$?get@?$C@H@@QEBAHXZ:
  push rbp
$LNpush$?get@?$C@H@@QEBAHXZ:
  sub rsp, 16
$LNalloc$?get@?$C@H@@QEBAHXZ:
  mov rbp, rsp
$LNfp$?get@?$C@H@@QEBAHXZ:
$LNprolog$?get@?$C@H@@QEBAHXZ:
  mov rax, rcx
  mov QWORD PTR [rbp+8], rax
  lea rax, [?viaMember@?$C@H@@2HA]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?get@?$C@H@@QEBAHXZ
  mov rax, 0
$_L_return_?get@?$C@H@@QEBAHXZ:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$?get@?$C@H@@QEBAHXZ:
?get@?$C@H@@QEBAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?get@?$C@H@@QEBAHXZ DD imagerel $LNbeg$?get@?$C@H@@QEBAHXZ
  DD imagerel $LNend$?get@?$C@H@@QEBAHXZ
  DD imagerel $unwind$?get@?$C@H@@QEBAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?get@?$C@H@@QEBAHXZ DB 01H
  DB $LNprolog$?get@?$C@H@@QEBAHXZ-$LNbeg$?get@?$C@H@@QEBAHXZ
  DB 3
  DB 05H
  DB $LNfp$?get@?$C@H@@QEBAHXZ-$LNbeg$?get@?$C@H@@QEBAHXZ
  DB 03H
  DB $LNalloc$?get@?$C@H@@QEBAHXZ-$LNbeg$?get@?$C@H@@QEBAHXZ
  DB 012H
  DB $LNpush$?get@?$C@H@@QEBAHXZ-$LNbeg$?get@?$C@H@@QEBAHXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
$_GLOBAL__sub_I_template_static_member_on_use_cpp PROC
$LNbeg$$_GLOBAL__sub_I_template_static_member_on_use_cpp:
  push rbp
$LNpush$$_GLOBAL__sub_I_template_static_member_on_use_cpp:
  sub rsp, 32
$LNalloc$$_GLOBAL__sub_I_template_static_member_on_use_cpp:
  mov rbp, rsp
$LNfp$$_GLOBAL__sub_I_template_static_member_on_use_cpp:
$LNprolog$$_GLOBAL__sub_I_template_static_member_on_use_cpp:
  mov rax, 0
  push rax
  lea rax, [?other@?$C@H@@2HA$guard]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L__GLOBAL__sub_I_template_static_member_on_use_cpp_end_0
  mov rax, 1
  push rax
  lea rax, [?other@?$C@H@@2HA$guard]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 10
  push rax
  lea rax, [?viaOther@?$C@H@@2HA]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul eax, r10d
  movsxd rax, eax
  push rax
  lea rax, [?other@?$C@H@@2HA]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L__GLOBAL__sub_I_template_static_member_on_use_cpp_end_0:
  mov rax, 0
  push rax
  lea rax, [?built@?$C@H@@2ULoud@@A$guard]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L__GLOBAL__sub_I_template_static_member_on_use_cpp_end_1
  mov rax, 1
  push rax
  lea rax, [?built@?$C@H@@2ULoud@@A$guard]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [?built@?$C@H@@2ULoud@@A]
  push rax
  mov rax, 8
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Loud@@QEAA@H@Z
$_L__GLOBAL__sub_I_template_static_member_on_use_cpp_end_1:
  mov rax, 0
$_L_return__GLOBAL__sub_I_template_static_member_on_use_cpp:
  lea rsp, [rbp+32]
  pop rbp
  ret
$LNend$$_GLOBAL__sub_I_template_static_member_on_use_cpp:
$_GLOBAL__sub_I_template_static_member_on_use_cpp ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$$_GLOBAL__sub_I_template_static_member_on_use_cpp DD imagerel $LNbeg$$_GLOBAL__sub_I_template_static_member_on_use_cpp
  DD imagerel $LNend$$_GLOBAL__sub_I_template_static_member_on_use_cpp
  DD imagerel $unwind$$_GLOBAL__sub_I_template_static_member_on_use_cpp
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$$_GLOBAL__sub_I_template_static_member_on_use_cpp DB 01H
  DB $LNprolog$$_GLOBAL__sub_I_template_static_member_on_use_cpp-$LNbeg$$_GLOBAL__sub_I_template_static_member_on_use_cpp
  DB 3
  DB 05H
  DB $LNfp$$_GLOBAL__sub_I_template_static_member_on_use_cpp-$LNbeg$$_GLOBAL__sub_I_template_static_member_on_use_cpp
  DB 03H
  DB $LNalloc$$_GLOBAL__sub_I_template_static_member_on_use_cpp-$LNbeg$$_GLOBAL__sub_I_template_static_member_on_use_cpp
  DB 032H
  DB $LNpush$$_GLOBAL__sub_I_template_static_member_on_use_cpp-$LNbeg$$_GLOBAL__sub_I_template_static_member_on_use_cpp
  DB 050H
  DW 0
.xdata ENDS

.CODE

.CRT$XCU SEGMENT READONLY ALIGN(8) 'DATA'
  DQ $_GLOBAL__sub_I_template_static_member_on_use_cpp
.CRT$XCU ENDS

END
