; Generated by cxx1 for x86_64-windows, in MASM syntax for ml64.
; The instruction selection is the same one the Linux backend makes;
; only the spelling is Microsoft's. See src/backend/Masm.cpp.

OPTION DOTNAME
OPTION NOSCOPED
OPTION PROC:PRIVATE

PUBLIC ??0Base@@QEAA@H@Z
PUBLIC ??0Derived@@QEAA@H@Z
PUBLIC ??0Other@@QEAA@H@Z
PUBLIC ??_R0?AUBase@@@8
PUBLIC ??_R0?AUDerived@@@8
PUBLIC ??_R0?AUOther@@@8
PUBLIC ?anything@@YAHXZ
PUBLIC ?byBase@@YAHXZ
PUBLIC ?byValue@@YAHXZ
PUBLIC ?past@@YAHXZ
PUBLIC _CT??_R0?AUBase@@@84
PUBLIC _CT??_R0?AUDerived@@@84
PUBLIC _CT??_R0?AUOther@@@84
PUBLIC _CTA1?AUBase@@
PUBLIC _CTA1?AUOther@@
PUBLIC _CTA2?AUDerived@@
PUBLIC _TI1?AUBase@@
PUBLIC _TI1?AUOther@@
PUBLIC _TI2?AUDerived@@
PUBLIC main
EXTERN _CxxThrowException:PROC
EXTERN __CxxFrameHandler3:PROC
EXTERN printf:PROC


EXTRN ??_7type_info@@6B@:QWORD
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0?AUDerived@@@8)
??_R0?AUDerived@@@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.?AUDerived@@', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA' COMDAT(_CT??_R0?AUDerived@@@84)
_CT??_R0?AUDerived@@@84 DD 00H
  DD imagerel ??_R0?AUDerived@@@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 4
  DD 00H
.xdata$x ENDS
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0?AUBase@@@8)
??_R0?AUBase@@@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.?AUBase@@', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA' COMDAT(_CT??_R0?AUBase@@@84)
_CT??_R0?AUBase@@@84 DD 00H
  DD imagerel ??_R0?AUBase@@@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 4
  DD 00H
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_CTA2?AUDerived@@)
_CTA2?AUDerived@@ DD 2
  DD imagerel _CT??_R0?AUDerived@@@84
  DD imagerel _CT??_R0?AUBase@@@84
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_TI2?AUDerived@@)
_TI2?AUDerived@@ DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA2?AUDerived@@
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_CTA1?AUBase@@)
_CTA1?AUBase@@ DD 1
  DD imagerel _CT??_R0?AUBase@@@84
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_TI1?AUBase@@)
_TI1?AUBase@@ DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA1?AUBase@@
.xdata$x ENDS
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0?AUOther@@@8)
??_R0?AUOther@@@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.?AUOther@@', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA' COMDAT(_CT??_R0?AUOther@@@84)
_CT??_R0?AUOther@@@84 DD 00H
  DD imagerel ??_R0?AUOther@@@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 4
  DD 00H
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_CTA1?AUOther@@)
_CTA1?AUOther@@ DD 1
  DD imagerel _CT??_R0?AUOther@@@84
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_TI1?AUOther@@)
_TI1?AUOther@@ DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA1?AUOther@@
.xdata$x ENDS

.CONST
$_L_str_0 DB 37, 100, 32, 37, 100, 32, 37, 100, 32, 37, 100, 10, 0

.CODE
??0Base@@QEAA@H@Z PROC
$LNbeg$??0Base@@QEAA@H@Z:
  push rbp
$LNpush$??0Base@@QEAA@H@Z:
  sub rsp, 16
$LNalloc$??0Base@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0Base@@QEAA@H@Z:
$LNprolog$??0Base@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp], rax
  mov rax, rdx
  mov DWORD PTR [rbp+12], eax
  lea rax, [rbp+12]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
$_L_return_??0Base@@QEAA@H@Z:
  mov rax, [rbp]
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??0Base@@QEAA@H@Z:
??0Base@@QEAA@H@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??0Base@@QEAA@H@Z DD imagerel $LNbeg$??0Base@@QEAA@H@Z
  DD imagerel $LNend$??0Base@@QEAA@H@Z
  DD imagerel $unwind$??0Base@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??0Base@@QEAA@H@Z DB 01H
  DB $LNprolog$??0Base@@QEAA@H@Z-$LNbeg$??0Base@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0Base@@QEAA@H@Z-$LNbeg$??0Base@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0Base@@QEAA@H@Z-$LNbeg$??0Base@@QEAA@H@Z
  DB 012H
  DB $LNpush$??0Base@@QEAA@H@Z-$LNbeg$??0Base@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
??0Derived@@QEAA@H@Z PROC
$LNbeg$??0Derived@@QEAA@H@Z:
  push rbp
$LNpush$??0Derived@@QEAA@H@Z:
  sub rsp, 48
$LNalloc$??0Derived@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0Derived@@QEAA@H@Z:
$LNprolog$??0Derived@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+32], rax
  mov rax, rdx
  mov DWORD PTR [rbp+44], eax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Base@@QEAA@H@Z
  mov rax, 0
$_L_return_??0Derived@@QEAA@H@Z:
  mov rax, [rbp+32]
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??0Derived@@QEAA@H@Z:
??0Derived@@QEAA@H@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??0Derived@@QEAA@H@Z DD imagerel $LNbeg$??0Derived@@QEAA@H@Z
  DD imagerel $LNend$??0Derived@@QEAA@H@Z
  DD imagerel $unwind$??0Derived@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??0Derived@@QEAA@H@Z DB 01H
  DB $LNprolog$??0Derived@@QEAA@H@Z-$LNbeg$??0Derived@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0Derived@@QEAA@H@Z-$LNbeg$??0Derived@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0Derived@@QEAA@H@Z-$LNbeg$??0Derived@@QEAA@H@Z
  DB 052H
  DB $LNpush$??0Derived@@QEAA@H@Z-$LNbeg$??0Derived@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
??0Other@@QEAA@H@Z PROC
$LNbeg$??0Other@@QEAA@H@Z:
  push rbp
$LNpush$??0Other@@QEAA@H@Z:
  sub rsp, 16
$LNalloc$??0Other@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0Other@@QEAA@H@Z:
$LNprolog$??0Other@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp], rax
  mov rax, rdx
  mov DWORD PTR [rbp+12], eax
  lea rax, [rbp+12]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
$_L_return_??0Other@@QEAA@H@Z:
  mov rax, [rbp]
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??0Other@@QEAA@H@Z:
??0Other@@QEAA@H@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??0Other@@QEAA@H@Z DD imagerel $LNbeg$??0Other@@QEAA@H@Z
  DD imagerel $LNend$??0Other@@QEAA@H@Z
  DD imagerel $unwind$??0Other@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??0Other@@QEAA@H@Z DB 01H
  DB $LNprolog$??0Other@@QEAA@H@Z-$LNbeg$??0Other@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0Other@@QEAA@H@Z-$LNbeg$??0Other@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0Other@@QEAA@H@Z-$LNbeg$??0Other@@QEAA@H@Z
  DB 012H
  DB $LNpush$??0Other@@QEAA@H@Z-$LNbeg$??0Other@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?byBase@@YAHXZ PROC
$LNbeg$?byBase@@YAHXZ:
  push rbp
$LNpush$?byBase@@YAHXZ:
  sub rsp, 80
$LNalloc$?byBase@@YAHXZ:
  mov rbp, rsp
$LNfp$?byBase@@YAHXZ:
$LNprolog$?byBase@@YAHXZ:
  mov QWORD PTR [rbp+32], -2
$_L_?byBase@@YAHXZ_try_0:
  lea rax, [rbp+64]
  push rax
  mov rax, 9
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Derived@@QEAA@H@Z
  lea rax, [rbp+64]
  push rax
  lea rax, [rbp+60]
  mov r10, rax
  pop rax
  mov ecx, DWORD PTR [rax]
  mov DWORD PTR [r10], ecx
  mov rax, r10
  lea rax, [rbp+60]
  push rax
  lea rax, [_TI2?AUDerived@@]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
  nop
$_L_?byBase@@YAHXZ_tryend_0:
$_L_?byBase@@YAHXZ_caught_0:
  jmp $_L_?byBase@@YAHXZ_user_$msskip4
$_L_?byBase@@YAHXZ_user_$msret3:
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?byBase@@YAHXZ
$_L_?byBase@@YAHXZ_user_$msskip4:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?byBase@@YAHXZ
  mov rax, 0
$_L_return_?byBase@@YAHXZ:
  lea rsp, [rbp+80]
  pop rbp
  ret
$LNend$?byBase@@YAHXZ:
?byBase@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?byBase@@YAHXZ DD imagerel $LNbeg$?byBase@@YAHXZ
  DD imagerel $LNend$?byBase@@YAHXZ
  DD imagerel $unwind$?byBase@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?byBase@@YAHXZ DB 019H
  DB $LNprolog$?byBase@@YAHXZ-$LNbeg$?byBase@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?byBase@@YAHXZ-$LNbeg$?byBase@@YAHXZ
  DB 03H
  DB $LNalloc$?byBase@@YAHXZ-$LNbeg$?byBase@@YAHXZ
  DB 092H
  DB $LNpush$?byBase@@YAHXZ-$LNbeg$?byBase@@YAHXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?byBase@@YAHXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?byBase@@YAHXZ$catch$0 PROC
$LNbeg$?byBase@@YAHXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?byBase@@YAHXZ$catch$0:
  sub rsp, 32
$LNprolog$?byBase@@YAHXZ$catch$0:
  mov rbp, rdx
  lea rax, [rbp+48]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  movsxd rax, eax
  push rax
  lea rax, [rbp+44]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?byBase@@YAHXZ_user_$msret3]
  jmp $LNleave$?byBase@@YAHXZ$catch$0
  lea rax, $_L_?byBase@@YAHXZ_caught_0
$LNleave$?byBase@@YAHXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?byBase@@YAHXZ$catch$0:
?byBase@@YAHXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?byBase@@YAHXZ$catch$0 DB 019H
  DB $LNprolog$?byBase@@YAHXZ$catch$0-$LNbeg$?byBase@@YAHXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?byBase@@YAHXZ$catch$0-$LNbeg$?byBase@@YAHXZ$catch$0
  DB 032H
  DB $LNpush$?byBase@@YAHXZ$catch$0-$LNbeg$?byBase@@YAHXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?byBase@@YAHXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?byBase@@YAHXZ DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?byBase@@YAHXZ
  DD 1
  DD imagerel $tryMap$?byBase@@YAHXZ
  DD 4
  DD imagerel $ip2state$?byBase@@YAHXZ
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$?byBase@@YAHXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?byBase@@YAHXZ DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?byBase@@YAHXZ
$handlerMap$0$?byBase@@YAHXZ DD 8
  DD imagerel ??_R0?AUBase@@@8
  DD 48
  DD imagerel ?byBase@@YAHXZ$catch$0
  DD 56
$ip2state$?byBase@@YAHXZ DD imagerel $LNbeg$?byBase@@YAHXZ
  DD 0ffffffffH
  DD imagerel $_L_?byBase@@YAHXZ_try_0
  DD 0
  DD imagerel $_L_?byBase@@YAHXZ_tryend_0
  DD 0ffffffffH
  DD imagerel ?byBase@@YAHXZ$catch$0
  DD 1
.xdata ENDS

.CODE
?byValue@@YAHXZ PROC
$LNbeg$?byValue@@YAHXZ:
  push rbp
$LNpush$?byValue@@YAHXZ:
  sub rsp, 80
$LNalloc$?byValue@@YAHXZ:
  mov rbp, rsp
$LNfp$?byValue@@YAHXZ:
$LNprolog$?byValue@@YAHXZ:
  mov QWORD PTR [rbp+40], -2
$_L_?byValue@@YAHXZ_try_0:
  lea rax, [rbp+64]
  push rax
  mov rax, 5
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Base@@QEAA@H@Z
  lea rax, [rbp+64]
  push rax
  lea rax, [rbp+60]
  mov r10, rax
  pop rax
  mov ecx, DWORD PTR [rax]
  mov DWORD PTR [r10], ecx
  mov rax, r10
  lea rax, [rbp+60]
  push rax
  lea rax, [_TI1?AUBase@@]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
  nop
$_L_?byValue@@YAHXZ_tryend_0:
$_L_?byValue@@YAHXZ_caught_0:
  jmp $_L_?byValue@@YAHXZ_user_$msskip9
$_L_?byValue@@YAHXZ_user_$msret8:
  lea rax, [rbp+52]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?byValue@@YAHXZ
$_L_?byValue@@YAHXZ_user_$msskip9:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?byValue@@YAHXZ
  mov rax, 0
$_L_return_?byValue@@YAHXZ:
  lea rsp, [rbp+80]
  pop rbp
  ret
$LNend$?byValue@@YAHXZ:
?byValue@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?byValue@@YAHXZ DD imagerel $LNbeg$?byValue@@YAHXZ
  DD imagerel $LNend$?byValue@@YAHXZ
  DD imagerel $unwind$?byValue@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?byValue@@YAHXZ DB 019H
  DB $LNprolog$?byValue@@YAHXZ-$LNbeg$?byValue@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?byValue@@YAHXZ-$LNbeg$?byValue@@YAHXZ
  DB 03H
  DB $LNalloc$?byValue@@YAHXZ-$LNbeg$?byValue@@YAHXZ
  DB 092H
  DB $LNpush$?byValue@@YAHXZ-$LNbeg$?byValue@@YAHXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?byValue@@YAHXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?byValue@@YAHXZ$catch$0 PROC
$LNbeg$?byValue@@YAHXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?byValue@@YAHXZ$catch$0:
  sub rsp, 32
$LNprolog$?byValue@@YAHXZ$catch$0:
  mov rbp, rdx
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+52]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?byValue@@YAHXZ_user_$msret8]
  jmp $LNleave$?byValue@@YAHXZ$catch$0
  lea rax, $_L_?byValue@@YAHXZ_caught_0
$LNleave$?byValue@@YAHXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?byValue@@YAHXZ$catch$0:
?byValue@@YAHXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?byValue@@YAHXZ$catch$0 DB 019H
  DB $LNprolog$?byValue@@YAHXZ$catch$0-$LNbeg$?byValue@@YAHXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?byValue@@YAHXZ$catch$0-$LNbeg$?byValue@@YAHXZ$catch$0
  DB 032H
  DB $LNpush$?byValue@@YAHXZ$catch$0-$LNbeg$?byValue@@YAHXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?byValue@@YAHXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?byValue@@YAHXZ DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?byValue@@YAHXZ
  DD 1
  DD imagerel $tryMap$?byValue@@YAHXZ
  DD 4
  DD imagerel $ip2state$?byValue@@YAHXZ
  DD 40
  DD 00H
  DD 01H
$stateUnwindMap$?byValue@@YAHXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?byValue@@YAHXZ DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?byValue@@YAHXZ
$handlerMap$0$?byValue@@YAHXZ DD 0
  DD imagerel ??_R0?AUBase@@@8
  DD 56
  DD imagerel ?byValue@@YAHXZ$catch$0
  DD 56
$ip2state$?byValue@@YAHXZ DD imagerel $LNbeg$?byValue@@YAHXZ
  DD 0ffffffffH
  DD imagerel $_L_?byValue@@YAHXZ_try_0
  DD 0
  DD imagerel $_L_?byValue@@YAHXZ_tryend_0
  DD 0ffffffffH
  DD imagerel ?byValue@@YAHXZ$catch$0
  DD 1
.xdata ENDS

.CODE
?past@@YAHXZ PROC
$LNbeg$?past@@YAHXZ:
  push rbp
$LNpush$?past@@YAHXZ:
  sub rsp, 80
$LNalloc$?past@@YAHXZ:
  mov rbp, rsp
$LNfp$?past@@YAHXZ:
$LNprolog$?past@@YAHXZ:
  mov QWORD PTR [rbp+40], -2
$_L_?past@@YAHXZ_try_0:
  lea rax, [rbp+64]
  push rax
  mov rax, 3
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Other@@QEAA@H@Z
  lea rax, [rbp+64]
  push rax
  lea rax, [rbp+60]
  mov r10, rax
  pop rax
  mov ecx, DWORD PTR [rax]
  mov DWORD PTR [r10], ecx
  mov rax, r10
  lea rax, [rbp+60]
  push rax
  lea rax, [_TI1?AUOther@@]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
  nop
$_L_?past@@YAHXZ_tryend_0:
$_L_?past@@YAHXZ_caught_0:
  jmp $_L_?past@@YAHXZ_user_$msskip14
$_L_?past@@YAHXZ_user_$msret13:
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?past@@YAHXZ
$_L_?past@@YAHXZ_user_$msskip14:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?past@@YAHXZ
  mov rax, 0
$_L_return_?past@@YAHXZ:
  lea rsp, [rbp+80]
  pop rbp
  ret
$LNend$?past@@YAHXZ:
?past@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?past@@YAHXZ DD imagerel $LNbeg$?past@@YAHXZ
  DD imagerel $LNend$?past@@YAHXZ
  DD imagerel $unwind$?past@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?past@@YAHXZ DB 019H
  DB $LNprolog$?past@@YAHXZ-$LNbeg$?past@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?past@@YAHXZ-$LNbeg$?past@@YAHXZ
  DB 03H
  DB $LNalloc$?past@@YAHXZ-$LNbeg$?past@@YAHXZ
  DB 092H
  DB $LNpush$?past@@YAHXZ-$LNbeg$?past@@YAHXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?past@@YAHXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?past@@YAHXZ$catch$0 PROC
$LNbeg$?past@@YAHXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?past@@YAHXZ$catch$0:
  sub rsp, 32
$LNprolog$?past@@YAHXZ$catch$0:
  mov rbp, rdx
  mov rax, 2
  neg eax
  movsxd rax, eax
  push rax
  lea rax, [rbp+56]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?past@@YAHXZ_user_$msret13]
  jmp $LNleave$?past@@YAHXZ$catch$0
  lea rax, $_L_?past@@YAHXZ_caught_0
$LNleave$?past@@YAHXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?past@@YAHXZ$catch$0:
?past@@YAHXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?past@@YAHXZ$catch$0 DB 019H
  DB $LNprolog$?past@@YAHXZ$catch$0-$LNbeg$?past@@YAHXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?past@@YAHXZ$catch$0-$LNbeg$?past@@YAHXZ$catch$0
  DB 032H
  DB $LNpush$?past@@YAHXZ$catch$0-$LNbeg$?past@@YAHXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?past@@YAHXZ
.xdata ENDS

.text$x SEGMENT ALIGN(16) 'CODE'
?past@@YAHXZ$catch$1 PROC
$LNbeg$?past@@YAHXZ$catch$1:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?past@@YAHXZ$catch$1:
  sub rsp, 32
$LNprolog$?past@@YAHXZ$catch$1:
  mov rbp, rdx
  lea rax, [rbp+48]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  movsxd rax, eax
  push rax
  lea rax, [rbp+56]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?past@@YAHXZ_user_$msret13]
  jmp $LNleave$?past@@YAHXZ$catch$1
  lea rax, $_L_?past@@YAHXZ_caught_0
$LNleave$?past@@YAHXZ$catch$1:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?past@@YAHXZ$catch$1:
?past@@YAHXZ$catch$1 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?past@@YAHXZ$catch$1 DB 019H
  DB $LNprolog$?past@@YAHXZ$catch$1-$LNbeg$?past@@YAHXZ$catch$1
  DB 02H
  DB 00H
  DB $LNprolog$?past@@YAHXZ$catch$1-$LNbeg$?past@@YAHXZ$catch$1
  DB 032H
  DB $LNpush$?past@@YAHXZ$catch$1-$LNbeg$?past@@YAHXZ$catch$1
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?past@@YAHXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?past@@YAHXZ DD 019930522H
  DD 3
  DD imagerel $stateUnwindMap$?past@@YAHXZ
  DD 1
  DD imagerel $tryMap$?past@@YAHXZ
  DD 5
  DD imagerel $ip2state$?past@@YAHXZ
  DD 40
  DD 00H
  DD 01H
$stateUnwindMap$?past@@YAHXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?past@@YAHXZ DD 0
  DD 0
  DD 2
  DD 2
  DD imagerel $handlerMap$0$?past@@YAHXZ
$handlerMap$0$?past@@YAHXZ DD 8
  DD imagerel ??_R0?AUBase@@@8
  DD 0
  DD imagerel ?past@@YAHXZ$catch$0
  DD 56
  DD 8
  DD imagerel ??_R0?AUOther@@@8
  DD 48
  DD imagerel ?past@@YAHXZ$catch$1
  DD 56
$ip2state$?past@@YAHXZ DD imagerel $LNbeg$?past@@YAHXZ
  DD 0ffffffffH
  DD imagerel $_L_?past@@YAHXZ_try_0
  DD 0
  DD imagerel $_L_?past@@YAHXZ_tryend_0
  DD 0ffffffffH
  DD imagerel ?past@@YAHXZ$catch$0
  DD 1
  DD imagerel ?past@@YAHXZ$catch$1
  DD 2
.xdata ENDS

.CODE
?anything@@YAHXZ PROC
$LNbeg$?anything@@YAHXZ:
  push rbp
$LNpush$?anything@@YAHXZ:
  sub rsp, 64
$LNalloc$?anything@@YAHXZ:
  mov rbp, rsp
$LNfp$?anything@@YAHXZ:
$LNprolog$?anything@@YAHXZ:
  mov QWORD PTR [rbp+32], -2
$_L_?anything@@YAHXZ_try_0:
  lea rax, [rbp+48]
  push rax
  mov rax, 1
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Other@@QEAA@H@Z
  lea rax, [rbp+48]
  push rax
  lea rax, [rbp+44]
  mov r10, rax
  pop rax
  mov ecx, DWORD PTR [rax]
  mov DWORD PTR [r10], ecx
  mov rax, r10
  lea rax, [rbp+44]
  push rax
  lea rax, [_TI1?AUOther@@]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
  nop
$_L_?anything@@YAHXZ_tryend_0:
$_L_?anything@@YAHXZ_caught_0:
  jmp $_L_?anything@@YAHXZ_user_$msskip19
$_L_?anything@@YAHXZ_user_$msret18:
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?anything@@YAHXZ
$_L_?anything@@YAHXZ_user_$msskip19:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?anything@@YAHXZ
  mov rax, 0
$_L_return_?anything@@YAHXZ:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?anything@@YAHXZ:
?anything@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?anything@@YAHXZ DD imagerel $LNbeg$?anything@@YAHXZ
  DD imagerel $LNend$?anything@@YAHXZ
  DD imagerel $unwind$?anything@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?anything@@YAHXZ DB 019H
  DB $LNprolog$?anything@@YAHXZ-$LNbeg$?anything@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?anything@@YAHXZ-$LNbeg$?anything@@YAHXZ
  DB 03H
  DB $LNalloc$?anything@@YAHXZ-$LNbeg$?anything@@YAHXZ
  DB 072H
  DB $LNpush$?anything@@YAHXZ-$LNbeg$?anything@@YAHXZ
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?anything@@YAHXZ
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?anything@@YAHXZ$catch$0 PROC
$LNbeg$?anything@@YAHXZ$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?anything@@YAHXZ$catch$0:
  sub rsp, 32
$LNprolog$?anything@@YAHXZ$catch$0:
  mov rbp, rdx
  mov rax, 3
  neg eax
  movsxd rax, eax
  push rax
  lea rax, [rbp+40]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?anything@@YAHXZ_user_$msret18]
  jmp $LNleave$?anything@@YAHXZ$catch$0
  lea rax, $_L_?anything@@YAHXZ_caught_0
$LNleave$?anything@@YAHXZ$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?anything@@YAHXZ$catch$0:
?anything@@YAHXZ$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?anything@@YAHXZ$catch$0 DB 019H
  DB $LNprolog$?anything@@YAHXZ$catch$0-$LNbeg$?anything@@YAHXZ$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?anything@@YAHXZ$catch$0-$LNbeg$?anything@@YAHXZ$catch$0
  DB 032H
  DB $LNpush$?anything@@YAHXZ$catch$0-$LNbeg$?anything@@YAHXZ$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?anything@@YAHXZ
.xdata ENDS

.text$x SEGMENT ALIGN(16) 'CODE'
?anything@@YAHXZ$catch$1 PROC
$LNbeg$?anything@@YAHXZ$catch$1:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?anything@@YAHXZ$catch$1:
  sub rsp, 32
$LNprolog$?anything@@YAHXZ$catch$1:
  mov rbp, rdx
  mov rax, 8
  push rax
  lea rax, [rbp+40]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?anything@@YAHXZ_user_$msret18]
  jmp $LNleave$?anything@@YAHXZ$catch$1
  lea rax, $_L_?anything@@YAHXZ_caught_0
$LNleave$?anything@@YAHXZ$catch$1:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?anything@@YAHXZ$catch$1:
?anything@@YAHXZ$catch$1 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?anything@@YAHXZ$catch$1 DB 019H
  DB $LNprolog$?anything@@YAHXZ$catch$1-$LNbeg$?anything@@YAHXZ$catch$1
  DB 02H
  DB 00H
  DB $LNprolog$?anything@@YAHXZ$catch$1-$LNbeg$?anything@@YAHXZ$catch$1
  DB 032H
  DB $LNpush$?anything@@YAHXZ$catch$1-$LNbeg$?anything@@YAHXZ$catch$1
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?anything@@YAHXZ
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?anything@@YAHXZ DD 019930522H
  DD 3
  DD imagerel $stateUnwindMap$?anything@@YAHXZ
  DD 1
  DD imagerel $tryMap$?anything@@YAHXZ
  DD 5
  DD imagerel $ip2state$?anything@@YAHXZ
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$?anything@@YAHXZ DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?anything@@YAHXZ DD 0
  DD 0
  DD 2
  DD 2
  DD imagerel $handlerMap$0$?anything@@YAHXZ
$handlerMap$0$?anything@@YAHXZ DD 8
  DD imagerel ??_R0?AUBase@@@8
  DD 0
  DD imagerel ?anything@@YAHXZ$catch$0
  DD 56
  DD 040H
  DD 00H
  DD 0
  DD imagerel ?anything@@YAHXZ$catch$1
  DD 56
$ip2state$?anything@@YAHXZ DD imagerel $LNbeg$?anything@@YAHXZ
  DD 0ffffffffH
  DD imagerel $_L_?anything@@YAHXZ_try_0
  DD 0
  DD imagerel $_L_?anything@@YAHXZ_tryend_0
  DD 0ffffffffH
  DD imagerel ?anything@@YAHXZ$catch$0
  DD 1
  DD imagerel ?anything@@YAHXZ$catch$1
  DD 2
.xdata ENDS

.CODE
main PROC
$LNbeg$main:
  push rbp
$LNpush$main:
  sub rsp, 48
$LNalloc$main:
  mov rbp, rsp
$LNfp$main:
$LNprolog$main:
  mov rax, 0
  call ?anything@@YAHXZ
  movsxd rax, eax
  mov [rsp+32], rax
  lea rax, [$_L_str_0]
  push rax
  sub rsp, 8
  mov rax, 0
  sub rsp, 32
  call ?byBase@@YAHXZ
  add rsp, 40
  movsxd rax, eax
  push rax
  mov rax, 0
  sub rsp, 32
  call ?byValue@@YAHXZ
  add rsp, 32
  movsxd rax, eax
  push rax
  sub rsp, 8
  mov rax, 0
  sub rsp, 32
  call ?past@@YAHXZ
  add rsp, 40
  movsxd rax, eax
  push rax
  pop r9
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
  jmp $_L_return_main
  mov rax, 0
$_L_return_main:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$main:
main ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main DD imagerel $LNbeg$main
  DD imagerel $LNend$main
  DD imagerel $unwind$main
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main DB 01H
  DB $LNprolog$main-$LNbeg$main
  DB 3
  DB 05H
  DB $LNfp$main-$LNbeg$main
  DB 03H
  DB $LNalloc$main-$LNbeg$main
  DB 052H
  DB $LNpush$main-$LNbeg$main
  DB 050H
  DW 0
.xdata ENDS

.CODE

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?byBase@@YAHXZ$catch$0 DD imagerel $LNbeg$?byBase@@YAHXZ$catch$0
  DD imagerel $LNend$?byBase@@YAHXZ$catch$0
  DD imagerel $unwind$?byBase@@YAHXZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?byValue@@YAHXZ$catch$0 DD imagerel $LNbeg$?byValue@@YAHXZ$catch$0
  DD imagerel $LNend$?byValue@@YAHXZ$catch$0
  DD imagerel $unwind$?byValue@@YAHXZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?past@@YAHXZ$catch$0 DD imagerel $LNbeg$?past@@YAHXZ$catch$0
  DD imagerel $LNend$?past@@YAHXZ$catch$0
  DD imagerel $unwind$?past@@YAHXZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?past@@YAHXZ$catch$1 DD imagerel $LNbeg$?past@@YAHXZ$catch$1
  DD imagerel $LNend$?past@@YAHXZ$catch$1
  DD imagerel $unwind$?past@@YAHXZ$catch$1
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?anything@@YAHXZ$catch$0 DD imagerel $LNbeg$?anything@@YAHXZ$catch$0
  DD imagerel $LNend$?anything@@YAHXZ$catch$0
  DD imagerel $unwind$?anything@@YAHXZ$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?anything@@YAHXZ$catch$1 DD imagerel $LNbeg$?anything@@YAHXZ$catch$1
  DD imagerel $LNend$?anything@@YAHXZ$catch$1
  DD imagerel $unwind$?anything@@YAHXZ$catch$1
.pdata ENDS

END
