; Generated by cxx1 for x86_64-windows, in MASM syntax for ml64.
; The instruction selection is the same one the Linux backend makes;
; only the spelling is Microsoft's. See src/backend/Masm.cpp.

OPTION DOTNAME
OPTION NOSCOPED
OPTION PROC:PRIVATE

PUBLIC ??_R0D@8
PUBLIC ??_R0H@8
PUBLIC ??_R0N@8
PUBLIC ?inner@@YAHH@Z
PUBLIC ?risky@@YAXH@Z
PUBLIC _CT??_R0D@81
PUBLIC _CT??_R0H@84
PUBLIC _CT??_R0N@88
PUBLIC _CTA1D
PUBLIC _CTA1H
PUBLIC _CTA1N
PUBLIC _TI1D
PUBLIC _TI1H
PUBLIC _TI1N
PUBLIC main
EXTERN _CxxThrowException:PROC
EXTERN __CxxFrameHandler3:PROC
EXTERN printf:PROC


EXTRN ??_7type_info@@6B@:QWORD
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0H@8)
??_R0H@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.H', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA' COMDAT(_CT??_R0H@84)
_CT??_R0H@84 DD 01H
  DD imagerel ??_R0H@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 4
  DD 00H
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_CTA1H)
_CTA1H DD 1
  DD imagerel _CT??_R0H@84
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_TI1H)
_TI1H DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA1H
.xdata$x ENDS
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0N@8)
??_R0N@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.N', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA' COMDAT(_CT??_R0N@88)
_CT??_R0N@88 DD 01H
  DD imagerel ??_R0N@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 8
  DD 00H
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_CTA1N)
_CTA1N DD 1
  DD imagerel _CT??_R0N@88
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_TI1N)
_TI1N DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA1N
.xdata$x ENDS
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0D@8)
??_R0D@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.D', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA' COMDAT(_CT??_R0D@81)
_CT??_R0D@81 DD 01H
  DD imagerel ??_R0D@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 1
  DD 00H
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_CTA1D)
_CTA1D DD 1
  DD imagerel _CT??_R0D@81
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_TI1D)
_TI1D DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA1D
.xdata$x ENDS

.CONST
$_L_str_0 DB 105, 110, 110, 101, 114, 32, 105, 110, 116, 32, 37, 100, 10, 0
$_L_str_1 DB 37, 100, 58, 32, 110, 111, 116, 104, 105, 110, 103, 32, 116, 104, 114, 111
  DB 119, 110, 10, 0
$_L_str_2 DB 37, 100, 58, 32, 105, 110, 116, 32, 37, 100, 10, 0
$_L_str_3 DB 37, 100, 58, 32, 100, 111, 117, 98, 108, 101, 32, 37, 46, 49, 102, 10
  DB 0
$_L_str_4 DB 37, 100, 58, 32, 115, 111, 109, 101, 116, 104, 105, 110, 103, 32, 101, 108
  DB 115, 101, 10, 0
$_L_str_5 DB 37, 100, 10, 0
$_L_str_6 DB 116, 104, 114, 111, 117, 103, 104, 32, 105, 110, 110, 101, 114, 58, 32, 37
  DB 46, 49, 102, 10, 0
$_L_str_7 DB 100, 111, 110, 101, 10, 0

.CODE
?risky@@YAXH@Z PROC
$LNbeg$?risky@@YAXH@Z:
  push rbp
$LNpush$?risky@@YAXH@Z:
  sub rsp, 64
$LNalloc$?risky@@YAXH@Z:
  mov rbp, rsp
$LNfp$?risky@@YAXH@Z:
$LNprolog$?risky@@YAXH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+60], eax
  mov rax, 1
  push rax
  lea rax, [rbp+60]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?risky@@YAXH@Z_end_0
  mov rax, 7
  push rax
  lea rax, [rbp+56]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+56]
  push rax
  lea rax, [_TI1H]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
$_L_?risky@@YAXH@Z_end_0:
  mov rax, 2
  push rax
  lea rax, [rbp+60]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?risky@@YAXH@Z_end_1
  mov rax, 4612811918334230528
  movq xmm0, rax
  sub rsp, 8
  movsd QWORD PTR [rsp], xmm0
  lea rax, [rbp+48]
  mov r10, rax
  movsd xmm0, QWORD PTR [rsp]
  add rsp, 8
  movsd QWORD PTR [r10], xmm0
  lea rax, [rbp+48]
  push rax
  lea rax, [_TI1N]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
$_L_?risky@@YAXH@Z_end_1:
  mov rax, 3
  push rax
  lea rax, [rbp+60]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?risky@@YAXH@Z_end_2
  mov rax, 120
  push rax
  lea rax, [rbp+47]
  mov r10, rax
  pop rax
  mov BYTE PTR [r10], al
  movsx rax, al
  lea rax, [rbp+47]
  push rax
  lea rax, [_TI1D]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
$_L_?risky@@YAXH@Z_end_2:
  mov rax, 0
$_L_return_?risky@@YAXH@Z:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?risky@@YAXH@Z:
?risky@@YAXH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?risky@@YAXH@Z DD imagerel $LNbeg$?risky@@YAXH@Z
  DD imagerel $LNend$?risky@@YAXH@Z
  DD imagerel $unwind$?risky@@YAXH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?risky@@YAXH@Z DB 01H
  DB $LNprolog$?risky@@YAXH@Z-$LNbeg$?risky@@YAXH@Z
  DB 3
  DB 05H
  DB $LNfp$?risky@@YAXH@Z-$LNbeg$?risky@@YAXH@Z
  DB 03H
  DB $LNalloc$?risky@@YAXH@Z-$LNbeg$?risky@@YAXH@Z
  DB 072H
  DB $LNpush$?risky@@YAXH@Z-$LNbeg$?risky@@YAXH@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?inner@@YAHH@Z PROC
$LNbeg$?inner@@YAHH@Z:
  push rbp
$LNpush$?inner@@YAHH@Z:
  sub rsp, 80
$LNalloc$?inner@@YAHH@Z:
  mov rbp, rsp
$LNfp$?inner@@YAHH@Z:
$LNprolog$?inner@@YAHH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+76], eax
  mov QWORD PTR [rbp+40], -2
$_L_?inner@@YAHH@Z_try_0:
  lea rax, [rbp+76]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?risky@@YAXH@Z
  mov rax, 0
  jmp $_L_return_?inner@@YAHH@Z
$_L_?inner@@YAHH@Z_tryend_0:
$_L_?inner@@YAHH@Z_caught_0:
  jmp $_L_?inner@@YAHH@Z_user_$msskip6
$_L_?inner@@YAHH@Z_user_$msret5:
  lea rax, [rbp+52]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?inner@@YAHH@Z
$_L_?inner@@YAHH@Z_user_$msskip6:
  mov rax, 0
$_L_return_?inner@@YAHH@Z:
  lea rsp, [rbp+80]
  pop rbp
  ret
$LNend$?inner@@YAHH@Z:
?inner@@YAHH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?inner@@YAHH@Z DD imagerel $LNbeg$?inner@@YAHH@Z
  DD imagerel $LNend$?inner@@YAHH@Z
  DD imagerel $unwind$?inner@@YAHH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?inner@@YAHH@Z DB 019H
  DB $LNprolog$?inner@@YAHH@Z-$LNbeg$?inner@@YAHH@Z
  DB 3
  DB 05H
  DB $LNfp$?inner@@YAHH@Z-$LNbeg$?inner@@YAHH@Z
  DB 03H
  DB $LNalloc$?inner@@YAHH@Z-$LNbeg$?inner@@YAHH@Z
  DB 092H
  DB $LNpush$?inner@@YAHH@Z-$LNbeg$?inner@@YAHH@Z
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?inner@@YAHH@Z
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?inner@@YAHH@Z$catch$0 PROC
$LNbeg$?inner@@YAHH@Z$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?inner@@YAHH@Z$catch$0:
  sub rsp, 32
$LNprolog$?inner@@YAHH@Z$catch$0:
  mov rbp, rdx
  lea rax, [$_L_str_0]
  push rax
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 1
  push rax
  lea rax, [rbp+52]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$_L_?inner@@YAHH@Z_user_$msret5]
  jmp $LNleave$?inner@@YAHH@Z$catch$0
  lea rax, $_L_?inner@@YAHH@Z_caught_0
$LNleave$?inner@@YAHH@Z$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?inner@@YAHH@Z$catch$0:
?inner@@YAHH@Z$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?inner@@YAHH@Z$catch$0 DB 019H
  DB $LNprolog$?inner@@YAHH@Z$catch$0-$LNbeg$?inner@@YAHH@Z$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?inner@@YAHH@Z$catch$0-$LNbeg$?inner@@YAHH@Z$catch$0
  DB 032H
  DB $LNpush$?inner@@YAHH@Z$catch$0-$LNbeg$?inner@@YAHH@Z$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?inner@@YAHH@Z
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?inner@@YAHH@Z DD 019930522H
  DD 2
  DD imagerel $stateUnwindMap$?inner@@YAHH@Z
  DD 1
  DD imagerel $tryMap$?inner@@YAHH@Z
  DD 4
  DD imagerel $ip2state$?inner@@YAHH@Z
  DD 40
  DD 00H
  DD 01H
$stateUnwindMap$?inner@@YAHH@Z DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$?inner@@YAHH@Z DD 0
  DD 0
  DD 1
  DD 1
  DD imagerel $handlerMap$0$?inner@@YAHH@Z
$handlerMap$0$?inner@@YAHH@Z DD 0
  DD imagerel ??_R0H@8
  DD 56
  DD imagerel ?inner@@YAHH@Z$catch$0
  DD 56
$ip2state$?inner@@YAHH@Z DD imagerel $LNbeg$?inner@@YAHH@Z
  DD 0ffffffffH
  DD imagerel $_L_?inner@@YAHH@Z_try_0
  DD 0
  DD imagerel $_L_?inner@@YAHH@Z_tryend_0
  DD 0ffffffffH
  DD imagerel ?inner@@YAHH@Z$catch$0
  DD 1
.xdata ENDS

.CODE
main PROC
$LNbeg$main:
  push rbp
$LNpush$main:
  sub rsp, 96
$LNalloc$main:
  mov rbp, rsp
$LNfp$main:
$LNprolog$main:
  mov rax, 0
  push rax
  lea rax, [rbp+92]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_main_begin_0:
  mov rax, 3
  push rax
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setle al
  movzx rax, al
  cmp rax, 0
  je $_L_main_end_0
  mov QWORD PTR [rbp+56], -2
$_L_main_try_1:
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ?risky@@YAXH@Z
  lea rax, [$_L_str_1]
  push rax
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
$_L_main_tryend_1:
$_L_main_caught_1:
$_L_main_step_0:
  lea rax, [rbp+92]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_main_begin_0
$_L_main_end_0:
  lea rax, [$_L_str_5]
  push rax
  sub rsp, 8
  mov rax, 1
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?inner@@YAHH@Z
  add rsp, 40
  movsxd rax, eax
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov QWORD PTR [rbp+56], -2
$_L_main_try_2:
  mov rax, 2
  push rax
  pop rcx
  mov rax, 0
  call ?inner@@YAHH@Z
  movsxd rax, eax
$_L_main_tryend_2:
$_L_main_caught_2:
  lea rax, [$_L_str_7]
  push rax
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
  jmp $_L_return_main
  mov rax, 0
$_L_return_main:
  lea rsp, [rbp+96]
  pop rbp
  ret
$LNend$main:
main ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main DD imagerel $LNbeg$main
  DD imagerel $LNend$main
  DD imagerel $unwind$main
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main DB 019H
  DB $LNprolog$main-$LNbeg$main
  DB 3
  DB 05H
  DB $LNfp$main-$LNbeg$main
  DB 03H
  DB $LNalloc$main-$LNbeg$main
  DB 0B2H
  DB $LNpush$main-$LNbeg$main
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$main
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
main$catch$0 PROC
$LNbeg$main$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$main$catch$0:
  sub rsp, 32
$LNprolog$main$catch$0:
  mov rbp, rdx
  lea rax, [$_L_str_2]
  push rax
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+72]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, $_L_main_caught_1
$LNleave$main$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$main$catch$0:
main$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main$catch$0 DB 019H
  DB $LNprolog$main$catch$0-$LNbeg$main$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$main$catch$0-$LNbeg$main$catch$0
  DB 032H
  DB $LNpush$main$catch$0-$LNbeg$main$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$main
.xdata ENDS

.text$x SEGMENT ALIGN(16) 'CODE'
main$catch$1 PROC
$LNbeg$main$catch$1:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$main$catch$1:
  sub rsp, 32
$LNprolog$main$catch$1:
  mov rbp, rdx
  lea rax, [$_L_str_3]
  push rax
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+64]
  movsd xmm0, QWORD PTR [rax]
  sub rsp, 8
  movsd QWORD PTR [rsp], xmm0
  mov r8, [rsp]
  movsd xmm2, QWORD PTR [rsp]
  add rsp, 8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, $_L_main_caught_1
$LNleave$main$catch$1:
  add rsp, 32
  pop rbp
  ret 0
$LNend$main$catch$1:
main$catch$1 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main$catch$1 DB 019H
  DB $LNprolog$main$catch$1-$LNbeg$main$catch$1
  DB 02H
  DB 00H
  DB $LNprolog$main$catch$1-$LNbeg$main$catch$1
  DB 032H
  DB $LNpush$main$catch$1-$LNbeg$main$catch$1
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$main
.xdata ENDS

.text$x SEGMENT ALIGN(16) 'CODE'
main$catch$2 PROC
$LNbeg$main$catch$2:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$main$catch$2:
  sub rsp, 32
$LNprolog$main$catch$2:
  mov rbp, rdx
  lea rax, [$_L_str_4]
  push rax
  lea rax, [rbp+92]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, $_L_main_caught_1
$LNleave$main$catch$2:
  add rsp, 32
  pop rbp
  ret 0
$LNend$main$catch$2:
main$catch$2 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main$catch$2 DB 019H
  DB $LNprolog$main$catch$2-$LNbeg$main$catch$2
  DB 02H
  DB 00H
  DB $LNprolog$main$catch$2-$LNbeg$main$catch$2
  DB 032H
  DB $LNpush$main$catch$2-$LNbeg$main$catch$2
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$main
.xdata ENDS

.text$x SEGMENT ALIGN(16) 'CODE'
main$catch$3 PROC
$LNbeg$main$catch$3:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$main$catch$3:
  sub rsp, 32
$LNprolog$main$catch$3:
  mov rbp, rdx
  lea rax, [$_L_str_6]
  push rax
  lea rax, [rbp+64]
  movsd xmm0, QWORD PTR [rax]
  sub rsp, 8
  movsd QWORD PTR [rsp], xmm0
  mov rdx, [rsp]
  movsd xmm1, QWORD PTR [rsp]
  add rsp, 8
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, $_L_main_caught_2
$LNleave$main$catch$3:
  add rsp, 32
  pop rbp
  ret 0
$LNend$main$catch$3:
main$catch$3 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main$catch$3 DB 019H
  DB $LNprolog$main$catch$3-$LNbeg$main$catch$3
  DB 02H
  DB 00H
  DB $LNprolog$main$catch$3-$LNbeg$main$catch$3
  DB 032H
  DB $LNpush$main$catch$3-$LNbeg$main$catch$3
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$main
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$main DD 019930522H
  DD 6
  DD imagerel $stateUnwindMap$main
  DD 2
  DD imagerel $tryMap$main
  DD 9
  DD imagerel $ip2state$main
  DD 56
  DD 00H
  DD 01H
$stateUnwindMap$main DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 0ffffffffH
  DD 00H
$tryMap$main DD 0
  DD 0
  DD 3
  DD 3
  DD imagerel $handlerMap$0$main
  DD 4
  DD 4
  DD 5
  DD 1
  DD imagerel $handlerMap$1$main
$handlerMap$0$main DD 0
  DD imagerel ??_R0H@8
  DD 72
  DD imagerel main$catch$0
  DD 56
  DD 0
  DD imagerel ??_R0N@8
  DD 64
  DD imagerel main$catch$1
  DD 56
  DD 040H
  DD 00H
  DD 0
  DD imagerel main$catch$2
  DD 56
$handlerMap$1$main DD 0
  DD imagerel ??_R0N@8
  DD 64
  DD imagerel main$catch$3
  DD 56
$ip2state$main DD imagerel $LNbeg$main
  DD 0ffffffffH
  DD imagerel $_L_main_try_1
  DD 0
  DD imagerel $_L_main_tryend_1
  DD 0ffffffffH
  DD imagerel $_L_main_try_2
  DD 4
  DD imagerel $_L_main_tryend_2
  DD 0ffffffffH
  DD imagerel main$catch$0
  DD 1
  DD imagerel main$catch$1
  DD 2
  DD imagerel main$catch$2
  DD 3
  DD imagerel main$catch$3
  DD 5
.xdata ENDS

.CODE

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?inner@@YAHH@Z$catch$0 DD imagerel $LNbeg$?inner@@YAHH@Z$catch$0
  DD imagerel $LNend$?inner@@YAHH@Z$catch$0
  DD imagerel $unwind$?inner@@YAHH@Z$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main$catch$0 DD imagerel $LNbeg$main$catch$0
  DD imagerel $LNend$main$catch$0
  DD imagerel $unwind$main$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main$catch$1 DD imagerel $LNbeg$main$catch$1
  DD imagerel $LNend$main$catch$1
  DD imagerel $unwind$main$catch$1
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main$catch$2 DD imagerel $LNbeg$main$catch$2
  DD imagerel $LNend$main$catch$2
  DD imagerel $unwind$main$catch$2
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main$catch$3 DD imagerel $LNbeg$main$catch$3
  DD imagerel $LNend$main$catch$3
  DD imagerel $unwind$main$catch$3
.pdata ENDS

END
